In [27]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 200)
gini = pd.read_csv('gini.csv')

In [85]:
#gini_last_30 = gini.iloc[:, np.r_[:1, 189:220]]
#gini_last_30

In [30]:
#gini_last_30.to_csv('gini_last_30.csv', index=False)

In [191]:
gini = pd.read_csv('gini.csv')
gini_last_10 = gini.iloc[:, np.r_[:1, 207:218]]
gini_last_10

,country,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Afghanistan,36.8,36.8,36.8,36.8,36.8,36.8,36.8,36.8,36.8,36.8,36.8
1,Albania,30.4,30.2,30.0,29.7,29.5,29.3,29.1,29.0,29.0,29.0,29.0
2,Algeria,30.3,29.9,29.4,29.0,28.5,28.2,27.9,27.7,27.6,27.6,27.6
3,Andorra,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
4,Angola,46.2,45.0,44.1,43.4,42.9,42.7,42.6,42.6,42.6,42.6,42.6
5,Antigua and Barbuda,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
6,Argentina,46.7,45.8,44.9,44.0,43.0,42.3,41.8,41.6,41.6,41.8,42.1
7,Armenia,32.7,30.8,29.6,29.6,29.2,29.5,30.2,30.7,31.3,31.9,32.3
8,Australia,34.7,34.9,35.0,34.2,33.6,32.9,32.4,31.9,32.2,32.3,32.3
9,Austria,29.8,30.2,30.5,30.7,30.7,30.8,30.6,30.6,30.6,30.6,30.5
10,Azerbaijan,31.9,31.7,31.8,32.1,32.2,32.4,32.4,32.4,32.4,32.4,32.4
11,Bahamas,43.7,43.7,43.7,43.7,43.7,43.7,43.7,43.7,43.7,43.7,43.7
12,Bahrain,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
13,Bangladesh,33.0,32.8,32.6,32.4,32.3,32.2,32.2,32.3,32.3,32.3,32.4
14,Barbados,44.4,44.2,44.1,44.0,43.9,43.8,43.8,43.8,43.8,43.8,43.8
15,Belarus,28.0,28.2,28.4,28.2,27.6,27.3,27.2,26.8,26.8,26.9,27.0
16,Belgium,29.1,28.7,28.5,28.5,28.2,28.0,27.9,27.8,27.8,27.8,27.8
17,Belize,53.3,53.3,53.3,53.3,53.3,53.3,53.3,53.3,53.3,53.3,53.3
18,Benin,40.2,40.7,41.3,41.8,42.4,43.1,44.0,45.1,46.0,46.9,47.5
19,Bhutan,39.0,38.6,38.4,38.4,38.5,38.6,38.6,38.5,38.3,38.0,37.8
20,Bolivia,55.1,54.0,51.8,49.7,48.1,47.4,47.1,47.0,46.7,46.3,45.7
21,Bosnia and Herzegovina,33.5,33.3,33.1,33.0,33.0,33.0,32.9,32.9,32.8,32.7,32.7
22,Botswana,62.9,62.3,61.7,61.2,60.8,60.6,60.5,60.5,60.5,60.5,60.5
23,Brazil,55.5,54.9,54.3,53.8,53.3,53.1,52.6,52.2,51.9,51.6,51.4
24,Brunei,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
25,Bulgaria,33.2,33.7,34.2,33.9,34.7,35.3,36.0,36.3,37.0,37.3,37.4
26,Burkina Faso,41.5,40.9,40.3,39.6,38.8,38.0,37.1,36.4,35.8,35.5,35.3
27,Burundi,34.5,34.4,34.7,35.3,36.0,36.6,37.3,37.8,38.2,38.5,38.6
28,Cambodia,42.0,42.0,42.0,42.0,42.0,42.0,42.0,42.0,42.0,42.0,42.0
29,Cameroon,42.8,43.1,43.5,43.9,44.5,45.0,45.5,46.0,46.3,46.5,46.6
30,Canada,33.8,33.8,33.7,33.7,33.7,33.8,33.3,32.8,32.2,31.7,31.1
31,Cape Verde,49.0,48.3,47.7,47.4,47.2,47.2,47.2,47.2,47.2,47.2,47.2
32,Central African Republic,51.2,53.2,54.7,55.7,56.2,56.2,56.2,56.2,56.2,56.2,56.2
33,Chad,41.1,41.6,42.0,42.4,42.8,43.1,43.2,43.3,43.3,43.3,43.3
34,Chile,49.0,48.7,48.5,48.4,48.2,47.9,47.6,47.5,47.5,47.5,47.6
35,China,41.5,41.9,42.3,42.5,42.5,41.9,41.3,40.6,40.0,39.4,39.2
36,Colombia,54.6,54.5,54.7,54.6,54.2,53.7,53.4,52.7,52.1,51.7,51.3
37,Comoros,53.8,52.8,51.7,50.6,49.6,48.5,47.5,46.6,46.0,45.5,45.3
38,"Congo, Dem. Rep.",42.2,42.1,42.1,42.1,42.1,42.1,42.1,42.1,42.1,42.1,42.1
39,"Congo, Rep.",47.6,47.9,48.1,48.4,48.6,48.8,48.9,48.9,48.9,48.9,48.9
40,Costa Rica,48.6,49.1,49.2,49.1,48.9,49.1,48.7,48.7,48.7,48.7,48.6
41,Cote d'Ivoire,42.6,42.8,42.8,42.8,42.7,42.4,42.2,42.0,41.8,41.6,41.5
42,Croatia,31.7,32.3,32.2,32.3,32.2,31.9,31.7,32.0,31.8,31.5,31.3
43,Cuba,42.9,43.0,43.2,43.2,43.3,43.4,43.4,43.4,43.4,43.4,43.4
44,Cyprus,30.9,31.3,31.5,31.8,32.4,33.5,34.2,34.7,35.0,34.9,34.3
45,Czech Republic,26.7,26.4,26.4,26.3,26.3,26.3,26.3,26.2,26.0,26.0,25.9
46,Denmark,25.5,25.8,26.2,26.5,26.8,27.5,27.8,28.0,28.2,28.3,28.2
47,Djibouti,42.1,42.6,43.1,43.6,44.1,44.3,44.4,44.4,44.3,44.1,44.1
48,Dominica,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
49,Dominican Republic,50.0,49.3,48.7,47.8,47.2,47.1,46.2,45.7,45.3,45.3,44.9
50,Ecuador,52.4,51.4,50.5,49.2,47.8,47.2,46.5,46.0,45.8,45.6,45.2
51,Egypt,31.7,31.5,31.4,31.3,31.2,30.9,30.8,30.9,31.0,31.2,31.6
52,El Salvador,46.8,46.4,45.4,44.8,44.1,43.4,42.5,41.9,41.5,41.1,40.4
53,Equatorial Guinea,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
54,Eritrea,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
55,Estonia,32.9,32.3,32.0,31.8,32.2,32.8,33.4,33.5,33.6,33.5,33.1
56,Ethiopia,30.5,30.9,31.5,32.1,32.7,33.5,34.5,35.5,36.7,37.7,38.4
57,Fiji,39.2,39.6,39.8,39.7,39.4,38.9,38.2,37.6,37.1,36.8,36.7
58,Finland,27.9,27.8,27.9,27.8,27.5,27.4,27.3,27.2,27.1,27.1,27.0
59,France,31.1,31.5,32.3,33.0,33.2,33.1,33.0,32.8,32.7,32.6,32.6
60,Gabon,41.9,41.5,41.1,40.8,40.5,40.1,39.8,39.4,39.1,38.7,38.4
61,Gambia,46.3,45.7,45.2,44.6,43.9,43.0,41.8,40.5,39.0,37.8,36.8
62,Georgia,37.4,37.7,38.3,38.8,38.9,39.0,38.8,38.1,37.5,37.0,36.6
63,Germany,31.0,31.0,30.9,30.7,30.6,30.7,30.8,31.1,31.4,31.6,31.7
64,Ghana,42.5,42.6,42.7,42.6,42.5,42.5,42.4,42.4,42.4,42.4,42.4
65,Greece,34.2,34.2,34.1,34.0,34.5,35.0,35.4,35.8,36.0,36.0,36.0
66,Grenada,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
67,Guatemala,54.1,53.6,53.0,52.2,51.4,50.7,49.9,49.2,48.8,48.5,48.3
68,Guinea,40.2,39.2,38.2,37.1,36.0,35.1,34.4,34.0,33.7,33.7,33.7
69,Guinea-Bissau,43.1,45.0,46.9,48.4,49.5,50.3,50.7,50.7,50.7,50.7,50.7
70,Guyana,43.2,43.2,43.2,43.2,43.2,43.2,43.2,43.2,43.2,43.2,43.2
71,Haiti,55.6,54.8,54.0,53.3,52.5,51.9,51.4,51.1,50.9,50.9,50.9
72,Holy See,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
73,Honduras,57.3,55.9,54.6,54.4,54.4,53.9,53.7,53.0,51.7,50.5,50.0
74,Hungary,29.6,29.0,28.4,28.5,28.8,29.6,30.4,30.6,30.8,30.7,30.5
75,Iceland,29.7,29.8,29.3,28.6,28.0,26.8,26.6,26.9,27.1,27.3,27.8
76,India,34.2,34.4,34.6,34.7,34.9,35.0,35.1,35.1,35.1,35.1,35.1
77,Indonesia,33.8,34.4,35.2,36.4,37.3,38.2,39.0,39.7,39.4,39.1,38.9
78,Iran,43.7,43.4,42.9,41.9,40.8,39.7,39.1,38.6,38.4,38.5,38.8
79,Iraq,28.6,28.7,28.8,29.0,29.2,29.3,29.4,29.5,29.5,29.5,29.5
80,Ireland,32.6,32.4,32.1,32.1,32.4,32.9,32.8,32.7,32.4,32.2,31.8
81,Israel,41.3,41.5,41.7,41.8,41.9,41.9,41.7,41.5,41.4,41.4,41.4
82,Italy,33.7,33.6,33.8,34.1,34.5,34.7,34.9,35.0,35.1,35.2,35.3
83,Jamaica,45.5,45.5,45.5,45.5,45.5,45.5,45.5,45.5,45.5,45.5,45.5
84,Japan,32.0,32.0,31.9,32.1,32.1,32.1,32.1,32.1,32.1,32.1,32.1
85,Jordan,34.7,33.9,33.5,33.3,33.2,33.3,33.6,33.7,33.7,33.7,33.7
86,Kazakhstan,30.4,29.6,29.0,28.6,28.2,27.9,27.6,27.4,27.2,26.9,26.9
87,Kenya,46.0,45.7,45.3,44.7,44.2,43.6,43.0,42.5,41.9,41.5,41.1
88,Kiribati,37.0,37.0,37.0,37.0,37.0,37.0,37.0,37.0,37.0,37.0,37.0
89,Kuwait,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
90,Kyrgyz Republic,34.0,33.0,32.5,30.6,29.3,28.8,28.2,28.0,27.8,27.6,27.2
91,Lao,34.3,34.7,35.2,35.5,35.8,36.0,36.1,36.3,36.3,36.4,36.4
92,Latvia,36.7,36.6,35.9,35.9,35.6,35.4,35.3,35.2,34.9,34.6,34.4
93,Lebanon,31.8,31.8,31.8,31.8,31.8,31.8,31.8,31.8,31.8,31.8,31.8
94,Lesotho,52.7,53.1,53.4,53.7,54.0,54.1,54.2,54.2,54.2,54.2,54.2
95,Liberia,36.4,36.2,35.9,35.6,35.1,34.6,34.2,33.8,33.5,33.3,33.2
96,Libya,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
97,Liechtenstein,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
98,Lithuania,35.4,35.6,35.3,34.9,35.0,34.7,34.8,35.6,36.6,37.0,37.4
99,Luxembourg,31.1,31.3,31.3,31.5,32.1,32.0,32.0,32.7,33.0,32.9,33.3
100,Madagascar,40.9,40.9,41.4,41.8,42.2,42.4,42.6,42.6,42.7,42.7,42.7
101,Malawi,41.7,41.7,42.7,43.6,44.4,44.9,45.3,45.5,45.5,45.5,45.5
102,Malaysia,46.0,45.9,45.6,45.2,44.5,43.6,42.8,42.1,41.5,41.2,41.1
103,Maldives,40.1,39.6,39.2,38.9,38.6,38.5,38.4,38.4,38.4,38.4,38.4
104,Mali,38.2,37.2,36.0,34.8,33.9,33.3,33.0,33.0,33.0,33.0,33.0
105,Malta,28.5,28.9,29.1,29.3,29.4,29.3,29.1,29.2,29.2,29.2,29.3
106,Marshall Islands,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
107,Mauritania,37.9,36.9,36.1,35.3,34.7,34.2,33.6,33.2,32.9,32.7,32.6
108,Mauritius,35.5,35.6,35.7,35.7,35.8,35.8,35.8,35.8,35.8,35.8,35.8
109,Mexico,48.4,47.9,47.3,46.9,46.8,46.8,46.9,46.9,46.8,46.5,46.3
110,"Micronesia, Fed. Sts.",42.0,41.8,41.5,41.2,40.9,40.6,40.4,40.2,40.1,40.1,40.1
111,Moldova,35.2,34.7,33.9,32.9,31.9,30.7,29.4,28.4,27.6,27.0,26.6
112,Monaco,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
113,Mongolia,34.8,35.0,34.7,34.5,34.2,33.6,33.1,33.0,32.6,32.4,32.3
114,Montenegro,30.5,30.6,30.4,30.5,30.7,31.1,31.3,31.9,32.1,32.0,31.9
115,Morocco,40.7,40.6,40.5,40.4,40.2,40.1,39.9,39.8,39.7,39.6,39.6
116,Mozambique,46.3,46.1,46.2,46.6,47.3,48.4,49.8,51.2,52.3,53.2,53.7
117,Myanmar,38.1,38.1,38.1,38.1,38.1,38.1,38.1,38.1,38.1,38.1,38.1
118,Namibia,62.5,62.1,61.8,61.4,61.0,60.7,60.3,60.0,59.7,59.5,59.3
119,Nauru,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
120,Nepal,40.6,39.1,37.5,36.0,34.7,33.8,33.2,32.8,32.8,32.8,32.8
121,Netherlands,29.6,29.2,28.9,28.5,28.1,27.8,28.0,28.1,28.2,28.3,28.3
122,New Zealand,32.8,32.7,32.6,33.1,33.2,33.2,33.5,34.0,34.0,34.5,34.8
123,Nicaragua,44.6,44.3,44.2,44.3,44.5,44.8,45.3,45.6,45.9,46.1,46.2
124,Niger,41.5,39.8,37.6,35.4,34.0,33.2,33.0,33.1,33.7,34.1,34.3
125,Nigeria,41.0,41.5,42.0,42.4,42.7,42.9,43.0,43.0,43.0,43.0,43.0
126,North Korea,37.0,37.0,37.0,37.0,37.0,37.0,37.0,37.0,37.0,37.0,37.0
127,North Macedonia,42.2,43.1,43.2,42.7,41.5,39.7,38.3,37.3,36.4,35.8,35.6
128,Norway,28.5,27.4,26.5,26.3,26.0,25.9,26.0,26.3,26.8,27.1,27.4
129,Oman,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
130,Pakistan,32.2,32.0,31.6,31.0,30.8,30.6,30.5,30.9,31.6,32.1,32.6
131,Palau,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
132,Palestine,34.7,34.8,34.9,35.0,34.7,34.5,34.4,34.2,34.1,33.9,33.8
133,Panama,53.9,53.3,52.9,52.2,52.0,51.7,51.4,51.2,51.0,50.7,50.5
134,Papua New Guinea,45.7,44.8,43.8,43.0,42.4,42.0,41.9,41.9,41.9,41.9,41.9
135,Paraguay,52.1,51.5,51.4,51.2,50.2,49.6,49.9,49.2,48.4,48.4,48.4
136,Peru,50.0,49.4,48.4,47.2,46.1,45.3,44.6,44.1,43.9,43.7,43.6
137,Philippines,44.6,44.6,44.5,44.3,44.2,44.1,43.9,43.5,43.1,42.7,42.4
138,Poland,34.7,34.0,33.6,33.4,33.2,33.0,32.8,32.6,32.1,31.7,31.3
139,Portugal,37.8,37.0,36.4,36.1,36.0,35.9,36.0,35.9,35.8,35.7,35.5
140,Qatar,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
141,Romania,32.4,32.7,33.1,32.4,32.0,31.9,32.7,33.5,32.9,32.1,31.4
142,Russia,41.3,41.2,40.8,40.6,40.3,40.1,40.2,39.8,39.4,38.8,38.2
143,Rwanda,51.0,50.7,50.1,49.1,48.2,47.4,46.6,46.0,45.5,45.3,45.1
144,Samoa,42.1,42.1,42.1,42.1,42.1,42.1,42.1,42.1,42.1,42.1,42.1
145,San Marino,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
146,Sao Tome and Principe,31.4,31.3,31.1,31.0,30.9,30.8,30.8,30.8,30.8,30.8,30.8
147,Saudi Arabia,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
148,Senegal,39.6,39.5,39.6,39.8,39.9,40.1,40.2,40.3,40.3,40.3,40.3
149,Serbia,31.6,30.1,28.6,29.5,31.8,33.1,35.4,36.4,36.3,35.2,35.1
150,Seychelles,42.9,43.2,43.6,44.1,44.8,45.5,46.0,46.4,46.7,46.8,46.8
151,Sierra Leone,38.4,37.5,36.7,35.8,35.1,34.6,34.2,34.0,34.0,34.0,34.0
152,Singapore,42.4,42.5,42.6,42.7,42.5,42.2,42.0,41.7,41.4,40.9,40.9
153,Slovak Republic,27.4,27.1,26.7,26.7,26.6,26.9,26.8,26.7,26.7,26.7,26.4
154,Slovenia,24.4,24.4,24.4,24.5,24.8,25.3,25.5,25.6,25.7,25.6,25.5
155,Solomon Islands,44.7,43.8,42.7,41.6,40.4,39.3,38.4,37.7,37.3,37.1,37.1
156,Somalia,47.8,47.8,47.9,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0
157,South Africa,63.9,63.9,63.6,63.4,63.3,63.2,63.2,63.2,63.1,63.1,63.0
158,South Korea,32.0,32.0,32.0,32.1,32.0,31.8,31.7,31.6,31.6,31.6,31.6
159,South Sudan,45.0,45.3,45.3,45.3,45.3,45.3,45.0,45.0,45.0,45.0,45.0
160,Spain,33.5,33.9,34.4,34.8,35.1,35.5,35.7,35.9,36.0,36.2,36.2
161,Sri Lanka,40.2,39.6,38.7,38.1,37.7,37.8,38.1,38.7,39.2,39.6,39.7
162,St. Kitts and Nevis,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
163,St. Lucia,42.6,42.6,42.6,42.6,42.6,42.6,42.6,42.6,42.6,42.6,42.6
164,St. Vincent and the Grenadines,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
165,Sudan,35.5,35.5,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4
166,Suriname,59.8,60.1,60.4,60.6,60.8,60.9,61.0,61.0,61.0,61.0,61.0
167,Swaziland,52.0,51.8,51.7,51.6,51.5,51.5,51.5,51.5,51.5,51.5,51.5
168,Sweden,26.9,27.1,27.3,27.6,27.7,27.8,28.0,28.3,28.6,28.8,28.9
169,Switzerland,34.1,33.7,33.5,33.0,32.5,32.2,32.2,32.1,32.2,32.4,32.4
170,Syria,35.6,35.5,35.4,35.3,35.3,35.3,35.2,35.2,35.2,35.2,35.2
171,Tajikistan,32.6,32.0,31.7,31.5,31.6,31.9,32.4,32.9,33.4,33.7,33.9
172,Tanzania,39.6,39.7,39.6,39.3,38.8,38.4,38.1,37.9,37.8,37.8,37.8
173,Thailand,41.3,40.7,40.2,39.3,39.2,38.7,38.2,37.5,37.2,36.6,36.2
174,Timor-Leste,29.5,28.7,28.2,28.1,28.2,28.3,28.4,28.5,28.6,28.6,28.7
175,Togo,43.0,43.2,43.7,44.5,45.0,45.1,45.0,44.5,43.9,43.5,43.2
176,Tonga,37.6,37.5,37.5,37.5,37.5,37.5,37.5,37.5,37.5,37.5,37.5
177,Trinidad and Tobago,41.1,41.2,41.2,41.3,41.3,41.3,41.3,41.3,41.3,41.3,41.3
178,Tunisia,37.8,37.4,37.0,36.6,36.3,36.0,35.9,35.8,35.8,35.8,35.8
179,Turkey,40.2,39.7,39.0,39.1,39.4,39.6,40.1,40.9,41.3,41.6,41.9
180,Turkmenistan,46.4,46.4,46.4,46.4,46.4,46.4,46.4,46.4,46.4,46.4,46.4
181,Tuvalu,39.1,39.1,39.1,39.1,39.1,39.1,39.1,39.1,39.1,39.1,39.1
182,Uganda,43.6,43.5,43.6,43.6,43.4,42.9,42.4,41.9,41.7,41.9,42.2
183,Ukraine,28.3,27.6,26.7,25.7,25.2,24.8,24.5,24.7,24.8,24.8,24.9
184,United Arab Emirates,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
185,United Kingdom,34.9,34.6,34.6,34.3,33.7,33.5,33.4,33.2,33.2,33.4,33.4
186,United States,40.8,40.8,40.8,40.7,40.7,40.7,40.8,41.0,41.2,41.3,41.4
187,Uruguay,45.8,45.8,45.5,44.8,43.5,42.6,41.5,40.6,40.1,40.1,39.9
188,Uzbekistan,33.5,33.5,33.5,33.5,33.5,33.5,33.5,33.5,33.5,33.5,33.5
189,Vanuatu,37.6,37.6,37.6,37.6,37.6,37.6,37.6,37.6,37.6,37.6,37.6
190,Venezuela,48.6,48.0,46.9,46.9,46.9,46.9,46.9,46.9,46.9,46.9,46.9
191,Vietnam,36.0,36.1,36.7,37.1,37.1,37.0,36.5,35.6,35.2,35.1,35.1
192,Yemen,34.9,35.0,35.2,35.5,35.7,36.0,36.2,36.4,36.6,36.7,36.7
193,Zambia,53.3,54.7,55.0,55.3,55.6,55.9,56.2,56.5,56.8,57.0,57.1
194,Zimbabwe,43.2,43.2,43.2,43.2,43.2,43.2,43.2,43.2,43.2,43.2,43.2

In [192]:
gini_last_10 = gini_last_10.melt(id_vars=['country'], var_name='year', value_name='gini_index')
gini_last_10

          country  year  gini_index
0     Afghanistan  2006        36.8
1         Albania  2006        30.4
2         Algeria  2006        30.3
3         Andorra  2006        40.0
4          Angola  2006        46.2
...           ...   ...         ...
2140    Venezuela  2016        46.9
2141      Vietnam  2016        35.1
2142        Yemen  2016        36.7
2143       Zambia  2016        57.1
2144     Zimbabwe  2016        43.2

[2145 rows x 3 columns]

In [361]:
gini_last_10.isnull().sum()

country       0
year          0
gini_index    0
dtype: int64

In [193]:
gini_last_10.sort_values(by=['country', 'year'], inplace=True)
gini_last_10

          country  year  gini_index
0     Afghanistan  2006        36.8
195   Afghanistan  2007        36.8
390   Afghanistan  2008        36.8
585   Afghanistan  2009        36.8
780   Afghanistan  2010        36.8
...           ...   ...         ...
1364     Zimbabwe  2012        43.2
1559     Zimbabwe  2013        43.2
1754     Zimbabwe  2014        43.2
1949     Zimbabwe  2015        43.2
2144     Zimbabwe  2016        43.2

[2145 rows x 3 columns]

In [195]:
gini_last_10.to_csv('gini_last_10.csv', index=False)

In [135]:
gini_melt.isnull().sum()
gini_melt.duplicated().sum()
gini_melt.describe()
gini_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6045 entries, 0 to 6044
Data columns (total 3 columns):
country       6045 non-null object
year          6045 non-null object
gini_index    6045 non-null float64
dtypes: float64(1), object(2)
memory usage: 141.8+ KB

In [125]:
gini_melt.to_csv ('gini_last_30_long.csv', index=False)

In [131]:
ls *.csv

demox_eiu.csv
gapminder_full.csv
gini.csv
gini_last_20.csv
gini_last_30.csv
gini_last_30_long.csv
income_per_person_gdppercapita_ppp_inflation_adjusted.csv
investments_percent_of_gdp.csv
tax_revenue_percent_of_gdp.csv

In [171]:
demo = pd.read_csv('demox_eiu.csv')
demo.tail(100)

,country,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
64,Hungary,75.3,74.80,74.4,73.3,72.1,70.4,69.6,69.6,69.0,68.4,67.2,66.4,66.3
65,Iceland,97.1,96.80,96.5,96.5,96.5,96.5,96.5,96.5,95.8,95.8,95.0,95.8,95.8
66,India,76.8,77.40,78.0,75.4,72.8,73.0,75.2,76.9,79.2,77.4,78.1,72.3,72.3
67,Indonesia,64.1,63.80,63.4,64.3,65.3,65.3,67.6,68.2,69.5,70.3,69.7,63.9,63.9
68,Iran,29.3,28.80,28.3,23.9,19.4,19.8,19.8,19.8,19.8,21.6,23.4,24.5,24.5
69,Iraq,40.1,40.00,40.0,40.0,40.0,40.3,41.0,41.0,42.3,40.8,40.8,40.9,40.6
70,Ireland,90.1,90.10,90.1,89.0,87.9,85.6,85.6,86.8,87.2,88.5,91.5,91.5,91.5
71,Israel,72.8,73.80,74.8,74.8,74.8,75.3,75.3,75.3,76.3,77.7,78.5,77.9,77.9
72,Italy,77.3,78.50,79.8,79.0,78.3,77.4,77.4,78.5,78.5,79.8,79.8,79.8,77.1
73,Jamaica,73.4,72.80,72.1,72.1,72.1,71.3,73.9,73.9,73.9,73.9,73.9,72.9,70.2
74,Japan,81.5,82.00,82.5,81.7,80.8,80.8,80.8,80.8,80.8,79.6,79.9,78.8,79.9
75,Jordan,39.2,39.30,39.3,38.4,37.4,38.9,37.6,37.6,37.6,38.6,39.6,38.7,39.3
76,Kazakhstan,36.2,35.40,34.5,33.8,33.0,32.4,29.5,30.6,31.7,30.6,30.6,30.6,29.4
77,Kenya,50.8,49.40,47.9,47.5,47.1,47.1,47.1,51.3,51.3,53.3,53.3,51.1,51.1
78,Kuwait,30.9,32.40,33.9,36.4,38.8,37.4,37.8,37.8,37.8,38.5,38.5,38.5,38.5
79,Kyrgyz Republic,40.8,40.60,40.5,41.8,43.1,43.4,46.9,46.9,52.4,53.3,49.3,51.1,51.1
80,Lao,21.0,21.00,21.0,21.0,21.0,21.0,23.2,22.1,22.1,22.1,23.7,23.7,23.7
81,Latvia,73.7,73.00,72.3,71.4,70.5,70.5,70.5,70.5,74.8,73.7,73.1,72.5,73.8
82,Lebanon,58.2,57.20,56.2,57.2,58.2,53.2,50.5,50.5,51.2,48.6,48.6,47.2,46.3
83,Lesotho,64.8,63.90,62.9,61.5,60.2,63.3,66.6,66.6,66.6,65.9,65.9,66.4,66.4
84,Liberia,52.2,52.40,52.5,51.6,50.7,50.7,49.5,49.5,49.5,49.5,53.1,52.3,53.5
85,Libya,18.4,19.20,20.0,19.7,19.4,35.5,51.5,48.2,38.0,22.5,22.5,23.2,21.9
86,Lithuania,74.3,74.00,73.6,73.0,72.4,72.4,72.4,75.4,75.4,75.4,74.7,74.1,75.0
87,Luxembourg,91.0,91.00,91.0,89.9,88.8,88.8,88.8,88.8,88.8,88.8,88.1,88.1,88.1
88,Madagascar,58.2,57.00,55.7,47.5,39.4,39.3,39.3,43.2,44.2,48.5,50.7,51.1,52.2
89,Malawi,49.7,50.50,51.3,54.9,58.4,58.4,60.8,60.0,56.6,55.5,55.5,54.9,54.9
90,Malaysia,59.8,61.70,63.6,62.8,61.9,61.9,64.1,64.9,64.9,64.3,65.4,65.4,68.8
91,Mali,59.9,59.30,58.7,59.4,60.1,63.6,51.2,59.0,57.9,57.0,57.0,56.4,54.1
92,Malta,83.9,83.90,83.9,83.3,82.8,82.8,82.8,82.8,83.9,83.9,83.9,81.5,82.1
93,Mauritania,31.2,35.10,39.1,38.9,38.6,41.7,41.7,41.7,41.7,39.6,39.6,38.2,38.2
94,Mauritius,80.4,80.40,80.4,80.4,80.4,80.4,81.7,81.7,81.7,82.8,82.8,82.2,82.2
95,Mexico,66.7,67.30,67.8,68.5,69.3,69.3,69.0,69.1,66.8,65.5,64.7,64.1,61.9
96,Moldova,65.0,65.00,65.0,64.2,63.3,63.3,63.2,63.2,63.2,63.5,60.1,59.4,58.5
97,Mongolia,66.0,66.00,66.0,64.8,63.6,62.3,63.5,65.1,66.2,66.2,66.2,65.0,65.0
98,Montenegro,65.7,65.00,64.3,63.5,62.7,61.5,60.5,59.4,59.4,60.1,57.2,56.9,57.4
99,Morocco,39.0,38.90,38.8,38.4,37.9,38.3,40.7,40.7,40.0,46.6,47.7,48.7,49.9
100,Mozambique,52.8,53.90,54.9,52.0,49.0,49.0,48.8,47.7,46.6,46.0,40.2,40.2,38.5
101,Myanmar,17.7,17.70,17.7,17.7,17.7,17.7,23.5,27.6,30.5,41.4,42.0,38.3,38.3
102,Namibia,65.4,65.10,64.8,63.5,62.3,62.4,62.4,62.4,62.4,63.1,63.1,63.1,62.5
103,Nepal,34.2,37.40,40.5,41.5,42.4,42.4,41.6,47.7,47.7,47.7,48.6,51.8,51.8
104,Netherlands,96.6,96.00,95.3,92.6,89.9,89.9,89.9,88.4,89.2,89.2,88.0,88.9,88.9
105,New Zealand,90.1,91.00,91.9,92.3,92.6,92.6,92.6,92.6,92.6,92.6,92.6,92.6,92.6
106,Nicaragua,56.8,58.80,60.7,59.0,57.3,55.6,55.6,54.6,53.2,52.6,48.1,46.6,36.3
107,Niger,35.4,34.80,34.1,34.0,33.8,41.6,41.6,40.8,40.2,38.5,39.6,37.6,37.6
108,Nigeria,35.2,35.30,35.3,35.0,34.7,38.3,37.7,37.7,37.6,46.2,45.0,44.4,44.4
109,North Korea,10.3,9.45,8.6,9.7,10.8,10.8,10.8,10.8,10.8,10.8,10.8,10.8,10.8
110,North Macedonia,63.3,62.70,62.1,61.9,61.6,61.6,61.6,61.6,62.5,60.2,52.3,55.7,58.7
111,Norway,95.5,96.20,96.8,97.4,98.0,98.0,99.3,99.3,99.3,99.3,99.3,98.7,98.7
112,Oman,27.7,28.80,29.8,29.2,28.6,32.6,32.6,32.6,31.5,30.4,30.4,30.4,30.4
113,Pakistan,39.2,41.90,44.6,45.0,45.5,45.5,45.7,46.4,46.4,44.0,43.3,42.6,41.7
114,Palestine,60.1,59.20,58.3,56.4,54.4,49.7,48.0,48.0,47.2,45.7,44.9,44.6,43.9
115,Panama,73.5,73.50,73.5,72.5,71.5,70.8,70.8,70.8,70.8,71.9,71.3,70.8,70.5
116,Papua New Guinea,65.4,65.40,65.4,65.4,65.4,63.2,63.2,63.6,60.3,60.3,60.3,60.3,60.3
117,Paraguay,61.6,62.80,64.0,64.0,64.0,64.0,62.6,62.6,62.6,63.3,62.7,63.1,62.4
118,Peru,61.1,62.10,63.1,63.5,64.0,65.9,64.7,65.4,65.4,65.8,66.5,64.9,66.0
119,Philippines,64.8,63.00,61.2,61.2,61.2,61.2,63.0,64.1,67.7,68.4,69.4,67.1,67.1
120,Poland,73.0,73.00,73.0,71.8,70.5,71.2,71.2,71.2,74.7,70.9,68.3,66.7,66.7
121,Portugal,81.6,81.00,80.5,80.3,80.2,78.1,79.2,76.5,77.9,77.9,78.6,78.4,78.4
122,Qatar,27.8,28.50,29.2,30.1,30.9,31.8,31.8,31.8,31.8,31.8,31.8,31.9,31.9
123,Romania,70.6,70.60,70.6,68.3,66.0,65.4,65.4,65.4,66.8,66.8,66.2,64.4,63.8
124,Russia,50.2,47.50,44.8,43.7,42.6,39.2,37.4,35.9,33.9,33.1,32.4,31.7,29.4
125,Rwanda,38.2,37.60,37.1,34.8,32.5,32.5,33.6,33.8,32.5,30.7,30.7,31.9,33.5
126,Saudi Arabia,19.2,19.10,19.0,18.7,18.4,17.7,17.1,18.2,18.2,19.3,19.3,19.3,19.3
127,Senegal,53.7,53.70,53.7,53.2,52.7,55.1,60.9,61.5,61.5,60.8,62.1,61.5,61.5
128,Serbia,66.2,65.50,64.9,64.1,63.3,63.3,63.3,66.7,67.1,67.1,65.7,64.1,64.1
129,Sierra Leone,35.7,38.40,41.1,43.1,45.1,45.1,47.1,46.4,45.6,45.5,45.5,46.6,46.6
130,Singapore,58.9,58.90,58.9,58.9,58.9,58.9,58.8,59.2,60.3,61.4,63.8,63.2,63.8
131,Slovak Republic,74.0,73.70,73.3,73.4,73.5,73.5,73.5,73.5,73.5,72.9,72.9,71.6,71.0
132,Slovenia,79.6,79.60,79.6,78.3,76.9,77.6,78.8,78.8,75.7,75.7,75.1,75.0,75.0
133,South Africa,79.1,79.10,79.1,78.5,77.9,77.9,77.9,79.0,78.2,75.6,74.1,72.4,72.4
134,South Korea,78.8,79.50,80.1,80.6,81.1,80.6,81.3,80.6,80.6,79.7,79.2,80.0,80.0
135,Spain,83.4,84.00,84.5,83.0,81.6,80.2,80.2,80.2,80.5,83.0,83.0,80.8,80.8
136,Sri Lanka,65.8,66.00,66.1,66.3,66.4,65.8,57.5,56.9,56.9,64.2,64.8,64.8,61.9
137,Sudan,29.0,28.60,28.1,26.1,24.2,23.8,23.8,25.4,25.4,23.7,23.7,21.5,21.5
138,Suriname,65.2,65.50,65.8,66.2,66.5,66.5,66.5,67.7,67.7,67.7,67.7,67.6,69.8
139,Swaziland,29.3,29.90,30.4,29.7,29.0,32.6,32.0,32.0,30.9,30.9,30.3,30.3,30.3
140,Sweden,98.8,98.80,98.8,96.9,95.0,95.0,97.3,97.3,97.3,94.5,93.9,93.9,93.9
141,Switzerland,90.2,90.80,91.5,91.2,90.9,90.9,90.9,90.9,90.9,90.9,90.9,90.3,90.3
142,Syria,23.6,22.70,21.8,22.4,23.1,19.9,16.3,18.6,17.4,14.3,14.3,14.3,14.3
143,Tajikistan,24.5,24.50,24.5,24.8,25.1,25.1,25.1,25.1,23.7,19.5,18.9,19.3,19.3
144,Tanzania,51.8,52.30,52.8,54.6,56.4,56.4,58.8,57.7,57.7,55.8,57.6,54.7,54.1
145,Thailand,56.7,62.40,68.1,66.8,65.5,65.5,65.5,62.5,53.9,50.9,49.2,46.3,46.3
146,Timor-Leste,64.1,68.20,72.2,72.2,72.2,72.2,71.6,72.4,72.4,72.4,72.4,71.9,71.9
147,Togo,17.5,20.90,24.3,29.4,34.5,34.5,34.5,34.5,34.5,34.1,33.2,30.5,31.0
148,Trinidad and Tobago,71.8,72.00,72.1,71.8,71.6,71.6,69.9,69.9,69.9,71.0,71.0,70.4,71.6
149,Tunisia,30.6,30.10,29.6,28.8,27.9,55.3,56.7,57.6,63.1,67.2,64.0,63.2,64.1
150,Turkey,57.0,57.00,56.9,57.1,57.3,57.3,57.6,56.3,51.2,51.2,50.4,48.8,43.7
151,Turkmenistan,18.3,17.80,17.2,17.2,17.2,17.2,17.2,17.2,18.3,18.3,18.3,17.2,17.2
152,Uganda,51.4,50.90,50.3,50.4,50.5,51.3,51.6,52.2,52.2,52.2,52.6,50.9,52.0
153,Ukraine,69.4,69.40,69.4,66.2,63.0,59.4,59.1,58.4,54.2,57.0,57.0,56.9,56.9
154,United Arab Emirates,24.2,25.10,26.0,25.6,25.2,25.8,25.8,25.2,26.4,27.5,27.5,26.9,27.6
155,United Kingdom,80.8,81.20,81.5,81.5,81.6,81.6,82.1,83.1,83.1,83.1,83.6,85.3,85.3
156,United States,82.2,82.20,82.2,82.0,81.8,81.1,81.1,81.1,81.1,80.5,79.8,79.8,79.6
157,Uruguay,79.6,80.20,80.8,80.9,81.0,81.7,81.7,81.7,81.7,81.7,81.7,81.2,83.8
158,Uzbekistan,18.5,17.90,17.4,17.4,17.4,17.4,17.2,17.2,24.5,19.5,19.5,19.5,20.1
159,Venezuela,54.2,53.80,53.4,52.6,51.8,50.8,51.5,50.7,50.7,50.0,46.8,38.7,31.6
160,Vietnam,27.5,26.40,25.3,27.4,29.4,29.6,28.9,32.9,34.1,35.3,33.8,30.8,30.8
161,Yemen,29.8,29.60,29.5,27.9,26.4,25.7,31.2,27.9,27.9,22.4,20.7,20.7,19.5
162,Zambia,52.5,52.50,52.5,54.6,56.8,61.9,62.6,62.6,63.9,62.8,59.9,56.8,56.1
163,Zimbabwe,26.2,25.80,25.3,25.9,26.4,26.8,26.7,26.7,27.8,30.5,30.5,31.6,31.6

In [197]:
demo_last_10 = demo.iloc[:, :-2]
demo_last_10

,country,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Afghanistan,30.6,30.40,30.2,27.5,24.8,24.8,24.8,24.8,27.7,27.7,25.5
1,Albania,59.1,59.10,59.1,58.9,58.6,58.1,56.7,56.7,56.7,59.1,59.1
2,Algeria,31.7,32.50,33.2,33.8,34.4,34.4,38.3,38.3,38.3,39.5,35.6
3,Angola,24.1,28.80,33.5,33.4,33.2,33.2,33.5,33.5,33.5,33.5,34.0
4,Argentina,66.3,66.30,66.3,67.3,68.4,68.4,68.4,68.4,68.4,70.2,69.6
5,Armenia,41.5,41.20,40.9,40.9,40.9,40.9,40.9,40.2,41.3,40.0,38.8
6,Australia,90.9,90.90,90.9,91.5,92.2,92.2,92.2,91.3,90.1,90.1,90.1
7,Austria,86.9,85.90,84.9,84.9,84.9,84.9,86.2,84.8,85.4,85.4,84.1
8,Azerbaijan,33.1,32.50,31.9,31.7,31.5,31.5,31.5,30.6,28.3,27.1,26.5
9,Bahrain,35.3,34.50,33.8,34.4,34.9,29.2,25.3,28.7,28.7,27.9,27.9
10,Bangladesh,61.1,58.10,55.2,57.0,58.7,58.6,58.6,58.6,57.8,57.3,57.3
11,Belarus,33.4,33.40,33.4,33.4,33.4,31.6,30.4,30.4,36.9,36.2,35.4
12,Belgium,81.5,81.50,81.6,81.0,80.5,80.5,80.5,80.5,79.3,79.3,77.7
13,Benin,61.6,61.10,60.6,61.1,61.7,60.6,60.0,58.7,56.5,57.2,56.7
14,Bhutan,26.2,34.60,43.0,44.9,46.8,45.7,46.5,48.2,48.7,49.3,49.3
15,Bolivia,59.8,60.60,61.5,60.4,59.2,58.4,58.4,57.9,57.9,57.5,56.3
16,Bosnia and Herzegovina,57.8,57.40,57.0,55.1,53.2,52.4,51.1,50.2,47.8,48.3,48.7
17,Botswana,76.0,75.30,74.7,75.5,76.3,76.3,78.5,79.8,78.7,78.7,78.7
18,Brazil,73.8,73.80,73.8,72.5,71.2,71.2,71.2,71.2,73.8,69.6,69.0
19,Bulgaria,71.0,70.60,70.2,69.3,68.4,67.8,67.2,68.3,67.3,71.4,70.1
20,Burkina Faso,37.2,36.60,36.0,36.0,35.9,35.9,35.2,41.5,40.9,47.0,47.0
21,Burundi,45.1,45.10,45.1,42.6,40.1,40.1,36.0,34.1,33.3,24.9,24.0
22,Cambodia,47.7,48.20,48.7,48.7,48.7,48.7,49.6,46.0,47.8,42.7,42.7
23,Cameroon,32.7,33.60,34.6,34.4,34.1,34.1,34.4,34.1,34.1,36.6,34.6
24,Canada,90.7,90.70,90.7,90.8,90.8,90.8,90.8,90.8,90.8,90.8,91.5
25,Cape Verde,74.3,76.20,78.1,78.8,79.4,79.2,79.2,79.2,78.1,78.1,79.4
26,Central African Republic,16.1,17.40,18.6,18.4,18.2,18.2,19.9,14.9,14.9,15.7,16.1
27,Chad,16.5,15.80,15.2,15.2,15.2,16.2,16.2,15.0,15.0,15.0,15.0
28,Chile,78.9,78.90,78.9,77.8,76.7,75.4,75.4,78.0,78.0,78.4,77.8
29,China,29.7,30.10,30.4,30.9,31.4,31.4,30.0,30.0,30.0,31.4,31.4
30,Colombia,64.0,64.70,65.4,65.5,65.5,66.3,66.3,65.5,65.5,66.2,66.7
31,Comoros,39.0,37.40,35.8,35.0,34.1,35.2,35.2,35.2,35.2,37.1,37.1
32,"Congo, Dem. Rep.",27.6,25.20,22.8,22.1,21.5,21.5,19.2,18.3,17.5,21.1,19.3
33,"Congo, Rep.",31.9,30.60,29.4,29.1,28.9,28.9,28.9,28.9,28.9,29.1,29.1
34,Costa Rica,80.4,80.40,80.4,80.4,80.4,81.0,81.0,80.3,80.3,79.6,78.8
35,Cote d'Ivoire,33.8,33.30,32.7,31.4,30.2,30.8,32.5,32.5,35.3,33.1,38.1
36,Croatia,70.4,70.40,70.4,69.3,68.1,67.3,69.3,69.3,69.3,69.3,67.5
37,Cuba,35.2,35.20,35.2,35.2,35.2,35.2,35.2,35.2,35.2,35.2,34.6
38,Cyprus,76.0,76.50,77.0,75.0,72.9,72.9,72.9,72.9,74.0,75.3,76.5
39,Czech Republic,81.7,81.80,81.9,81.9,81.9,81.9,81.9,80.6,79.4,79.4,78.2
40,Denmark,95.2,95.20,95.2,95.2,95.2,95.2,95.2,93.8,91.1,91.1,92.0
41,Djibouti,23.7,23.70,23.7,22.9,22.0,26.8,27.4,29.6,29.9,29.0,28.3
42,Dominican Republic,61.3,61.60,62.0,62.0,62.0,62.0,64.9,67.4,66.7,66.7,66.7
43,Ecuador,56.4,56.40,56.4,57.0,57.7,57.2,57.8,58.7,58.7,58.7,58.1
44,Egypt,39.0,39.00,38.9,34.8,30.7,39.5,45.6,32.7,31.6,31.8,33.1
45,El Salvador,62.2,63.10,64.0,64.3,64.7,64.7,64.7,65.3,65.3,66.4,66.4
46,Equatorial Guinea,20.9,21.40,21.9,20.1,18.4,17.7,18.3,17.7,16.6,17.7,17.0
47,Eritrea,23.1,23.10,23.1,23.1,23.1,23.4,24.0,24.0,24.4,23.7,23.7
48,Estonia,77.4,77.10,76.8,76.8,76.8,76.1,76.1,76.1,77.4,78.5,78.5
49,Ethiopia,47.2,46.20,45.2,41.0,36.8,37.9,37.2,38.3,37.2,38.3,36.0
50,Fiji,56.6,53.90,51.1,43.6,36.2,36.7,36.7,36.1,56.1,56.9,56.4
51,Finland,92.5,92.50,92.5,92.2,91.9,90.6,90.6,90.3,90.3,90.3,90.3
52,France,80.7,80.70,80.7,79.2,77.7,77.7,78.8,79.2,80.4,79.2,79.2
53,Gabon,27.2,28.60,30.0,31.4,32.9,34.8,35.6,37.6,37.6,37.6,37.4
54,Gambia,43.9,42.90,41.9,37.9,33.8,33.8,33.1,33.1,30.5,29.7,29.1
55,Germany,88.2,88.20,88.2,86.0,83.8,83.4,83.4,83.1,86.4,86.4,86.3
56,Ghana,53.5,53.50,53.5,56.9,60.2,60.2,60.2,63.3,63.3,68.6,67.5
57,Greece,81.3,81.30,81.3,80.3,79.2,76.5,76.5,76.5,74.5,74.5,72.3
58,Guatemala,60.7,60.70,60.7,60.6,60.5,58.8,58.8,58.1,58.1,59.2,59.2
59,Guinea,20.2,20.60,20.9,24.4,27.9,27.9,27.9,28.4,30.1,31.4,31.4
60,Guinea-Bissau,20.0,19.90,19.9,19.9,19.9,19.9,14.3,12.6,19.3,19.3,19.8
61,Guyana,61.5,61.40,61.2,60.9,60.5,60.5,60.5,60.5,59.1,60.5,62.5
62,Haiti,41.9,41.90,41.9,41.0,40.0,40.0,39.6,39.4,38.2,39.4,40.2
63,Honduras,62.5,62.10,61.8,59.7,57.6,58.4,58.4,58.4,58.4,58.4,59.2
64,Hungary,75.3,74.80,74.4,73.3,72.1,70.4,69.6,69.6,69.0,68.4,67.2
65,Iceland,97.1,96.80,96.5,96.5,96.5,96.5,96.5,96.5,95.8,95.8,95.0
66,India,76.8,77.40,78.0,75.4,72.8,73.0,75.2,76.9,79.2,77.4,78.1
67,Indonesia,64.1,63.80,63.4,64.3,65.3,65.3,67.6,68.2,69.5,70.3,69.7
68,Iran,29.3,28.80,28.3,23.9,19.4,19.8,19.8,19.8,19.8,21.6,23.4
69,Iraq,40.1,40.00,40.0,40.0,40.0,40.3,41.0,41.0,42.3,40.8,40.8
70,Ireland,90.1,90.10,90.1,89.0,87.9,85.6,85.6,86.8,87.2,88.5,91.5
71,Israel,72.8,73.80,74.8,74.8,74.8,75.3,75.3,75.3,76.3,77.7,78.5
72,Italy,77.3,78.50,79.8,79.0,78.3,77.4,77.4,78.5,78.5,79.8,79.8
73,Jamaica,73.4,72.80,72.1,72.1,72.1,71.3,73.9,73.9,73.9,73.9,73.9
74,Japan,81.5,82.00,82.5,81.7,80.8,80.8,80.8,80.8,80.8,79.6,79.9
75,Jordan,39.2,39.30,39.3,38.4,37.4,38.9,37.6,37.6,37.6,38.6,39.6
76,Kazakhstan,36.2,35.40,34.5,33.8,33.0,32.4,29.5,30.6,31.7,30.6,30.6
77,Kenya,50.8,49.40,47.9,47.5,47.1,47.1,47.1,51.3,51.3,53.3,53.3
78,Kuwait,30.9,32.40,33.9,36.4,38.8,37.4,37.8,37.8,37.8,38.5,38.5
79,Kyrgyz Republic,40.8,40.60,40.5,41.8,43.1,43.4,46.9,46.9,52.4,53.3,49.3
80,Lao,21.0,21.00,21.0,21.0,21.0,21.0,23.2,22.1,22.1,22.1,23.7
81,Latvia,73.7,73.00,72.3,71.4,70.5,70.5,70.5,70.5,74.8,73.7,73.1
82,Lebanon,58.2,57.20,56.2,57.2,58.2,53.2,50.5,50.5,51.2,48.6,48.6
83,Lesotho,64.8,63.90,62.9,61.5,60.2,63.3,66.6,66.6,66.6,65.9,65.9
84,Liberia,52.2,52.40,52.5,51.6,50.7,50.7,49.5,49.5,49.5,49.5,53.1
85,Libya,18.4,19.20,20.0,19.7,19.4,35.5,51.5,48.2,38.0,22.5,22.5
86,Lithuania,74.3,74.00,73.6,73.0,72.4,72.4,72.4,75.4,75.4,75.4,74.7
87,Luxembourg,91.0,91.00,91.0,89.9,88.8,88.8,88.8,88.8,88.8,88.8,88.1
88,Madagascar,58.2,57.00,55.7,47.5,39.4,39.3,39.3,43.2,44.2,48.5,50.7
89,Malawi,49.7,50.50,51.3,54.9,58.4,58.4,60.8,60.0,56.6,55.5,55.5
90,Malaysia,59.8,61.70,63.6,62.8,61.9,61.9,64.1,64.9,64.9,64.3,65.4
91,Mali,59.9,59.30,58.7,59.4,60.1,63.6,51.2,59.0,57.9,57.0,57.0
92,Malta,83.9,83.90,83.9,83.3,82.8,82.8,82.8,82.8,83.9,83.9,83.9
93,Mauritania,31.2,35.10,39.1,38.9,38.6,41.7,41.7,41.7,41.7,39.6,39.6
94,Mauritius,80.4,80.40,80.4,80.4,80.4,80.4,81.7,81.7,81.7,82.8,82.8
95,Mexico,66.7,67.30,67.8,68.5,69.3,69.3,69.0,69.1,66.8,65.5,64.7
96,Moldova,65.0,65.00,65.0,64.2,63.3,63.3,63.2,63.2,63.2,63.5,60.1
97,Mongolia,66.0,66.00,66.0,64.8,63.6,62.3,63.5,65.1,66.2,66.2,66.2
98,Montenegro,65.7,65.00,64.3,63.5,62.7,61.5,60.5,59.4,59.4,60.1,57.2
99,Morocco,39.0,38.90,38.8,38.4,37.9,38.3,40.7,40.7,40.0,46.6,47.7
100,Mozambique,52.8,53.90,54.9,52.0,49.0,49.0,48.8,47.7,46.6,46.0,40.2
101,Myanmar,17.7,17.70,17.7,17.7,17.7,17.7,23.5,27.6,30.5,41.4,42.0
102,Namibia,65.4,65.10,64.8,63.5,62.3,62.4,62.4,62.4,62.4,63.1,63.1
103,Nepal,34.2,37.40,40.5,41.5,42.4,42.4,41.6,47.7,47.7,47.7,48.6
104,Netherlands,96.6,96.00,95.3,92.6,89.9,89.9,89.9,88.4,89.2,89.2,88.0
105,New Zealand,90.1,91.00,91.9,92.3,92.6,92.6,92.6,92.6,92.6,92.6,92.6
106,Nicaragua,56.8,58.80,60.7,59.0,57.3,55.6,55.6,54.6,53.2,52.6,48.1
107,Niger,35.4,34.80,34.1,34.0,33.8,41.6,41.6,40.8,40.2,38.5,39.6
108,Nigeria,35.2,35.30,35.3,35.0,34.7,38.3,37.7,37.7,37.6,46.2,45.0
109,North Korea,10.3,9.45,8.6,9.7,10.8,10.8,10.8,10.8,10.8,10.8,10.8
110,North Macedonia,63.3,62.70,62.1,61.9,61.6,61.6,61.6,61.6,62.5,60.2,52.3
111,Norway,95.5,96.20,96.8,97.4,98.0,98.0,99.3,99.3,99.3,99.3,99.3
112,Oman,27.7,28.80,29.8,29.2,28.6,32.6,32.6,32.6,31.5,30.4,30.4
113,Pakistan,39.2,41.90,44.6,45.0,45.5,45.5,45.7,46.4,46.4,44.0,43.3
114,Palestine,60.1,59.20,58.3,56.4,54.4,49.7,48.0,48.0,47.2,45.7,44.9
115,Panama,73.5,73.50,73.5,72.5,71.5,70.8,70.8,70.8,70.8,71.9,71.3
116,Papua New Guinea,65.4,65.40,65.4,65.4,65.4,63.2,63.2,63.6,60.3,60.3,60.3
117,Paraguay,61.6,62.80,64.0,64.0,64.0,64.0,62.6,62.6,62.6,63.3,62.7
118,Peru,61.1,62.10,63.1,63.5,64.0,65.9,64.7,65.4,65.4,65.8,66.5
119,Philippines,64.8,63.00,61.2,61.2,61.2,61.2,63.0,64.1,67.7,68.4,69.4
120,Poland,73.0,73.00,73.0,71.8,70.5,71.2,71.2,71.2,74.7,70.9,68.3
121,Portugal,81.6,81.00,80.5,80.3,80.2,78.1,79.2,76.5,77.9,77.9,78.6
122,Qatar,27.8,28.50,29.2,30.1,30.9,31.8,31.8,31.8,31.8,31.8,31.8
123,Romania,70.6,70.60,70.6,68.3,66.0,65.4,65.4,65.4,66.8,66.8,66.2
124,Russia,50.2,47.50,44.8,43.7,42.6,39.2,37.4,35.9,33.9,33.1,32.4
125,Rwanda,38.2,37.60,37.1,34.8,32.5,32.5,33.6,33.8,32.5,30.7,30.7
126,Saudi Arabia,19.2,19.10,19.0,18.7,18.4,17.7,17.1,18.2,18.2,19.3,19.3
127,Senegal,53.7,53.70,53.7,53.2,52.7,55.1,60.9,61.5,61.5,60.8,62.1
128,Serbia,66.2,65.50,64.9,64.1,63.3,63.3,63.3,66.7,67.1,67.1,65.7
129,Sierra Leone,35.7,38.40,41.1,43.1,45.1,45.1,47.1,46.4,45.6,45.5,45.5
130,Singapore,58.9,58.90,58.9,58.9,58.9,58.9,58.8,59.2,60.3,61.4,63.8
131,Slovak Republic,74.0,73.70,73.3,73.4,73.5,73.5,73.5,73.5,73.5,72.9,72.9
132,Slovenia,79.6,79.60,79.6,78.3,76.9,77.6,78.8,78.8,75.7,75.7,75.1
133,South Africa,79.1,79.10,79.1,78.5,77.9,77.9,77.9,79.0,78.2,75.6,74.1
134,South Korea,78.8,79.50,80.1,80.6,81.1,80.6,81.3,80.6,80.6,79.7,79.2
135,Spain,83.4,84.00,84.5,83.0,81.6,80.2,80.2,80.2,80.5,83.0,83.0
136,Sri Lanka,65.8,66.00,66.1,66.3,66.4,65.8,57.5,56.9,56.9,64.2,64.8
137,Sudan,29.0,28.60,28.1,26.1,24.2,23.8,23.8,25.4,25.4,23.7,23.7
138,Suriname,65.2,65.50,65.8,66.2,66.5,66.5,66.5,67.7,67.7,67.7,67.7
139,Swaziland,29.3,29.90,30.4,29.7,29.0,32.6,32.0,32.0,30.9,30.9,30.3
140,Sweden,98.8,98.80,98.8,96.9,95.0,95.0,97.3,97.3,97.3,94.5,93.9
141,Switzerland,90.2,90.80,91.5,91.2,90.9,90.9,90.9,90.9,90.9,90.9,90.9
142,Syria,23.6,22.70,21.8,22.4,23.1,19.9,16.3,18.6,17.4,14.3,14.3
143,Tajikistan,24.5,24.50,24.5,24.8,25.1,25.1,25.1,25.1,23.7,19.5,18.9
144,Tanzania,51.8,52.30,52.8,54.6,56.4,56.4,58.8,57.7,57.7,55.8,57.6
145,Thailand,56.7,62.40,68.1,66.8,65.5,65.5,65.5,62.5,53.9,50.9,49.2
146,Timor-Leste,64.1,68.20,72.2,72.2,72.2,72.2,71.6,72.4,72.4,72.4,72.4
147,Togo,17.5,20.90,24.3,29.4,34.5,34.5,34.5,34.5,34.5,34.1,33.2
148,Trinidad and Tobago,71.8,72.00,72.1,71.8,71.6,71.6,69.9,69.9,69.9,71.0,71.0
149,Tunisia,30.6,30.10,29.6,28.8,27.9,55.3,56.7,57.6,63.1,67.2,64.0
150,Turkey,57.0,57.00,56.9,57.1,57.3,57.3,57.6,56.3,51.2,51.2,50.4
151,Turkmenistan,18.3,17.80,17.2,17.2,17.2,17.2,17.2,17.2,18.3,18.3,18.3
152,Uganda,51.4,50.90,50.3,50.4,50.5,51.3,51.6,52.2,52.2,52.2,52.6
153,Ukraine,69.4,69.40,69.4,66.2,63.0,59.4,59.1,58.4,54.2,57.0,57.0
154,United Arab Emirates,24.2,25.10,26.0,25.6,25.2,25.8,25.8,25.2,26.4,27.5,27.5
155,United Kingdom,80.8,81.20,81.5,81.5,81.6,81.6,82.1,83.1,83.1,83.1,83.6
156,United States,82.2,82.20,82.2,82.0,81.8,81.1,81.1,81.1,81.1,80.5,79.8
157,Uruguay,79.6,80.20,80.8,80.9,81.0,81.7,81.7,81.7,81.7,81.7,81.7
158,Uzbekistan,18.5,17.90,17.4,17.4,17.4,17.4,17.2,17.2,24.5,19.5,19.5
159,Venezuela,54.2,53.80,53.4,52.6,51.8,50.8,51.5,50.7,50.7,50.0,46.8
160,Vietnam,27.5,26.40,25.3,27.4,29.4,29.6,28.9,32.9,34.1,35.3,33.8
161,Yemen,29.8,29.60,29.5,27.9,26.4,25.7,31.2,27.9,27.9,22.4,20.7
162,Zambia,52.5,52.50,52.5,54.6,56.8,61.9,62.6,62.6,63.9,62.8,59.9
163,Zimbabwe,26.2,25.80,25.3,25.9,26.4,26.8,26.7,26.7,27.8,30.5,30.5

In [201]:
demo_last_10 = demo_last_10.melt(id_vars=['country'], var_name='year', value_name='demox_eiu')
demo_last_10

          country  year  demox_eiu
0     Afghanistan  2006       30.6
1         Albania  2006       59.1
2         Algeria  2006       31.7
3          Angola  2006       24.1
4       Argentina  2006       66.3
...           ...   ...        ...
1799    Venezuela  2016       46.8
1800      Vietnam  2016       33.8
1801        Yemen  2016       20.7
1802       Zambia  2016       59.9
1803     Zimbabwe  2016       30.5

[1804 rows x 3 columns]

In [202]:
demo_last_10.sort_values(['country','year'], inplace=True)
demo_last_10

          country  year  demox_eiu
0     Afghanistan  2006       30.6
164   Afghanistan  2007       30.4
328   Afghanistan  2008       30.2
492   Afghanistan  2009       27.5
656   Afghanistan  2010       24.8
...           ...   ...        ...
1147     Zimbabwe  2012       26.7
1311     Zimbabwe  2013       26.7
1475     Zimbabwe  2014       27.8
1639     Zimbabwe  2015       30.5
1803     Zimbabwe  2016       30.5

[1804 rows x 3 columns]

In [203]:
demo_last_10.to_csv('demox_eiu_last_10.csv', index=False)

In [205]:
invest_last_30 = invest.iloc[:, np.r_[:1, 49:58]]
invest_last_30.head(100)

,country,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Afghanistan,18.9,17.90,17.9,16.60,16.80,17.20,18.10,19.40,17.70
1,Albania,35.8,34.60,30.3,31.40,28.30,28.40,24.60,24.40,24.80
2,Algeria,37.3,46.90,41.4,38.10,39.20,43.40,45.60,50.70,50.70
3,Angola,16.2,15.20,14.4,12.90,15.10,14.70,15.30,9.55,8.40
4,Argentina,19.6,16.10,17.7,18.40,16.50,17.30,17.30,17.10,17.00
5,Armenia,40.9,34.70,32.9,27.30,25.30,22.30,20.90,20.70,18.00
6,Australia,28.6,27.30,26.8,26.40,27.60,27.80,26.70,26.10,25.30
7,Austria,24.5,22.80,22.6,24.10,24.00,23.70,23.50,23.60,24.10
8,Azerbaijan,18.7,18.90,18.1,20.30,21.70,24.50,25.70,27.90,24.90
9,Bahamas,29.4,28.00,28.0,30.10,31.30,28.70,32.20,24.70,24.70
10,Bahrain,35.2,26.10,27.3,22.40,28.10,25.90,26.80,26.50,29.60
11,Bangladesh,26.2,26.20,26.2,27.40,28.30,28.40,28.60,28.90,29.70
12,Barbados,19.1,17.10,16.0,17.00,15.90,16.70,16.70,17.30,17.10
13,Belarus,37.6,37.30,40.7,37.20,35.10,38.80,34.80,29.00,26.50
14,Belgium,25.7,21.70,22.7,24.00,23.20,22.20,23.30,23.60,24.00
15,Belize,25.6,19.10,13.2,17.00,16.00,18.30,21.30,22.50,22.10
16,Benin,20.4,21.90,23.1,24.10,22.60,27.80,28.60,26.00,24.60
17,Bhutan,42.9,45.70,61.7,67.70,67.90,46.00,51.70,54.00,55.60
18,Bolivia,17.6,17.00,17.0,19.80,17.70,19.00,21.00,20.30,21.10
19,Bosnia and Herzegovina,27.1,19.80,16.3,18.70,19.20,18.20,19.10,18.70,19.60
20,Botswana,36.2,38.90,41.4,37.80,38.10,29.40,27.90,32.10,24.30
21,Brazil,21.6,18.80,21.8,21.80,21.40,21.70,20.50,17.40,15.40
22,Brunei,13.7,17.60,23.7,26.00,32.90,39.60,27.40,35.20,34.60
23,Bulgaria,37.0,28.60,22.6,21.50,21.90,21.30,21.40,21.20,19.10
24,Burkina Faso,25.4,24.90,26.9,28.00,32.50,32.50,25.90,24.30,23.20
25,Burundi,26.7,23.20,30.5,27.60,28.40,28.70,27.80,16.60,16.90
26,Cambodia,18.6,21.40,17.4,17.10,18.50,20.00,22.10,22.50,22.70
27,Cameroon,24.1,23.70,23.2,24.10,22.80,23.10,24.10,22.40,22.20
28,Canada,24.1,22.00,23.5,24.20,24.90,25.00,24.90,24.10,23.20
29,Cape Verde,48.5,43.80,47.6,47.50,37.20,31.60,37.00,30.20,36.10
30,Central African Republic,12.7,13.20,14.3,15.00,14.80,8.69,10.20,13.90,13.60
31,Chad,21.9,30.20,34.5,28.50,31.10,29.30,33.80,28.40,26.20
32,Chile,26.8,21.10,23.1,24.60,26.40,25.60,23.20,23.80,22.20
33,China,43.3,46.40,47.6,47.70,47.20,47.40,47.00,45.40,44.30
34,Colombia,23.5,22.40,22.1,23.90,23.90,24.30,26.30,26.70,24.70
35,Comoros,19.8,16.80,14.7,15.60,17.70,21.80,27.40,18.40,20.90
36,"Congo, Dem. Rep.",10.9,14.60,28.8,24.90,14.30,21.80,23.20,19.60,17.40
37,"Congo, Rep.",18.3,22.50,20.5,25.30,26.00,30.90,41.30,40.90,50.40
38,Costa Rica,24.9,18.40,19.7,19.90,20.50,19.00,18.80,18.40,17.90
39,Cote d'Ivoire,12.1,8.70,13.4,4.70,15.10,20.70,19.80,20.10,20.70
40,Croatia,31.4,25.00,21.4,20.60,19.20,19.30,18.80,20.00,20.20
41,Cuba,14.8,10.90,10.1,8.47,8.58,9.39,7.61,9.37,NaN
42,Cyprus,28.9,22.90,23.8,18.80,16.10,13.20,12.30,14.20,16.80
43,Czech Republic,31.1,26.50,27.1,27.00,26.20,24.70,25.90,28.00,26.30
44,Denmark,24.0,19.10,18.1,19.10,19.50,19.70,20.10,20.00,21.00
45,Djibouti,NaN,NaN,NaN,NaN,NaN,29.80,33.80,44.70,28.80
46,Dominican Republic,30.0,23.60,26.4,25.00,24.30,22.70,23.00,22.60,21.90
47,Ecuador,26.4,25.60,28.0,28.10,27.80,28.50,28.30,26.90,25.20
48,Egypt,22.4,19.20,19.5,17.10,16.00,14.20,13.60,14.30,15.00
49,El Salvador,20.2,14.10,16.7,17.80,17.80,17.20,16.40,15.60,15.10
50,Equatorial Guinea,27.5,39.40,38.1,32.00,41.10,30.30,28.70,24.70,16.60
51,Eritrea,12.7,9.26,9.3,10.00,NaN,NaN,NaN,NaN,NaN
52,Estonia,30.7,20.70,21.3,25.10,29.10,26.90,27.10,24.90,24.20
53,Ethiopia,0.0,0.00,0.0,32.10,37.10,34.10,38.00,40.70,38.00
54,Fiji,24.9,NaN,NaN,21.00,17.30,27.60,19.00,17.90,20.00
55,Finland,25.1,21.20,21.6,23.50,22.50,21.40,20.90,20.90,21.90
56,France,24.1,21.30,21.9,23.20,22.60,22.30,22.70,22.70,22.70
57,Gabon,25.1,28.00,29.7,26.60,27.00,29.20,35.10,29.20,27.90
58,Gambia,15.9,19.60,21.3,18.90,27.80,20.00,20.90,19.70,18.70
59,Georgia,26.0,13.00,21.6,26.20,28.90,24.80,29.80,31.50,32.70
60,Germany,20.9,18.10,19.6,21.10,19.30,19.50,19.50,19.10,19.20
61,Ghana,16.5,16.40,13.1,12.80,17.00,13.30,18.80,16.70,14.50
62,Greece,24.5,18.30,17.0,15.10,12.80,11.60,11.90,9.82,10.60
63,Guatemala,16.4,13.10,13.9,15.20,15.00,14.00,13.70,13.60,12.90
64,Guinea,26.2,21.30,20.3,24.10,26.00,23.50,23.40,23.50,51.80
65,Guinea-Bissau,12.8,10.80,10.8,9.93,6.70,7.22,11.40,8.09,7.82
66,Guyana,23.9,26.20,25.2,23.90,24.80,18.60,28.70,32.30,29.60
67,Haiti,28.8,27.50,25.4,27.90,35.60,36.70,38.20,41.10,38.70
68,Honduras,36.1,20.60,21.9,26.00,24.60,21.80,22.20,25.10,23.30
69,Hungary,24.7,20.30,20.7,20.50,19.50,21.00,23.30,21.80,19.80
70,Iceland,25.8,14.80,13.8,15.40,16.00,15.40,17.30,19.10,21.50
71,India,38.2,40.70,40.7,39.60,38.30,34.00,34.30,31.80,30.30
72,Indonesia,27.8,31.00,32.9,33.00,35.10,33.80,34.60,34.10,33.80
73,Iran,41.8,40.90,40.3,36.90,40.30,38.70,39.90,34.00,33.20
74,Iraq,15.2,11.30,15.9,15.50,13.40,26.90,25.70,24.40,20.60
75,Ireland,24.6,20.20,17.3,17.20,20.20,18.80,22.40,21.20,32.70
76,Israel,20.0,18.30,18.4,20.40,21.20,20.00,20.20,19.80,20.50
77,Italy,21.8,19.40,20.5,20.50,17.90,17.00,17.00,17.30,17.10
78,Jamaica,24.4,21.10,20.2,21.40,19.90,21.30,22.50,21.30,21.30
79,Japan,24.5,21.30,21.3,22.10,22.70,23.20,23.90,24.00,23.60
80,Jordan,29.9,26.30,24.0,25.50,26.90,28.10,28.00,24.10,22.20
81,Kazakhstan,27.5,29.40,25.4,23.00,25.20,24.60,25.80,27.90,27.80
82,Kenya,19.6,19.30,20.8,21.70,21.50,20.10,22.40,21.50,17.30
83,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Kuwait,17.6,18.00,17.7,13.50,12.80,14.40,16.30,25.40,27.00
85,Kyrgyz Republic,28.9,27.30,27.4,25.50,35.00,33.90,36.80,34.70,33.90
86,Lao,31.7,33.90,27.5,28.10,32.50,30.60,29.80,31.60,29.00
87,Latvia,35.1,22.00,19.3,25.20,26.20,24.30,22.70,22.20,19.60
88,Lebanon,28.2,27.10,25.2,26.80,24.30,27.70,24.20,21.40,24.80
89,Lesotho,25.7,27.70,28.4,22.70,32.00,29.70,31.40,28.80,28.30
90,Liberia,19.5,19.50,19.5,19.50,19.50,19.50,19.50,20.20,20.10
91,Libya,29.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,Lithuania,27.9,12.40,18.0,21.70,19.40,19.50,19.00,20.60,17.20
93,Luxembourg,20.7,16.20,17.9,19.40,19.40,19.00,18.80,18.10,17.90
94,Madagascar,40.3,34.80,20.8,17.60,17.60,15.90,15.60,13.10,14.80
95,Malawi,23.2,24.50,22.8,12.40,12.00,12.70,12.00,12.20,10.80
96,Malaysia,21.5,17.80,23.4,23.20,25.70,25.90,25.00,25.10,25.90
97,Mali,24.2,22.00,24.0,19.70,17.20,17.80,17.60,17.40,17.40
98,Malta,21.7,20.80,23.6,19.40,18.00,19.00,17.70,23.90,23.10
99,Marshall Islands,14.4,32.10,36.7,21.70,4.35,20.90,17.20,16.00,NaN

In [251]:
tax = pd.read_csv('tax_revenue_percent_of_gdp.csv')
tax

,country,1972,1973,1974,1975,1976,1977,1978,1979,1980,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.040,8.440,9.120,8.850,7.470,7.080,6.840,7.5500,NaN,NaN
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.000,17.500,16.500,18.300,18.5000,17.6000,NaN
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.300,35.100,34.400,37.200,NaN,NaN,NaN,NaN,NaN,NaN
3,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.000,17.100,16.900,17.300,16.700,15.500,15.600,12.5000,10.3000,NaN
4,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.700,17.300,18.500,17.900,18.500,17.200,16.500,NaN,NaN,NaN
5,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.300,12.400,12.900,12.700,13.000,12.500,12.600,12.3000,12.2000,NaN
6,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.300,16.500,17.100,17.200,17.500,NaN,21.600,20.9000,21.3000,NaN
7,Australia,17.90,17.00,18.10,19.90,20.30,20.60,20.40,19.80,20.40,...,24.300,22.100,20.600,20.400,21.200,22.100,22.000,22.0000,22.3000,NaN
8,Austria,17.90,18.20,18.40,18.00,17.90,18.00,18.80,18.60,18.60,...,26.100,25.200,25.300,25.400,25.900,26.400,26.400,26.8000,25.7000,NaN
9,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.400,14.100,12.200,12.200,12.800,13.400,14.200,15.6000,NaN,NaN
10,Bahamas,NaN,14.50,16.70,16.30,17.20,15.90,16.30,15.30,15.00,...,12.100,11.300,10.900,12.900,11.900,11.400,11.400,12.7000,14.2000,NaN
11,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.240,1.360,1.180,1.110,NaN,1.070,NaN,NaN,NaN,NaN
12,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.660,7.500,7.830,8.690,9.020,8.960,8.640,8.5000,8.7700,NaN
13,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.400,24.900,25.100,25.900,24.200,23.400,24.000,26.1000,NaN,NaN
14,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.400,19.300,16.300,14.500,14.700,13.400,12.700,14.2000,13.8000,NaN
15,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.100,23.600,24.300,24.700,25.700,26.200,26.300,24.7000,23.1000,NaN
16,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.700,22.500,23.600,22.600,22.500,23.300,23.400,NaN,NaN,NaN
17,Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.100,15.000,15.500,14.800,14.400,15.400,NaN,NaN,NaN,NaN
18,Bhutan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.420,9.240,13.100,13.500,14.700,14.400,13.300,13.8000,13.2000,NaN
19,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.300,18.900,19.700,20.300,20.500,19.800,19.800,19.9000,20.0000,NaN
21,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.400,27.300,23.600,23.200,26.600,25.600,25.800,24.7000,20.8000,NaN
22,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.10,...,15.500,14.400,13.600,14.200,13.700,13.400,12.800,12.8000,12.9000,NaN
23,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.200,19.000,18.500,17.700,19.000,19.800,19.600,20.2000,20.0000,NaN
24,Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.900,12.500,12.700,13.700,15.600,16.800,15.400,15.1000,15.8000,NaN
25,Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13.900,14.700,13.700,12.200,NaN,NaN,NaN,NaN
26,Cambodia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.600,9.650,10.000,10.200,11.100,12.100,14.600,14.2000,15.3000,NaN
27,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.400,12.300,11.800,11.800,11.700,11.700,11.800,12.3000,12.2000,12.20
28,Cape Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.300,18.400,NaN,NaN,17.900,NaN,NaN,NaN,NaN,NaN
29,Central African Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.060,9.170,10.100,9.290,NaN,NaN,NaN,NaN,NaN,NaN
30,Chile,16.20,17.40,16.30,20.60,18.40,18.80,18.70,17.90,19.00,...,18.700,14.500,17.400,18.900,19.000,17.400,17.000,17.4000,17.4000,NaN
31,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.100,10.300,10.200,10.300,10.200,9.870,9.670,9.3700,NaN,NaN
32,Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.900,12.600,12.100,14.600,13.300,14.100,15.000,15.1000,13.3000,NaN
33,"Congo, Dem. Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.970,7.890,8.350,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"Congo, Rep.",16.80,15.50,25.00,20.40,NaN,NaN,NaN,NaN,25.40,...,5.950,8.400,7.600,8.860,9.430,NaN,NaN,NaN,NaN,NaN
35,Costa Rica,11.40,12.50,13.60,12.40,12.20,12.30,12.70,11.90,11.60,...,15.300,13.300,13.100,13.400,13.300,13.700,13.400,13.7000,14.0000,NaN
36,Cote d'Ivoire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.100,14.600,14.300,10.900,14.300,14.500,14.000,15.4000,15.2000,NaN
37,Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000,19.200,19.100,18.400,19.500,19.000,19.100,NaN,NaN,NaN
38,Cyprus,NaN,NaN,NaN,13.40,12.10,13.20,13.60,14.20,14.80,...,46.100,23.300,23.200,23.300,23.300,23.400,24.500,24.1000,24.3000,NaN
39,Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.400,13.400,13.400,14.300,14.700,14.900,14.200,14.6000,14.7000,NaN
40,Denmark,29.00,28.90,29.10,26.70,26.50,27.10,28.10,28.60,28.50,...,33.400,33.200,32.700,32.800,33.400,33.800,36.500,33.9000,33.7000,NaN
41,Dominica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.800,24.300,24.600,23.100,23.000,22.400,22.100,NaN,NaN,NaN
42,Dominican Republic,13.90,13.40,14.40,16.10,13.30,12.50,11.30,11.00,10.50,...,14.200,12.600,12.200,12.300,13.000,13.500,13.600,13.3000,13.5000,NaN
43,Egypt,NaN,NaN,NaN,20.90,17.30,25.10,23.00,21.10,NaN,...,15.300,15.700,14.100,14.000,12.400,13.500,12.200,12.5000,NaN,NaN
44,El Salvador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.100,15.000,15.800,15.300,16.200,17.100,16.700,16.9000,17.6000,NaN
45,Equatorial Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.790,12.800,7.590,7.020,8.740,8.520,8.300,11.5000,NaN,NaN
46,Estonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.240,1.370,1.270,1.230,1.270,1.290,1.340,1.4000,1.4300,NaN
47,Ethiopia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.810,6.580,8.160,9.210,9.380,8.760,NaN,NaN,NaN,NaN
48,Fiji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,21.800,23.000,23.200,23.600,24.600,25.5000,NaN,NaN
49,Finland,21.70,22.00,21.30,22.10,24.70,24.20,22.40,21.20,21.40,...,20.500,19.000,18.700,20.100,20.300,20.700,20.800,20.7000,21.0000,NaN
50,France,18.70,17.80,18.90,17.70,18.80,18.20,18.30,18.80,19.30,...,22.000,20.700,22.000,21.800,22.600,23.200,23.200,23.2000,23.1000,NaN
51,Gambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.700,15.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.800,23.100,22.100,23.800,24.100,23.400,23.500,23.8000,23.5000,NaN
53,Germany,10.80,11.00,10.50,10.10,10.20,10.50,10.50,10.40,10.30,...,11.400,11.600,11.100,11.400,11.600,11.600,11.500,11.4000,11.2000,NaN
54,Ghana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Greece,12.90,12.50,12.60,12.70,14.10,14.00,14.30,13.90,13.80,...,20.200,19.800,20.200,22.100,23.600,23.700,24.400,24.9000,26.7000,NaN
56,Grenada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.500,18.200,18.700,19.200,18.700,18.400,19.400,NaN,NaN,NaN
57,Guatemala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.300,10.300,10.400,10.800,10.800,10.900,10.800,10.2000,10.4000,NaN
58,Honduras,10.70,10.80,11.10,11.10,11.70,13.10,12.70,12.80,13.60,...,16.100,14.200,14.400,14.800,14.700,15.100,16.500,17.3000,NaN,NaN
59,Hungary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.300,23.300,22.800,21.100,22.900,22.700,23.000,23.4000,23.4000,NaN
60,Iceland,23.20,23.20,24.10,23.20,22.10,21.10,21.50,22.20,21.50,...,23.200,20.100,20.700,21.200,22.100,22.700,25.300,23.5000,38.5000,NaN
61,India,NaN,NaN,8.29,9.15,9.31,8.71,9.43,9.82,9.15,...,11.100,9.940,10.500,10.200,10.800,11.000,NaN,NaN,NaN,NaN
62,Indonesia,12.40,13.80,16.00,16.60,17.90,17.70,17.90,20.30,21.80,...,13.300,11.100,10.500,11.200,11.400,11.300,10.800,10.8000,10.3000,NaN
63,Iran,8.27,7.55,5.42,8.19,7.56,8.22,8.87,5.99,5.17,...,6.200,7.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.890,1.2300,2.0200,NaN
65,Ireland,21.80,22.10,22.00,21.30,23.60,22.50,22.10,21.90,24.20,...,23.700,22.000,21.800,21.800,22.500,22.800,23.200,18.9000,18.8000,NaN
66,Israel,25.70,24.30,30.60,30.40,33.80,35.10,33.20,37.80,35.90,...,23.800,21.900,22.500,22.700,22.100,23.000,23.300,23.4000,23.4000,NaN
67,Italy,NaN,12.60,13.50,12.80,14.10,15.00,15.70,15.80,17.40,...,21.900,22.400,22.300,22.300,23.600,23.700,23.500,23.4000,23.7000,NaN
68,Jamaica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.700,25.000,24.300,23.400,24.300,24.000,24.100,24.8000,26.1000,NaN
69,Japan,10.50,11.70,11.30,9.35,9.13,9.16,9.25,9.95,10.50,...,8.930,8.370,8.810,9.360,9.680,10.400,11.500,11.4000,11.1000,NaN
70,Jordan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.800,17.000,16.000,15.000,15.300,15.300,NaN,NaN,NaN,NaN
71,Kazakhstan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,15.700,18.300,13.300,16.000,14.200,9.8400,9.9200,NaN
72,Kenya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,16.900,16.3000,15.8000,NaN
73,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16.000,18.100,18.500,17.800,17.800,22.3000,24.5000,NaN
74,Kuwait,37.40,37.20,32.70,NaN,NaN,4.62,7.60,2.18,2.70,...,0.876,0.971,0.979,0.800,0.716,0.777,0.890,1.3800,NaN,NaN
75,Kyrgyz Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,17.600,17.500,16.8000,16.9000,NaN
76,Lao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.100,12.800,13.000,13.100,13.600,13.700,13.800,13.5000,12.9000,NaN
77,Latvia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.800,18.800,19.800,20.000,21.100,22.000,22.400,22.8000,23.9000,NaN
78,Lebanon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.400,16.800,16.900,16.300,15.200,14.300,14.200,13.6000,13.9000,NaN
79,Lesotho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.200,58.400,37.300,34.800,48.000,45.900,45.200,40.6000,34.2000,36.40
80,Liberia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000,NaN,17.300,17.300,20.900,20.300,NaN,NaN,NaN,NaN
81,Lithuania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.930,4.930,4.620,4.490,4.510,4.530,4.590,4.8200,4.9300,NaN
82,Luxembourg,16.10,16.60,17.10,20.00,19.60,22.00,22.90,21.10,21.60,...,24.700,25.100,25.000,24.600,25.700,25.900,25.600,25.0000,25.7000,NaN
83,Madagascar,59.00,56.30,NaN,NaN,NaN,NaN,65.40,62.00,57.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Malawi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,14.500,15.400,15.500,13.600,14.100,15.900,15.2000,15.5000,17.30
85,Malaysia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.700,14.900,13.300,14.800,15.600,15.300,14.800,14.3000,13.8000,NaN
86,Maldives,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.12,...,11.600,9.100,8.850,12.100,NaN,NaN,19.500,NaN,NaN,NaN
87,Mali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.900,13.000,12.900,12.500,13.000,13.000,12.600,14.1000,15.4000,NaN
88,Malta,21.20,22.00,20.70,18.90,17.70,18.40,19.20,NaN,19.70,...,26.100,26.500,26.100,26.100,26.400,26.800,26.900,25.6000,26.2000,NaN
89,Marshall Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.400,18.100,17.100,16.700,15.800,15.900,15.900,17.5000,17.8000,NaN
90,Mauritius,NaN,NaN,NaN,NaN,20.00,19.60,17.70,16.40,18.30,...,17.000,18.100,18.000,18.000,18.600,18.400,18.500,8.9900,18.1000,NaN
91,Mexico,7.61,7.09,8.00,9.18,9.04,9.95,10.70,11.30,12.10,...,10.000,9.680,10.100,10.000,9.770,10.300,10.600,12.8000,13.6000,NaN
92,"Micronesia, Fed. Sts.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.290,4.400,4.670,4.980,4.910,5.490,12.600,5.4400,6.0500,NaN
93,Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.400,17.700,18.200,18.300,18.600,18.400,19.800,19.5000,19.3000,NaN
94,Mongolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.700,16.500,19.600,18.500,15.300,15.700,12.900,11.8000,11.3000,NaN
95,Morocco,14.90,15.60,15.50,19.80,16.60,20.00,19.50,20.00,16.60,...,26.500,23.500,22.800,23.300,NaN,NaN,NaN,NaN,NaN,NaN
96,Mozambique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16.100,18.700,20.400,23.100,25.400,21.9000,20.1000,NaN
97,Myanmar,NaN,9.42,7.61,7.92,8.81,10.50,10.00,10.20,9.61,...,NaN,NaN,NaN,NaN,4.520,5.530,5.840,6.0100,6.4100,5.82
98,Namibia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.100,29.400,25.900,30.000,32.900,31.500,33.600,32.5000,28.5000,NaN
99,Nepal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.400,11.800,13.400,13.300,13.900,15.300,15.900,16.7000,18.7000,21.30
100,Netherlands,NaN,22.80,21.50,22.60,22.60,23.70,23.50,23.40,23.40,...,21.400,21.000,21.300,20.400,19.600,19.900,20.900,21.5000,22.2000,NaN
101,New Zealand,23.80,25.60,28.10,27.70,27.50,29.60,28.10,29.40,29.40,...,31.500,29.600,26.100,25.600,26.800,26.600,26.800,27.4000,27.2000,NaN
102,Nicaragua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.200,13.100,13.700,14.500,15.000,15.000,15.300,15.8000,16.3000,NaN
103,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.460,5.110,2.270,1.800,1.560,1.480,NaN,NaN,NaN,NaN
104,North Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.500,17.100,16.900,17.000,16.400,15.700,16.200,16.8000,16.8000,NaN
105,Norway,23.00,20.70,20.50,20.40,21.50,22.10,21.80,22.20,25.10,...,27.900,25.900,26.800,27.700,27.000,25.100,23.500,22.1000,22.0000,NaN
106,Oman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.420,3.390,2.540,2.270,2.600,2.520,NaN,NaN,NaN,NaN
107,Pakistan,NaN,10.40,11.90,10.80,10.90,11.00,11.50,12.30,13.30,...,9.490,8.940,9.980,9.190,NaN,NaN,NaN,NaN,NaN,NaN
108,Palau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.700,16.000,17.000,18.300,18.000,18.400,19.200,19.3000,19.7000,NaN
109,Palestine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.060,5.220,5.450,5.250,4.560,4.810,5.710,5.6000,NaN,NaN
110,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18.000,16.0000,13.5000,NaN
111,Paraguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.800,11.700,12.100,12.600,12.800,12.000,12.700,12.9000,12.6000,13.20
112,Peru,12.70,10.80,11.00,11.60,11.20,11.70,12.50,13.80,18.00,...,16.500,14.500,15.500,16.000,16.500,16.400,16.700,14.9000,13.8000,NaN
113,Philippines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.600,12.200,12.100,12.400,12.900,13.300,13.600,13.6000,13.7000,NaN
114,Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.200,15.900,16.500,16.700,16.000,15.600,15.500,15.6000,16.2000,NaN
115,Portugal,NaN,11.50,11.80,12.30,13.80,14.10,13.50,13.80,15.20,...,21.000,19.200,19.700,21.200,20.900,22.800,22.700,22.9000,22.5000,NaN
116,Qatar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.900,19.900,14.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.800,15.400,16.600,18.000,17.900,17.600,17.900,18.9000,16.8000,NaN
118,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.800,13.000,13.000,13.900,13.700,12.900,13.200,10.6000,9.1300,NaN
119,Rwanda,NaN,8.63,10.20,7.52,9.91,10.90,9.72,11.70,10.50,...,NaN,NaN,NaN,NaN,NaN,NaN,13.300,13.7000,14.8000,NaN
120,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,21.700,19.400,19.600,22.100,23.100,22.7000,24.2000,24.30
121,San Marino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.400,14.700,13.700,14.200,16.100,15.400,NaN,16.2000,15.4000,NaN
122,Sao Tome and Principe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.900,15.200,17.700,17.700,14.600,NaN,NaN,NaN,NaN,NaN
123,Senegal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,18.000,18.700,19.000,19.000,NaN,19.600,20.6000,20.5000,NaN
124,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.400,21.200,21.400,20.200,19.700,NaN,NaN,NaN,NaN,NaN
125,Seychelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.400,25.200,27.900,31.500,30.400,28.100,30.100,29.6000,31.7000,NaN
126,Sierra Leone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.210,8.410,9.080,9.310,9.510,9.120,8.600,NaN,NaN,NaN
127,Singapore,14.60,14.80,15.10,16.60,16.00,16.70,15.90,16.00,17.00,...,13.900,13.100,13.000,13.300,13.800,13.400,13.700,13.3000,13.7000,NaN
128,Slovak Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.400,15.500,15.000,15.500,15.000,15.900,16.700,17.6000,17.4000,NaN
129,Slovenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.400,18.000,18.100,17.900,18.000,18.000,18.200,18.5000,18.6000,NaN
130,Solomon Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,28.700,29.200,30.300,29.200,29.2000,26.7000,NaN
131,South Africa,17.20,17.80,17.40,18.30,18.20,19.10,19.10,19.30,19.20,...,26.800,24.400,25.000,25.200,25.600,26.000,26.500,27.3000,27.1000,NaN
132,South Korea,11.20,10.50,11.60,13.30,14.50,14.20,14.60,14.80,14.80,...,15.100,14.300,14.000,14.400,14.700,14.300,13.900,13.9000,14.8000,NaN
133,Spain,8.98,9.35,8.60,8.79,9.05,8.92,9.53,9.70,9.70,...,13.300,11.000,13.000,12.400,12.200,14.000,14.300,14.4000,13.8000,NaN
134,Sri Lanka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.300,12.800,11.300,11.300,10.400,10.500,10.100,12.4000,12.3000,NaN
135,St. Kitts and Nevis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.500,22.200,22.100,20.300,21.700,19.800,20.400,NaN,NaN,NaN
136,St. Lucia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.000,21.200,19.500,19.700,19.100,20.200,20.400,NaN,NaN,NaN
137,St. Vincent and the Grenadines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.900,23.700,22.900,22.600,23.000,21.600,23.900,NaN,NaN,NaN
138,Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.300,17.200,15.700,18.500,19.500,NaN,NaN,NaN,NaN,NaN
139,Swaziland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.800,25.300,16.000,16.300,28.600,NaN,NaN,NaN,NaN,NaN
140,Sweden,19.30,17.80,17.30,16.70,19.60,20.30,18.60,17.00,16.50,...,27.000,26.900,27.100,26.500,26.100,26.200,26.300,27.0000,27.7000,NaN
141,Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.51,...,9.910,9.680,9.720,9.650,9.520,9.600,9.400,9.8500,9.7700,NaN
142,Syria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.900,NaN,NaN,NaN
144,Thailand,11.00,10.20,12.60,11.20,10.80,11.60,11.70,12.40,13.10,...,15.400,14.200,14.900,16.400,15.400,16.900,15.600,16.0000,15.5000,NaN
145,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,24.300,24.900,25.700,23.200,22.500,18.5000,9.8200,NaN
146,Togo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.900,15.300,15.700,16.400,16.600,20.000,NaN,21.8000,21.9000,NaN
147,Trinidad and Tobago,NaN,NaN,NaN,NaN,29.60,32.60,28.70,29.20,35.70,...,29.500,26.800,26.200,25.600,26.400,NaN,27.100,NaN,NaN,NaN
148,Tunisia,17.80,19.00,17.90,20.20,19.90,21.30,22.60,21.80,21.00,...,20.500,20.000,20.100,21.200,21.100,NaN,NaN,NaN,NaN,NaN
149,Turkey,13.40,14.30,13.20,14.70,16.30,16.70,16.50,14.60,14.30,...,17.700,18.300,19.400,18.700,18.400,18.500,18.100,18.2000,18.3000,NaN
150,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9000,13.5000,NaN
151,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.900,16.400,15.600,18.500,18.300,17.600,17.300,20.5000,19.6000,NaN
152,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.321,0.364,0.370,0.356,0.0577,0.0435,NaN
153,United Kingdom,23.00,21.10,23.70,24.30,23.80,23.30,22.20,21.90,23.90,...,26.500,24.200,25.400,26.100,25.200,25.200,24.900,25.2000,25.6000,NaN
154,United States,11.80,11.50,11.80,11.20,10.70,11.60,11.50,12.00,12.10,...,10.300,7.940,8.610,9.590,9.820,10.600,11.000,11.2000,10.9000,NaN
155,Uruguay,13.70,10.40,12.70,12.20,15.50,15.80,16.00,14.40,15.80,...,18.200,18.700,18.900,19.100,18.800,19.000,18.600,18.5000,23.7000,NaN
156,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16.200,17.200,17.500,17.300,17.5000,17.3000,NaN
157,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,16.000,15.500,16.000,16.600,17.200,17.400,16.7000,16.6000,NaN
158,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.400,20.600,22.300,22.200,19.000,19.100,NaN,NaN,NaN,NaN
159,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.200,12.500,13.200,17.100,16.200,15.700,17.000,16.8000,14.9000,NaN
160,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.300,20.700,20.900,21.400,NaN,NaN,NaN,NaN,NaN

In [252]:
tax_last_10 = tax.iloc[:, np.r_[:1, 35:46]]
tax_last_10

,country,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Afghanistan,6.88,5.23,6.040,8.440,9.120,8.850,7.470,7.080,6.840,7.5500,NaN
1,Albania,NaN,NaN,NaN,NaN,NaN,18.000,17.500,16.500,18.300,18.5000,17.6000
2,Algeria,40.80,37.40,45.300,35.100,34.400,37.200,NaN,NaN,NaN,NaN,NaN
3,Angola,29.30,23.20,27.000,17.100,16.900,17.300,16.700,15.500,15.600,12.5000,10.3000
4,Antigua and Barbuda,18.20,19.50,18.700,17.300,18.500,17.900,18.500,17.200,16.500,NaN,NaN
5,Argentina,12.90,12.40,13.300,12.400,12.900,12.700,13.000,12.500,12.600,12.3000,12.2000
6,Armenia,14.40,16.00,17.300,16.500,17.100,17.200,17.500,NaN,21.600,20.9000,21.3000
7,Australia,24.60,24.10,24.300,22.100,20.600,20.400,21.200,22.100,22.000,22.0000,22.3000
8,Austria,25.10,25.40,26.100,25.200,25.300,25.400,25.900,26.400,26.400,26.8000,25.7000
9,Azerbaijan,NaN,NaN,16.400,14.100,12.200,12.200,12.800,13.400,14.200,15.6000,NaN
10,Bahamas,11.20,11.40,12.100,11.300,10.900,12.900,11.900,11.400,11.400,12.7000,14.2000
11,Bahrain,1.17,1.15,1.240,1.360,1.180,1.110,NaN,1.070,NaN,NaN,NaN
12,Bangladesh,7.04,6.92,7.660,7.500,7.830,8.690,9.020,8.960,8.640,8.5000,8.7700
13,Barbados,25.10,26.80,26.400,24.900,25.100,25.900,24.200,23.400,24.000,26.1000,NaN
14,Belarus,22.20,23.70,25.400,19.300,16.300,14.500,14.700,13.400,12.700,14.2000,13.8000
15,Belgium,25.20,24.70,25.100,23.600,24.300,24.700,25.700,26.200,26.300,24.7000,23.1000
16,Belize,21.80,22.90,21.700,22.500,23.600,22.600,22.500,23.300,23.400,NaN,NaN
17,Benin,14.20,15.70,16.100,15.000,15.500,14.800,14.400,15.400,NaN,NaN,NaN
18,Bhutan,9.03,7.52,8.420,9.240,13.100,13.500,14.700,14.400,13.300,13.8000,13.2000
19,Bolivia,16.80,17.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Bosnia and Herzegovina,21.70,21.40,20.300,18.900,19.700,20.300,20.500,19.800,19.800,19.9000,20.0000
21,Botswana,26.90,25.70,27.400,27.300,23.600,23.200,26.600,25.600,25.800,24.7000,20.8000
22,Brazil,15.40,15.80,15.500,14.400,13.600,14.200,13.700,13.400,12.800,12.8000,12.9000
23,Bulgaria,21.10,22.90,22.200,19.000,18.500,17.700,19.000,19.800,19.600,20.2000,20.0000
24,Burkina Faso,12.10,12.70,11.900,12.500,12.700,13.700,15.600,16.800,15.400,15.1000,15.8000
25,Burundi,NaN,NaN,NaN,NaN,13.900,14.700,13.700,12.200,NaN,NaN,NaN
26,Cambodia,8.18,9.70,10.600,9.650,10.000,10.200,11.100,12.100,14.600,14.2000,15.3000
27,Canada,13.40,13.40,12.400,12.300,11.800,11.800,11.700,11.700,11.800,12.3000,12.2000
28,Cape Verde,22.70,20.90,21.300,18.400,NaN,NaN,17.900,NaN,NaN,NaN,NaN
29,Central African Republic,NaN,NaN,9.060,9.170,10.100,9.290,NaN,NaN,NaN,NaN,NaN
30,Chile,19.50,20.30,18.700,14.500,17.400,18.900,19.000,17.400,17.000,17.4000,17.4000
31,China,9.06,9.77,10.100,10.300,10.200,10.300,10.200,9.870,9.670,9.3700,NaN
32,Colombia,NaN,NaN,12.900,12.600,12.100,14.600,13.300,14.100,15.000,15.1000,13.3000
33,"Congo, Dem. Rep.",6.83,6.99,8.970,7.890,8.350,NaN,NaN,NaN,NaN,NaN,NaN
34,"Congo, Rep.",5.79,6.60,5.950,8.400,7.600,8.860,9.430,NaN,NaN,NaN,NaN
35,Costa Rica,13.90,14.90,15.300,13.300,13.100,13.400,13.300,13.700,13.400,13.7000,14.0000
36,Cote d'Ivoire,14.70,15.10,15.100,14.600,14.300,10.900,14.300,14.500,14.000,15.4000,15.2000
37,Croatia,19.90,19.90,20.000,19.200,19.100,18.400,19.500,19.000,19.100,NaN,NaN
38,Cyprus,40.90,48.30,46.100,23.300,23.200,23.300,23.300,23.400,24.500,24.1000,24.3000
39,Czech Republic,14.10,14.50,13.400,13.400,13.400,14.300,14.700,14.900,14.200,14.6000,14.7000
40,Denmark,31.90,35.10,33.400,33.200,32.700,32.800,33.400,33.800,36.500,33.9000,33.7000
41,Dominica,23.50,25.10,24.800,24.300,24.600,23.100,23.000,22.400,22.100,NaN,NaN
42,Dominican Republic,14.00,14.90,14.200,12.600,12.200,12.300,13.000,13.500,13.600,13.3000,13.5000
43,Egypt,15.80,15.30,15.300,15.700,14.100,14.000,12.400,13.500,12.200,12.5000,NaN
44,El Salvador,15.70,16.70,17.100,15.000,15.800,15.300,16.200,17.100,16.700,16.9000,17.6000
45,Equatorial Guinea,9.67,7.55,7.790,12.800,7.590,7.020,8.740,8.520,8.300,11.5000,NaN
46,Estonia,1.28,1.30,1.240,1.370,1.270,1.230,1.270,1.290,1.340,1.4000,1.4300
47,Ethiopia,8.26,7.81,7.810,6.580,8.160,9.210,9.380,8.760,NaN,NaN,NaN
48,Fiji,23.20,NaN,NaN,NaN,21.800,23.000,23.200,23.600,24.600,25.5000,NaN
49,Finland,21.50,21.10,20.500,19.000,18.700,20.100,20.300,20.700,20.800,20.7000,21.0000
50,France,22.60,22.10,22.000,20.700,22.000,21.800,22.600,23.200,23.200,23.2000,23.1000
51,Gambia,7.98,13.00,14.700,15.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Georgia,15.40,17.70,23.800,23.100,22.100,23.800,24.100,23.400,23.500,23.8000,23.5000
53,Germany,10.80,11.30,11.400,11.600,11.100,11.400,11.600,11.600,11.500,11.4000,11.2000
54,Ghana,NaN,NaN,NaN,NaN,13.700,NaN,NaN,NaN,NaN,NaN,NaN
55,Greece,20.00,20.20,20.200,19.800,20.200,22.100,23.600,23.700,24.400,24.9000,26.7000
56,Grenada,19.10,19.70,19.500,18.200,18.700,19.200,18.700,18.400,19.400,NaN,NaN
57,Guatemala,11.90,12.10,11.300,10.300,10.400,10.800,10.800,10.900,10.800,10.2000,10.4000
58,Honduras,15.20,16.40,16.100,14.200,14.400,14.800,14.700,15.100,16.500,17.3000,NaN
59,Hungary,19.80,21.40,23.300,23.300,22.800,21.100,22.900,22.700,23.000,23.4000,23.4000
60,Iceland,27.40,26.20,23.200,20.100,20.700,21.200,22.100,22.700,25.300,23.5000,38.5000
61,India,11.40,12.30,11.100,9.940,10.500,10.200,10.800,11.000,NaN,NaN,NaN
62,Indonesia,NaN,NaN,13.300,11.100,10.500,11.200,11.400,11.300,10.800,10.8000,10.3000
63,Iran,6.22,5.94,6.200,7.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.890,1.2300,2.0200
65,Ireland,26.80,25.90,23.700,22.000,21.800,21.800,22.500,22.800,23.200,18.9000,18.8000
66,Israel,26.10,26.10,23.800,21.900,22.500,22.700,22.100,23.000,23.300,23.4000,23.4000
67,Italy,22.10,22.40,21.900,22.400,22.300,22.300,23.600,23.700,23.500,23.4000,23.7000
68,Jamaica,24.00,24.80,24.700,25.000,24.300,23.400,24.300,24.000,24.100,24.8000,26.1000
69,Japan,10.50,10.10,8.930,8.370,8.810,9.360,9.680,10.400,11.500,11.4000,11.1000
70,Jordan,NaN,NaN,17.800,17.000,16.000,15.000,15.300,15.300,NaN,NaN,NaN
71,Kazakhstan,NaN,NaN,NaN,NaN,15.700,18.300,13.300,16.000,14.200,9.8400,9.9200
72,Kenya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.900,16.3000,15.8000
73,Kiribati,NaN,NaN,NaN,NaN,16.000,18.100,18.500,17.800,17.800,22.3000,24.5000
74,Kuwait,0.97,1.09,0.876,0.971,0.979,0.800,0.716,0.777,0.890,1.3800,NaN
75,Kyrgyz Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.600,17.500,16.8000,16.9000
76,Lao,NaN,NaN,12.100,12.800,13.000,13.100,13.600,13.700,13.800,13.5000,12.9000
77,Latvia,22.20,21.70,20.800,18.800,19.800,20.000,21.100,22.000,22.400,22.8000,23.9000
78,Lebanon,15.20,15.10,16.400,16.800,16.900,16.300,15.200,14.300,14.200,13.6000,13.9000
79,Lesotho,48.00,49.30,51.200,58.400,37.300,34.800,48.000,45.900,45.200,40.6000,34.2000
80,Liberia,13.40,19.00,20.000,NaN,17.300,17.300,20.900,20.300,NaN,NaN,NaN
81,Lithuania,5.93,5.89,5.930,4.930,4.620,4.490,4.510,4.530,4.590,4.8200,4.9300
82,Luxembourg,24.20,24.70,24.700,25.100,25.000,24.600,25.700,25.900,25.600,25.0000,25.7000
83,Madagascar,10.70,11.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Malawi,NaN,NaN,NaN,14.500,15.400,15.500,13.600,14.100,15.900,15.2000,15.5000
85,Malaysia,14.50,14.30,14.700,14.900,13.300,14.800,15.600,15.300,14.800,14.3000,13.8000
86,Maldives,11.80,12.10,11.600,9.100,8.850,12.100,NaN,NaN,19.500,NaN,NaN
87,Mali,13.30,13.10,11.900,13.000,12.900,12.500,13.000,13.000,12.600,14.1000,15.4000
88,Malta,60.20,62.90,26.100,26.500,26.100,26.100,26.400,26.800,26.900,25.6000,26.2000
89,Marshall Islands,NaN,NaN,18.400,18.100,17.100,16.700,15.800,15.900,15.900,17.5000,17.8000
90,Mauritius,16.00,15.10,17.000,18.100,18.000,18.000,18.600,18.400,18.500,8.9900,18.1000
91,Mexico,NaN,NaN,10.000,9.680,10.100,10.000,9.770,10.300,10.600,12.8000,13.6000
92,"Micronesia, Fed. Sts.",NaN,NaN,4.290,4.400,4.670,4.980,4.910,5.490,12.600,5.4400,6.0500
93,Moldova,19.60,20.60,20.400,17.700,18.200,18.300,18.600,18.400,19.800,19.5000,19.3000
94,Mongolia,28.70,23.50,21.700,16.500,19.600,18.500,15.300,15.700,12.900,11.8000,11.3000
95,Morocco,21.50,23.90,26.500,23.500,22.800,23.300,NaN,NaN,NaN,NaN,NaN
96,Mozambique,NaN,NaN,NaN,NaN,16.100,18.700,20.400,23.100,25.400,21.9000,20.1000
97,Myanmar,NaN,NaN,NaN,NaN,NaN,NaN,4.520,5.530,5.840,6.0100,6.4100
98,Namibia,29.10,30.90,30.100,29.400,25.900,30.000,32.900,31.500,33.600,32.5000,28.5000
99,Nepal,8.78,9.77,10.400,11.800,13.400,13.300,13.900,15.300,15.900,16.7000,18.7000
100,Netherlands,21.80,21.90,21.400,21.000,21.300,20.400,19.600,19.900,20.900,21.5000,22.2000
101,New Zealand,32.00,30.10,31.500,29.600,26.100,25.600,26.800,26.600,26.800,27.4000,27.2000
102,Nicaragua,13.70,13.90,13.200,13.100,13.700,14.500,15.000,15.000,15.300,15.8000,16.3000
103,Nigeria,2.41,3.98,5.460,5.110,2.270,1.800,1.560,1.480,NaN,NaN,NaN
104,North Macedonia,18.10,19.10,18.500,17.100,16.900,17.000,16.400,15.700,16.200,16.8000,16.8000
105,Norway,28.90,28.10,27.900,25.900,26.800,27.700,27.000,25.100,23.500,22.1000,22.0000
106,Oman,1.94,2.70,2.420,3.390,2.540,2.270,2.600,2.520,NaN,NaN,NaN
107,Pakistan,10.40,9.23,9.490,8.940,9.980,9.190,NaN,NaN,NaN,NaN,NaN
108,Palau,NaN,NaN,16.700,16.000,17.000,18.300,18.000,18.400,19.200,19.3000,19.7000
109,Palestine,4.60,4.63,5.060,5.220,5.450,5.250,4.560,4.810,5.710,5.6000,NaN
110,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000,16.0000,13.5000
111,Paraguay,10.50,10.10,10.800,11.700,12.100,12.600,12.800,12.000,12.700,12.9000,12.6000
112,Peru,15.70,16.40,16.500,14.500,15.500,16.000,16.500,16.400,16.700,14.9000,13.8000
113,Philippines,13.70,13.50,13.600,12.200,12.100,12.400,12.900,13.300,13.600,13.6000,13.7000
114,Poland,17.20,18.10,18.200,15.900,16.500,16.700,16.000,15.600,15.500,15.6000,16.2000
115,Portugal,21.10,21.30,21.000,19.200,19.700,21.200,20.900,22.800,22.700,22.9000,22.5000
116,Qatar,20.10,20.60,15.900,19.900,14.700,NaN,NaN,NaN,NaN,NaN,NaN
117,Romania,17.70,17.40,16.800,15.400,16.600,18.000,17.900,17.600,17.900,18.9000,16.8000
118,Russia,16.60,16.60,15.800,13.000,13.000,13.900,13.700,12.900,13.200,10.6000,9.1300
119,Rwanda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.300,13.7000,14.8000
120,Samoa,NaN,NaN,NaN,NaN,21.700,19.400,19.600,22.100,23.100,22.7000,24.2000
121,San Marino,15.70,15.50,15.400,14.700,13.700,14.200,16.100,15.400,NaN,16.2000,15.4000
122,Sao Tome and Principe,16.10,16.30,14.900,15.200,17.700,17.700,14.600,NaN,NaN,NaN,NaN
123,Senegal,NaN,NaN,NaN,18.000,18.700,19.000,19.000,NaN,19.600,20.6000,20.5000
124,Serbia,NaN,22.80,22.400,21.200,21.400,20.200,19.700,NaN,NaN,NaN,NaN
125,Seychelles,24.70,23.30,22.400,25.200,27.900,31.500,30.400,28.100,30.100,29.6000,31.7000
126,Sierra Leone,8.43,7.88,8.210,8.410,9.080,9.310,9.510,9.120,8.600,NaN,NaN
127,Singapore,11.90,12.90,13.900,13.100,13.000,13.300,13.800,13.400,13.700,13.3000,13.7000
128,Slovak Republic,16.80,16.70,16.400,15.500,15.000,15.500,15.000,15.900,16.700,17.6000,17.4000
129,Slovenia,20.80,20.00,19.400,18.000,18.100,17.900,18.000,18.000,18.200,18.5000,18.6000
130,Solomon Islands,NaN,NaN,NaN,NaN,NaN,28.700,29.200,30.300,29.200,29.2000,26.7000
131,South Africa,27.30,27.60,26.800,24.400,25.000,25.200,25.600,26.000,26.500,27.3000,27.1000
132,South Korea,14.30,15.50,15.100,14.300,14.000,14.400,14.700,14.300,13.900,13.9000,14.8000
133,Spain,16.10,16.70,13.300,11.000,13.000,12.400,12.200,14.000,14.300,14.4000,13.8000
134,Sri Lanka,14.60,14.20,13.300,12.800,11.300,11.300,10.400,10.500,10.100,12.4000,12.3000
135,St. Kitts and Nevis,21.10,22.10,22.500,22.200,22.100,20.300,21.700,19.800,20.400,NaN,NaN
136,St. Lucia,19.70,19.10,21.000,21.200,19.500,19.700,19.100,20.200,20.400,NaN,NaN
137,St. Vincent and the Grenadines,21.90,22.90,23.900,23.700,22.900,22.600,23.000,21.600,23.900,NaN,NaN
138,Suriname,16.70,18.90,17.300,17.200,15.700,18.500,19.500,NaN,NaN,NaN,NaN
139,Swaziland,31.00,27.30,29.800,25.300,16.000,16.300,28.600,NaN,NaN,NaN,NaN
140,Sweden,28.50,28.40,27.000,26.900,27.100,26.500,26.100,26.200,26.300,27.0000,27.7000
141,Switzerland,9.52,9.36,9.910,9.680,9.720,9.650,9.520,9.600,9.400,9.8500,9.7700
142,Syria,14.60,14.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.900,NaN,NaN
144,Thailand,15.60,15.10,15.400,14.200,14.900,16.400,15.400,16.900,15.600,16.0000,15.5000
145,Timor-Leste,NaN,NaN,NaN,NaN,24.300,24.900,25.700,23.200,22.500,18.5000,9.8200
146,Togo,14.80,16.20,14.900,15.300,15.700,16.400,16.600,20.000,NaN,21.8000,21.9000
147,Trinidad and Tobago,30.30,26.00,29.500,26.800,26.200,25.600,26.400,NaN,27.100,NaN,NaN
148,Tunisia,18.50,19.10,20.500,20.000,20.100,21.200,21.100,NaN,NaN,NaN,NaN
149,Turkey,NaN,NaN,17.700,18.300,19.400,18.700,18.400,18.500,18.100,18.2000,18.3000
150,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9000,13.5000
151,Ukraine,17.70,16.50,17.900,16.400,15.600,18.500,18.300,17.600,17.300,20.5000,19.6000
152,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,0.321,0.364,0.370,0.356,0.0577,0.0435
153,United Kingdom,25.70,25.90,26.500,24.200,25.400,26.100,25.200,25.200,24.900,25.2000,25.6000
154,United States,11.30,11.30,10.300,7.940,8.610,9.590,9.820,10.600,11.000,11.2000,10.9000
155,Uruguay,19.00,18.40,18.200,18.700,18.900,19.100,18.800,19.000,18.600,18.5000,23.7000
156,Uzbekistan,NaN,NaN,NaN,NaN,NaN,16.200,17.200,17.500,17.300,17.5000,17.3000
157,Vanuatu,NaN,NaN,NaN,16.000,15.500,16.000,16.600,17.200,17.400,16.7000,16.6000
158,Vietnam,22.20,21.50,22.400,20.600,22.300,22.200,19.000,19.100,NaN,NaN,NaN
159,Zambia,13.70,13.90,14.200,12.500,13.200,17.100,16.200,15.700,17.000,16.8000,14.9000
160,Zimbabwe,NaN,NaN,NaN,10.300,20.700,20.900,21.400,NaN,NaN,NaN,NaN

In [253]:
tax_last_10 = tax_last_10.melt(id_vars=['country'], var_name='year', value_name='tax_%_gdp')
tax_last_10

                  country  year  tax_%_gdp
0             Afghanistan  2006       6.88
1                 Albania  2006        NaN
2                 Algeria  2006      40.80
3                  Angola  2006      29.30
4     Antigua and Barbuda  2006      18.20
...                   ...   ...        ...
1766           Uzbekistan  2016      17.30
1767              Vanuatu  2016      16.60
1768              Vietnam  2016        NaN
1769               Zambia  2016      14.90
1770             Zimbabwe  2016        NaN

[1771 rows x 3 columns]

In [179]:
tax_last_10.sort_values(['country', 'year'], inplace=True)
tax_last_10

          country  year  tax_%_gdp
0     Afghanistan  2006       6.88
161   Afghanistan  2007       5.23
322   Afghanistan  2008       6.04
483   Afghanistan  2009       8.44
644   Afghanistan  2010       9.12
...           ...   ...        ...
1126     Zimbabwe  2012      21.40
1287     Zimbabwe  2013        NaN
1448     Zimbabwe  2014        NaN
1609     Zimbabwe  2015        NaN
1770     Zimbabwe  2016        NaN

[1771 rows x 3 columns]

In [181]:
tax_last_10.to_csv('tax_last_10.csv', index=False)

In [182]:
tax_last_10 = pd.read_csv('tax_last_10.csv')
tax_last_10

          country  year  tax_%_gdp
0     Afghanistan  2006       6.88
1     Afghanistan  2007       5.23
2     Afghanistan  2008       6.04
3     Afghanistan  2009       8.44
4     Afghanistan  2010       9.12
...           ...   ...        ...
1766     Zimbabwe  2012      21.40
1767     Zimbabwe  2013        NaN
1768     Zimbabwe  2014        NaN
1769     Zimbabwe  2015        NaN
1770     Zimbabwe  2016        NaN

[1771 rows x 3 columns]

In [209]:
income = pd.read_csv('income_per_person_gdppercapita_ppp_inflation_adjusted.csv')

In [212]:
income_last_10 = income.iloc[:, np.r_[:1, 207:218]]
income_last_10

,country,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Afghanistan,1120,1250,1270,1500,1670,1630,1770,1810,1800,1770,1760
1,Albania,7910,8450,9160,9530,9930,10200,10400,10500,10700,11000,11400
2,Algeria,12400,12600,12700,12700,12900,13000,13200,13300,13500,13800,13900
3,Andorra,42700,43400,41400,41700,39000,42000,41900,43700,44900,46600,48200
4,Angola,5500,6040,6470,6290,6360,6350,6650,6730,6810,6650,6260
5,Antigua and Barbuda,24700,26500,26100,22600,20700,20000,20400,20100,20800,21400,22400
6,Argentina,16700,18000,18600,17300,18900,19800,19400,19600,18900,19200,18600
7,Armenia,6110,7010,7560,6530,6700,7020,7510,7720,7950,8170,8160
8,Australia,39500,40700,41400,41300,41500,42000,42800,43200,43700,44100,44600
9,Austria,42500,43900,44400,42700,43300,44500,44600,44300,44200,44300,44700
10,Azerbaijan,10900,13500,14600,15700,16200,15800,15900,16600,16900,16800,16100
11,Bahamas,33000,32900,31500,29700,29700,29500,30100,29700,29300,29400,28600
12,Bahrain,42700,42800,42200,40700,40600,40200,41000,42700,43800,43900,43700
13,Bangladesh,2100,2220,2320,2410,2520,2650,2790,2930,3070,3230,3420
14,Barbados,16900,17100,17000,16300,16300,16300,16300,16300,16300,16400,16700
15,Belarus,12400,13600,15000,15100,16300,17200,17500,17600,17900,17200,16800
16,Belgium,40500,41600,41600,40400,41100,41300,41100,41000,41300,41800,42200
17,Belize,8000,7880,7930,7780,7850,7830,7880,7770,7880,7980,7770
18,Benin,1750,1810,1840,1830,1820,1820,1860,1940,2000,1990,2010
19,Bhutan,4830,5630,5840,6160,6810,7270,7550,7620,7950,8380,8940
20,Bolivia,4780,4910,5130,5210,5340,5530,5720,6010,6240,6440,6620
21,Bosnia and Herzegovina,8800,9320,9850,9600,9760,9980,10000,10500,10800,11300,11800
22,Botswana,12400,13200,13700,12400,13200,13800,14300,15700,16200,15700,16000
23,Brazil,12700,13300,13900,13700,14600,15100,15200,15500,15500,14800,14200
24,Brunei,85400,84500,81900,79500,80600,82500,82200,79300,76400,75100,72400
25,Bulgaria,13400,14500,15400,15000,15300,15700,15800,15900,16300,17000,17800
26,Burkina Faso,1310,1340,1390,1390,1420,1470,1520,1560,1580,1600,1640
27,Burundi,707,707,718,721,734,739,748,761,768,716,689
28,Cambodia,2150,2330,2450,2420,2520,2660,2810,2960,3120,3290,3470
29,Cameroon,2800,2860,2880,2860,2880,2910,2970,3040,3130,3220,3290
30,Canada,41200,41600,41600,39900,40700,41600,41800,42400,43100,43100,43100
31,Cape Verde,5070,5770,6080,5930,5940,6100,6090,6060,6020,6010,6210
32,Central African Republic,863,885,888,950,982,1020,1060,678,677,703,731
33,Chad,1740,1740,1730,1740,1920,1850,1950,1990,2060,2050,1860
34,Chile,17900,18500,19000,18500,19400,20300,21200,21900,22000,22300,22300
35,China,6390,7260,7930,8630,9500,10400,11100,11900,12700,13500,14400
36,Colombia,9840,10400,10600,10600,11000,11700,12000,12400,12900,13100,13200
37,Comoros,2380,2340,2380,2390,2430,2470,2480,2530,2530,2490,2490
38,"Congo, Dem. Rep.",605,623,640,637,660,682,706,741,785,812,805
39,"Congo, Rep.",5000,4760,4850,5050,5320,5350,5420,5470,5700,5700,5400
40,Costa Rica,11600,12300,12700,12500,12900,13300,13800,13900,14300,14600,15100
41,Cote d'Ivoire,2660,2650,2660,2680,2670,2500,2700,2860,3040,3230,3400
42,Croatia,21100,22200,22700,21000,20800,20800,20300,20300,20400,21000,21900
43,Cuba,5920,6050,6340,6480,6700,6930,7140,7380,7630,7890,7890
44,Cyprus,34600,35600,36000,34400,33900,33200,31800,30000,29900,30700,32000
45,Czech Republic,27500,28800,29400,27800,28400,28800,28500,28400,29100,30600,31300
46,Denmark,46200,46400,45900,43400,44000,44400,44300,44600,45100,45800,46500
47,Djibouti,2360,2440,2540,2630,2670,2740,2830,2920,3040,3180,3060
48,Dominica,9090,9660,10300,10200,10300,10300,10100,10100,10500,10200,10500
49,Dominican Republic,9860,10500,10700,10600,11400,11600,11800,12200,13000,13700,14500
50,Ecuador,8780,8820,9230,9130,9310,9880,10300,10600,10900,10700,10400
51,Egypt,8540,8990,9460,9720,10000,9980,9980,9970,10000,10200,10500
52,El Salvador,6120,6200,6310,6150,6280,6490,6650,6760,6850,6980,7120
53,Equatorial Guinea,32600,35900,40400,39100,34000,34600,35900,33000,31700,27700,24300
54,Eritrea,2190,2170,1910,1950,1960,2100,1180,1160,1200,1240,1240
55,Estonia,25300,27400,26000,22200,22700,24500,25700,26300,27100,27600,28600
56,Ethiopia,794,860,928,982,1080,1160,1230,1320,1410,1520,1620
57,Fiji,7510,7370,7370,7190,7350,7520,7610,7970,8410,8780,8970
58,Finland,40500,42500,42600,38900,39800,40700,39900,39400,39000,39100,40100
59,France,37000,37700,37600,36300,36800,37400,37400,37400,37600,37800,38100
60,Gabon,16000,16500,15500,15000,15500,16000,16200,16500,16600,16700,16500
61,Gambia,1410,1420,1450,1500,1550,1440,1480,1500,1440,1480,1440
62,Georgia,5770,6530,6710,6520,6980,7550,8080,8380,8770,9010,9260
63,Germany,39100,40500,41000,38800,40400,42700,42800,42900,43700,44000,44700
64,Ghana,2600,2650,2810,2880,3030,3370,3600,3770,3790,3790,3830
65,Greece,31100,32100,31900,30400,28700,26100,24400,23700,24100,24100,24200
66,Grenada,11200,11900,11900,11100,11000,11000,10800,11000,11800,12400,12800
67,Guatemala,6460,6710,6780,6670,6710,6850,6900,7010,7150,7290,7370
68,Guinea,1580,1650,1680,1630,1670,1720,1780,1810,1840,1860,2010
69,Guinea-Bissau,1370,1380,1390,1400,1430,1510,1440,1450,1430,1470,1530
70,Guyana,4970,5320,5420,5610,5830,6110,6400,6690,6910,7090,7290
71,Haiti,1580,1610,1600,1620,1510,1570,1590,1630,1660,1650,1660
72,Honduras,3810,3950,4030,3850,3910,3980,4070,4110,4160,4250,4340
73,Hungary,23400,23500,23700,22200,22400,22800,22600,23100,24200,25100,25700
74,Iceland,41800,44600,44700,41500,40100,40800,41100,42400,42800,44200,46800
75,India,3630,3850,3910,4160,4450,4630,4820,5070,5380,5740,6150
76,Indonesia,7120,7470,7820,8070,8460,8860,9270,9650,10000,10400,10700
77,Iran,16400,17500,17400,17300,18100,18400,16800,16600,17100,16700,18700
78,Iraq,11800,11800,12500,12700,13200,13700,15000,15600,15100,15000,16500
79,Ireland,47600,48700,45700,42900,43500,44900,44800,45200,48800,60500,62800
80,Israel,27600,28700,29000,28600,29700,30600,30600,31300,31900,32100,32700
81,Italy,38200,38600,38000,35700,36200,36300,35200,34200,33900,34300,34700
82,Jamaica,8630,8710,8590,8180,8020,8110,8020,8010,8020,8050,8120
83,Japan,36100,36700,36300,34300,35800,35800,36400,37100,37300,37800,38100
84,Jordan,9090,9420,9630,9660,9390,9120,8870,8660,8530,8410,8320
85,Kazakhstan,17500,18900,19300,19000,20100,21300,22000,23000,23600,23500,23400
86,Kenya,2270,2360,2300,2310,2440,2520,2560,2640,2710,2800,2890
87,Kiribati,1920,1910,1830,1800,1750,1750,1800,1850,1820,1980,2050
88,Kuwait,96400,96800,93600,81900,75400,78000,78700,75600,72600,70300,70100
89,Kyrgyz Republic,2420,2600,2790,2840,2790,2920,2870,3120,3180,3230,3310
90,Lao,3330,3520,3740,3950,4220,4490,4770,5080,5390,5690,6000
91,Latvia,19800,21900,21400,18600,18300,19800,20800,21600,22200,23000,23700
92,Lebanon,10600,11500,12600,13700,14400,13800,13400,12800,12300,11900,11800
93,Lesotho,2000,2100,2240,2290,2420,2580,2720,2750,2810,2870,2940
94,Liberia,982,1030,1060,1080,1100,1150,1210,1280,1260,1230,1180
95,Libya,27300,28600,29000,28400,29500,11100,24600,21100,16000,14400,13900
96,Lithuania,20200,22700,23600,20300,21100,22900,24000,25100,26300,27000,28000
97,Luxembourg,91700,97900,94900,89100,91700,92000,89500,90700,92300,93700,93900
98,Madagascar,1420,1460,1520,1420,1390,1370,1370,1360,1370,1380,1400
99,Malawi,884,942,986,1040,1080,1100,1090,1110,1140,1140,1140
100,Malaysia,19200,20000,20600,19900,21000,21800,22700,23400,24500,25400,26100
101,Maldives,11400,12000,12800,11500,12000,12500,12300,12600,12900,12700,13000
102,Mali,1790,1790,1810,1840,1880,1880,1810,1800,1870,1920,1970
103,Malta,26700,27700,28400,27500,28300,28600,29100,30000,31900,34500,35600
104,Marshall Islands,3060,3160,3100,3050,3240,3270,3370,3450,3410,3380,3430
105,Mauritania,3570,3570,3500,3370,3430,3480,3580,3690,3780,3720,3690
106,Mauritius,13400,14100,14900,15300,15900,16600,17100,17600,18300,18900,19600
107,Mexico,16600,16800,16700,15600,16200,16500,16900,16900,17200,17500,17800
108,"Micronesia, Fed. Sts.",3280,3240,3200,3250,3320,3410,3310,3140,3030,3140,3120
109,Moldova,4210,4340,4690,4420,4730,5010,4980,5440,5710,5700,5950
110,Monaco,54600,60900,59900,53700,54100,58100,58100,57900,58300,58800,59500
111,Mongolia,6480,7050,7570,7350,7690,8850,9750,10700,11300,11300,11200
112,Montenegro,12800,13600,14600,13700,14000,14500,14100,14600,14800,15300,15700
113,Morocco,5710,5850,6120,6300,6460,6700,6810,7020,7110,7330,7310
114,Mozambique,809,846,879,910,945,984,1030,1070,1120,1160,1170
115,Myanmar,2530,2820,3080,3390,3690,3870,4110,4420,4740,5030,5290
116,Namibia,8110,8390,8460,8330,8680,8960,9250,9600,10000,10500,10400
117,Nauru,4030,4050,5420,5860,6610,7340,7910,10100,12600,12300,13000
118,Nepal,1710,1750,1840,1910,1990,2050,2160,2250,2390,2460,2450
119,Netherlands,45300,46900,47700,45700,46100,46600,45900,45800,46200,46900,47700
120,New Zealand,32400,33100,32500,32100,32200,32700,33300,33900,34600,35200,35700
121,Nicaragua,3820,3960,4040,3850,3970,4160,4380,4530,4690,4850,5000
122,Niger,777,772,815,779,812,799,860,870,900,903,912
123,Nigeria,4260,4420,4600,4840,5090,5210,5290,5500,5690,5690,5450
124,North Korea,1750,1710,1760,1730,1710,1720,1730,1740,1750,1720,1720
125,North Macedonia,9850,10500,11000,11000,11400,11600,11500,11900,12300,12800,13100
126,Norway,63900,65100,64600,62700,62400,62100,63000,62900,63400,64000,64200
127,Oman,42500,43100,45100,45700,45300,41900,42600,41300,39700,39200,39200
128,Pakistan,4000,4100,4070,4100,4070,4100,4150,4240,4350,4460,4610
129,Palau,13900,14300,13900,13300,13600,14500,15100,14900,15500,17100,17200
130,Palestine,3360,3500,3610,3820,4020,4410,4570,4560,4450,4490,4600
131,Panama,12700,14000,15100,15000,15600,17100,18500,19400,20000,20800,21500
132,Papua New Guinea,2620,2840,2770,2880,3100,3070,3150,3200,3560,3820,3900
133,Paraguay,8280,8610,9030,8880,9740,10000,9830,10500,10900,11100,11400
134,Peru,8020,8640,9350,9380,10100,10600,11200,11700,11900,12100,12400
135,Philippines,4940,5180,5300,5270,5580,5690,5970,6280,6560,6850,7210
136,Poland,18300,19600,20400,21000,21800,22900,23200,23600,24400,25300,26100
137,Portugal,27000,27600,27600,26700,27200,26800,25800,25700,26000,26600,27200
138,Qatar,117000,116000,116000,113000,120000,124000,120000,118000,117000,116000,114000
139,Romania,15700,17100,19000,18100,17500,17900,18400,19100,19800,20700,21800
140,Russia,21000,22800,24000,22100,23300,24300,25200,25600,25300,24500,24400
141,Rwanda,1140,1190,1290,1340,1400,1470,1560,1590,1670,1770,1830
142,Samoa,5410,5720,5740,5420,5410,5670,5650,5490,5520,5570,5940
143,San Marino,85500,90500,90800,78200,73600,65700,59900,57300,56100,55900,56700
144,Sao Tome and Principe,2340,2350,2470,2460,2560,2610,2640,2710,2840,2890,2950
145,Saudi Arabia,45700,45300,46800,44500,45400,48500,49500,49400,49700,50500,50200
146,Senegal,2680,2740,2770,2760,2780,2740,2800,2800,2900,3000,3100
147,Serbia,11900,12800,13500,13200,13400,13700,13700,14200,14000,14300,14900
148,Seychelles,19100,21000,20100,19800,20400,22600,22600,23500,24200,24900,25600
149,Sierra Leone,1070,1130,1160,1170,1210,1260,1410,1670,1710,1330,1380
150,Singapore,66200,69200,66800,64900,73100,76000,77500,79900,82000,83300,84700
151,Slovak Republic,21700,24100,25400,24000,25200,25800,26200,26600,27300,28400,29200
152,Slovenia,28400,30200,31100,28500,28700,28800,28000,27600,28400,29000,29900
153,Solomon Islands,1760,1840,1930,1800,1870,2070,2100,2110,2100,2090,2110
154,Somalia,615,615,615,615,614,614,616,619,621,623,625
155,South Africa,11500,11900,12100,11800,12000,12200,12300,12400,12400,12400,12200
156,South Korea,26700,28000,28600,28600,30400,31200,31800,32500,33400,34200,35000
157,South Sudan,3610,3920,3940,3960,4010,3700,1940,2140,2170,1910,1680
158,Spain,33700,34300,34200,32700,32500,32100,31100,30700,31200,32400,33400
159,Sri Lanka,6910,7330,7710,7930,8500,9160,9980,10200,10600,11100,11400
160,St. Kitts and Nevis,25100,24900,26300,25200,24600,24800,24400,25500,26800,27200,27600
161,St. Lucia,11600,11700,12100,11800,11700,12000,11900,11600,11600,11600,12000
162,St. Vincent and the Grenadines,10000,10400,10600,10400,10000,9970,10100,10300,10400,10500,10600
163,Sudan,2950,3190,3350,3370,3400,3640,4070,4150,4160,4260,4360
164,Suriname,12500,13000,13300,13600,14100,14800,15000,15300,15200,14500,13500
165,Swaziland,7630,7920,7930,8000,8240,8370,8710,9200,9310,9270,9480
166,Sweden,43000,44100,43500,40900,43000,43800,43400,43500,44200,45700,46300
167,Switzerland,54500,56300,56800,54800,55900,56200,56200,56500,57200,57300,57600
168,Syria,5750,5860,5920,6120,6290,5980,4830,4120,3540,3050,3090
169,Tajikistan,1810,1910,2020,2050,2140,2250,2360,2480,2580,2670,2790
170,Tanzania,1980,2050,2110,2160,2230,2330,2360,2450,2540,2610,2710
171,Thailand,12000,12600,12800,12600,13500,13500,14500,14800,14900,15300,15700
172,Timor-Leste,9020,9310,10000,9280,9010,9860,10200,8890,6470,7660,7570
173,Togo,1160,1160,1170,1200,1240,1290,1340,1380,1420,1470,1500
174,Tonga,4880,4630,4740,4820,4990,5150,5240,5120,5270,5480,5640
175,Trinidad and Tobago,29800,31100,32000,30400,31300,31000,31200,31600,31100,31500,29300
176,Tunisia,9180,9690,10000,10200,10400,10100,10400,10600,10800,10900,10900
177,Turkey,17300,17900,17800,16800,18000,19700,20300,21600,22300,23300,23700
178,Turkmenistan,7130,7820,8850,9250,9940,11200,12200,13200,14300,15000,15600
179,Tuvalu,2910,3070,3280,3100,2990,3180,3030,3130,3140,3390,3450
180,Uganda,1350,1420,1500,1550,1590,1680,1690,1700,1720,1750,1770
181,Ukraine,7870,8520,8770,7510,7820,8280,8320,8340,8240,7470,7680
182,United Arab Emirates,87100,77200,69400,58800,55400,56600,57900,60400,62900,65800,67000
183,United Kingdom,37800,38500,38100,36200,36500,36800,37100,37600,38400,39000,39400
184,United States,50400,50900,50400,48600,49500,49900,50600,51200,52100,53200,53600
185,Uruguay,13500,14400,15400,16000,17200,18000,18600,19400,19900,19900,20200
186,Uzbekistan,3270,3530,3790,4020,4240,4470,4770,5070,5340,5640,5880
187,Vanuatu,2760,2840,2950,2980,2950,2910,2880,2850,2840,2740,2780
188,Venezuela,16400,17600,18200,17400,16900,17300,18000,18000,17100,15600,15200
189,Vietnam,3630,3850,4030,4210,4430,4660,4860,5070,5310,5610,5900
190,Yemen,4270,4290,4320,4360,4570,3880,3860,3940,3830,3110,2620
191,Zambia,2650,2800,2930,3120,3340,3420,3570,3630,3690,3680,3700
192,Zimbabwe,1890,1810,1480,1630,1930,2170,2490,2490,2510,2510,2490

In [215]:
income_last_10 = income_last_10.melt(id_vars=['country'], var_name='year', value_name='income_per_person')
income_last_10

          country  year  income_per_person
0     Afghanistan  2006               1120
1         Albania  2006               7910
2         Algeria  2006              12400
3         Andorra  2006              42700
4          Angola  2006               5500
...           ...   ...                ...
2118    Venezuela  2016              15200
2119      Vietnam  2016               5900
2120        Yemen  2016               2620
2121       Zambia  2016               3700
2122     Zimbabwe  2016               2490

[2123 rows x 3 columns]

In [217]:
income_last_10.sort_values(['country', 'year'], inplace=True)
income_last_10

          country  year  income_per_person
0     Afghanistan  2006               1120
193   Afghanistan  2007               1250
386   Afghanistan  2008               1270
579   Afghanistan  2009               1500
772   Afghanistan  2010               1670
...           ...   ...                ...
1350     Zimbabwe  2012               2490
1543     Zimbabwe  2013               2490
1736     Zimbabwe  2014               2510
1929     Zimbabwe  2015               2510
2122     Zimbabwe  2016               2490

[2123 rows x 3 columns]

In [218]:
income_last_10.to_csv('income_last_10.csv', index=False)

In [219]:
invest = pd.read_csv('investments_percent_of_gdp.csv')
invest

,country,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,16.10,16.60,19.10,14.20,13.90,11.30,8.41,5.18,6.47,...,18.90,17.90,17.90,16.60,16.80,17.20,18.10,19.40,17.70,NaN
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.80,34.60,30.30,31.40,28.30,28.40,24.60,24.40,24.80,25.20
2,Algeria,42.20,47.20,35.40,28.90,21.80,22.60,17.30,23.40,27.90,...,37.30,46.90,41.40,38.10,39.20,43.40,45.60,50.70,50.70,47.80
3,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.20,15.20,14.40,12.90,15.10,14.70,15.30,9.55,8.40,7.82
4,Argentina,23.50,27.80,21.70,18.30,21.50,22.40,20.50,21.20,21.70,...,19.60,16.10,17.70,18.40,16.50,17.30,17.30,17.10,17.00,19.10
5,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40.90,34.70,32.90,27.30,25.30,22.30,20.90,20.70,18.00,19.00
6,Australia,31.60,33.20,28.50,30.90,30.70,33.60,32.70,33.00,33.00,...,28.60,27.30,26.80,26.40,27.60,27.80,26.70,26.10,25.30,24.20
7,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.50,22.80,22.60,24.10,24.00,23.70,23.50,23.60,24.10,25.10
8,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.70,18.90,18.10,20.30,21.70,24.50,25.70,27.90,24.90,24.10
9,Bahamas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.40,28.00,28.00,30.10,31.30,28.70,32.20,24.70,24.70,27.00
10,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.20,26.10,27.30,22.40,28.10,25.90,26.80,26.50,29.60,NaN
11,Bangladesh,6.89,7.73,12.00,9.86,12.00,11.50,9.02,10.70,14.20,...,26.20,26.20,26.20,27.40,28.30,28.40,28.60,28.90,29.70,30.50
12,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.10,17.10,16.00,17.00,15.90,16.70,16.70,17.30,17.10,17.80
13,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.60,37.30,40.70,37.20,35.10,38.80,34.80,29.00,26.50,26.20
14,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.70,21.70,22.70,24.00,23.20,22.20,23.30,23.60,24.00,24.60
15,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.60,19.10,13.20,17.00,16.00,18.30,21.30,22.50,22.10,19.00
16,Benin,11.40,11.00,11.10,11.60,9.73,8.78,8.78,11.80,12.40,...,20.40,21.90,23.10,24.10,22.60,27.80,28.60,26.00,24.60,28.60
17,Bhutan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42.90,45.70,61.70,67.70,67.90,46.00,51.70,54.00,55.60,47.20
18,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.60,17.00,17.00,19.80,17.70,19.00,21.00,20.30,21.10,22.20
19,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.10,19.80,16.30,18.70,19.20,18.20,19.10,18.70,19.60,20.50
20,Botswana,6.02,7.40,8.80,9.81,12.30,13.30,21.80,25.40,30.70,...,36.20,38.90,41.40,37.80,38.10,29.40,27.90,32.10,24.30,NaN
21,Brazil,19.70,21.40,19.60,19.30,18.60,20.00,19.90,16.90,18.90,...,21.60,18.80,21.80,21.80,21.40,21.70,20.50,17.40,15.40,15.50
22,Brunei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.70,17.60,23.70,26.00,32.90,39.60,27.40,35.20,34.60,34.80
23,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.00,28.60,22.60,21.50,21.90,21.30,21.40,21.20,19.10,20.90
24,Burkina Faso,8.52,8.65,8.71,8.80,9.64,8.71,7.97,8.02,8.27,...,25.40,24.90,26.90,28.00,32.50,32.50,25.90,24.30,23.20,25.50
25,Burundi,6.25,6.90,7.38,6.02,5.37,5.77,6.77,6.85,8.19,...,26.70,23.20,30.50,27.60,28.40,28.70,27.80,16.60,16.90,NaN
26,Cambodia,20.20,17.80,18.20,17.60,15.70,13.50,18.10,14.80,14.20,...,18.60,21.40,17.40,17.10,18.50,20.00,22.10,22.50,22.70,22.90
27,Cameroon,NaN,NaN,NaN,NaN,NaN,12.50,13.30,13.80,13.40,...,24.10,23.70,23.20,24.10,22.80,23.10,24.10,22.40,22.20,21.60
28,Canada,NaN,NaN,NaN,NaN,NaN,25.70,26.40,23.60,22.80,...,24.10,22.00,23.50,24.20,24.90,25.00,24.90,24.10,23.20,23.70
29,Cape Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.50,43.80,47.60,47.50,37.20,31.60,37.00,30.20,36.10,37.30
30,Central African Republic,19.60,21.20,23.30,21.80,22.10,21.40,21.10,21.80,16.20,...,12.70,13.20,14.30,15.00,14.80,8.69,10.20,13.90,13.60,17.70
31,Chad,13.60,14.80,11.70,15.10,15.00,11.00,13.20,15.70,15.00,...,21.90,30.20,34.50,28.50,31.10,29.30,33.80,28.40,26.20,21.40
32,Chile,14.10,15.50,12.90,15.40,14.70,15.40,16.70,16.60,16.90,...,26.80,21.10,23.10,24.60,26.40,25.60,23.20,23.80,22.20,22.10
33,China,39.10,22.30,15.30,21.30,23.80,26.60,30.20,23.70,24.80,...,43.30,46.40,47.60,47.70,47.20,47.40,47.00,45.40,44.30,43.60
34,Colombia,20.20,20.40,18.10,17.60,17.50,17.70,20.40,18.50,21.20,...,23.50,22.40,22.10,23.90,23.90,24.30,26.30,26.70,24.70,23.40
35,Comoros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.80,16.80,14.70,15.60,17.70,21.80,27.40,18.40,20.90,21.20
36,"Congo, Dem. Rep.",6.93,7.14,3.96,18.10,18.50,16.90,8.33,12.00,11.20,...,10.90,14.60,28.80,24.90,14.30,21.80,23.20,19.60,17.40,20.80
37,"Congo, Rep.",53.20,64.70,36.30,22.70,20.30,22.40,30.30,31.50,29.60,...,18.30,22.50,20.50,25.30,26.00,30.90,41.30,40.90,50.40,26.60
38,Costa Rica,17.50,18.90,19.50,18.80,16.00,19.50,19.10,19.40,18.00,...,24.90,18.40,19.70,19.90,20.50,19.00,18.80,18.40,17.90,18.00
39,Cote d'Ivoire,16.70,19.80,13.90,17.80,21.80,21.90,21.80,19.80,17.80,...,12.10,8.70,13.40,4.70,15.10,20.70,19.80,20.10,20.70,22.60
40,Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.40,25.00,21.40,20.60,19.20,19.30,18.80,20.00,20.20,20.50
41,Cuba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.80,10.90,10.10,8.47,8.58,9.39,7.61,9.37,NaN,NaN
42,Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28.90,22.90,23.80,18.80,16.10,13.20,12.30,14.20,16.80,20.40
43,Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.10,26.50,27.10,27.00,26.20,24.70,25.90,28.00,26.30,26.30
44,Denmark,NaN,NaN,NaN,NaN,NaN,NaN,25.40,25.00,24.50,...,24.00,19.10,18.10,19.10,19.50,19.70,20.10,20.00,21.00,21.00
45,Djibouti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,29.80,33.80,44.70,28.80,50.40
46,Dominican Republic,12.60,8.87,11.90,16.00,18.30,9.77,15.90,15.50,15.40,...,30.00,23.60,26.40,25.00,24.30,22.70,23.00,22.60,21.90,21.80
47,Ecuador,12.70,12.80,11.60,11.80,11.60,24.40,22.40,22.90,18.40,...,26.40,25.60,28.00,28.10,27.80,28.50,28.30,26.90,25.20,25.40
48,Egypt,NaN,NaN,NaN,NaN,NaN,17.70,16.80,14.40,12.60,...,22.40,19.20,19.50,17.10,16.00,14.20,13.60,14.30,15.00,15.30
49,El Salvador,NaN,NaN,NaN,NaN,NaN,15.20,16.60,14.80,11.50,...,20.20,14.10,16.70,17.80,17.80,17.20,16.40,15.60,15.10,16.90
50,Equatorial Guinea,NaN,NaN,16.50,17.40,18.90,18.60,18.40,20.40,20.80,...,27.50,39.40,38.10,32.00,41.10,30.30,28.70,24.70,16.60,12.00
51,Eritrea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.70,9.26,9.30,10.00,NaN,NaN,NaN,NaN,NaN,NaN
52,Estonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.70,20.70,21.30,25.10,29.10,26.90,27.10,24.90,24.20,25.40
53,Ethiopia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,0.00,0.00,32.10,37.10,34.10,38.00,40.70,38.00,39.00
54,Fiji,19.70,19.70,15.70,17.10,19.90,19.80,20.60,20.00,25.90,...,24.90,NaN,NaN,21.00,17.30,27.60,19.00,17.90,20.00,NaN
55,Finland,NaN,NaN,NaN,NaN,NaN,29.60,28.10,25.40,25.40,...,25.10,21.20,21.60,23.50,22.50,21.40,20.90,20.90,21.90,22.80
56,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.10,21.30,21.90,23.20,22.60,22.30,22.70,22.70,22.70,23.50
57,Gabon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.10,28.00,29.70,26.60,27.00,29.20,35.10,29.20,27.90,28.80
58,Gambia,NaN,NaN,NaN,NaN,NaN,NaN,8.18,9.19,10.60,...,15.90,19.60,21.30,18.90,27.80,20.00,20.90,19.70,18.70,19.20
59,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.00,13.00,21.60,26.20,28.90,24.80,29.80,31.50,32.70,31.90
60,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.90,18.10,19.60,21.10,19.30,19.50,19.50,19.10,19.20,19.80
61,Ghana,24.40,20.10,17.10,18.70,19.50,17.90,12.80,10.30,11.10,...,16.50,16.40,13.10,12.80,17.00,13.30,18.80,16.70,14.50,16.10
62,Greece,NaN,NaN,NaN,NaN,NaN,53.30,9.72,24.30,2.39,...,24.50,18.30,17.00,15.10,12.80,11.60,11.90,9.82,10.60,11.70
63,Guatemala,10.30,8.92,8.78,10.60,12.80,13.30,10.80,12.90,15.10,...,16.40,13.10,13.90,15.20,15.00,14.00,13.70,13.60,12.90,12.10
64,Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.20,21.30,20.30,24.10,26.00,23.50,23.40,23.50,51.80,36.10
65,Guinea-Bissau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.80,10.80,10.80,9.93,6.70,7.22,11.40,8.09,7.82,10.50
66,Guyana,28.30,24.00,16.60,16.90,16.10,22.20,23.90,25.80,22.30,...,23.90,26.20,25.20,23.90,24.80,18.60,28.70,32.30,29.60,30.10
67,Haiti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28.80,27.50,25.40,27.90,35.60,36.70,38.20,41.10,38.70,43.40
68,Honduras,13.90,12.20,14.90,16.00,14.60,14.60,16.00,19.70,18.50,...,36.10,20.60,21.90,26.00,24.60,21.80,22.20,25.10,23.30,23.80
69,Hungary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.70,20.30,20.70,20.50,19.50,21.00,23.30,21.80,19.80,22.50
70,Iceland,NaN,NaN,NaN,NaN,NaN,27.90,29.50,33.00,33.50,...,25.80,14.80,13.80,15.40,16.00,15.40,17.30,19.10,21.50,22.20
71,India,15.90,15.00,16.70,15.90,16.10,18.10,18.60,15.90,14.60,...,38.20,40.70,40.70,39.60,38.30,34.00,34.30,31.80,30.30,30.70
72,Indonesia,7.87,95.30,5.60,8.20,12.10,6.69,4.53,8.01,8.80,...,27.80,31.00,32.90,33.00,35.10,33.80,34.60,34.10,33.80,33.40
73,Iran,25.10,25.20,24.40,19.20,26.60,31.90,34.20,34.10,41.40,...,41.80,40.90,40.30,36.90,40.30,38.70,39.90,34.00,33.20,34.20
74,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.20,11.30,15.90,15.50,13.40,26.90,25.70,24.40,20.60,17.40
75,Ireland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.60,20.20,17.30,17.20,20.20,18.80,22.40,21.20,32.70,24.20
76,Israel,19.10,20.50,22.80,21.10,23.50,26.10,21.10,16.90,23.30,...,20.00,18.30,18.40,20.40,21.20,20.00,20.20,19.80,20.50,NaN
77,Italy,NaN,NaN,NaN,NaN,NaN,23.10,22.60,23.50,24.10,...,21.80,19.40,20.50,20.50,17.90,17.00,17.00,17.30,17.10,17.20
78,Jamaica,29.70,28.30,26.70,24.20,26.90,26.50,28.00,29.30,34.90,...,24.40,21.10,20.20,21.40,19.90,21.30,22.50,21.30,21.30,21.80
79,Japan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.50,21.30,21.30,22.10,22.70,23.20,23.90,24.00,23.60,NaN
80,Jordan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.90,26.30,24.00,25.50,26.90,28.10,28.00,24.10,22.20,20.60
81,Kazakhstan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.50,29.40,25.40,23.00,25.20,24.60,25.80,27.90,27.80,NaN
82,Kenya,NaN,NaN,NaN,NaN,13.10,14.40,18.60,20.20,20.00,...,19.60,19.30,20.80,21.70,21.50,20.10,22.40,21.50,17.30,19.30
83,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Kuwait,NaN,NaN,NaN,NaN,NaN,15.80,17.70,21.30,18.00,...,17.60,18.00,17.70,13.50,12.80,14.40,16.30,25.40,27.00,NaN
85,Kyrgyz Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28.90,27.30,27.40,25.50,35.00,33.90,36.80,34.70,33.90,32.20
86,Lao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.70,33.90,27.50,28.10,32.50,30.60,29.80,31.60,29.00,29.00
87,Latvia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.10,22.00,19.30,25.20,26.20,24.30,22.70,22.20,19.60,21.50
88,Lebanon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28.20,27.10,25.20,26.80,24.30,27.70,24.20,21.40,24.80,21.80
89,Lesotho,2.02,3.92,7.02,8.63,9.70,11.50,10.10,11.60,12.30,...,25.70,27.70,28.40,22.70,32.00,29.70,31.40,28.80,28.30,NaN
90,Liberia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.50,19.50,19.50,19.50,19.50,19.50,19.50,20.20,20.10,NaN
91,Libya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,Lithuania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.90,12.40,18.00,21.70,19.40,19.50,19.00,20.60,17.20,17.50
93,Luxembourg,NaN,NaN,NaN,NaN,NaN,30.30,29.30,35.20,30.80,...,20.70,16.20,17.90,19.40,19.40,19.00,18.80,18.10,17.90,17.30
94,Madagascar,6.96,5.84,5.04,6.76,7.07,6.50,8.53,9.26,10.30,...,40.30,34.80,20.80,17.60,17.60,15.90,15.60,13.10,14.80,15.20
95,Malawi,10.30,12.80,8.33,9.83,7.69,14.00,17.40,13.50,16.10,...,23.20,24.50,22.80,12.40,12.00,12.70,12.00,12.20,10.80,13.40
96,Malaysia,17.50,20.50,23.90,19.70,19.50,19.20,19.10,20.20,20.10,...,21.50,17.80,23.40,23.20,25.70,25.90,25.00,25.10,25.90,25.50
97,Mali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.40,17.10,...,24.20,22.00,24.00,19.70,17.20,17.80,17.60,17.40,17.40,19.90
98,Malta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.70,20.80,23.60,19.40,18.00,19.00,17.70,23.90,23.10,NaN
99,Marshall Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.40,32.10,36.70,21.70,4.35,20.90,17.20,16.00,NaN,NaN
100,Mauritania,22.60,35.40,43.20,26.30,11.70,10.10,9.97,15.60,20.00,...,41.70,34.90,39.20,43.40,58.80,56.00,52.20,54.80,47.70,56.80
101,Mauritius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.30,23.80,27.10,23.90,24.40,22.00,19.70,18.10,17.90,16.90
102,Mexico,18.40,17.60,16.50,18.40,18.90,20.30,19.50,20.20,19.40,...,24.10,22.90,22.80,23.30,23.90,22.50,21.90,23.30,23.70,23.10
103,"Micronesia, Fed. Sts.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39.20,23.10,23.50,24.20,23.60,24.70,26.10,22.70,22.30,23.30
105,Mongolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43.60,34.40,42.10,58.20,55.90,53.30,35.20,26.40,29.40,36.20
106,Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.20,26.90,21.80,19.30,20.60,19.60,20.20,20.10,26.10,29.30
107,Morocco,10.20,9.70,11.40,12.00,10.50,10.60,10.10,13.30,12.60,...,39.10,35.00,34.10,35.80,35.00,34.70,32.20,30.20,33.10,33.20
108,Mozambique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.30,14.70,18.30,25.70,47.40,54.50,55.40,45.30,38.30,35.60
109,Myanmar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.60,18.90,23.20,29.20,30.90,31.80,35.40,34.90,32.90,NaN
110,Namibia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.80,26.50,24.10,22.40,26.70,25.10,33.60,33.80,23.70,17.60
111,Nepal,NaN,NaN,NaN,NaN,NaN,6.44,4.83,4.99,5.69,...,30.30,31.70,38.30,38.00,34.50,37.30,41.20,39.10,33.70,42.50
112,Netherlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.40,20.90,20.40,20.50,19.20,18.20,18.50,19.90,20.10,20.20
113,New Zealand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.70,19.70,20.10,20.40,20.90,22.00,22.90,23.40,24.40,NaN
114,Nicaragua,14.90,14.80,17.20,17.40,19.60,20.90,23.00,21.00,17.70,...,33.60,23.20,24.80,31.00,31.00,30.90,28.90,32.70,30.70,29.00
115,Niger,6.70,6.91,9.88,12.30,10.80,7.97,7.84,8.67,9.72,...,32.10,34.70,40.00,38.40,36.20,36.20,37.40,40.00,33.90,33.70
116,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.33,12.10,17.30,16.20,14.90,14.90,15.80,15.50,15.30,NaN
117,North Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.90,25.70,24.50,26.90,28.90,28.80,30.30,30.40,32.60,31.60
118,Norway,NaN,NaN,NaN,NaN,NaN,31.60,32.20,32.40,28.00,...,26.10,24.70,25.40,25.90,26.50,27.90,28.10,27.60,29.30,28.80
119,Oman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.20,12.60,...,36.50,28.20,25.40,23.80,27.80,29.80,24.70,36.40,NaN,NaN
120,Pakistan,11.60,16.90,18.20,20.90,20.50,21.50,16.00,16.70,18.00,...,19.20,17.50,15.80,14.10,15.10,15.00,14.60,15.70,15.70,16.10
121,Palau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.50,18.80,21.90,24.00,22.10,19.40,28.20,21.10,25.20,NaN
122,Palestine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.60,20.70,21.60,17.80,21.10,21.70,19.00,21.10,21.10,22.80
123,Panama,21.30,24.90,25.60,25.70,22.20,22.90,28.60,27.50,29.10,...,42.30,31.40,38.20,38.60,43.70,44.00,44.30,42.60,43.80,NaN
124,Papua New Guinea,13.40,13.10,13.20,16.10,19.10,21.60,22.40,21.90,21.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Paraguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.40,13.80,16.20,17.10,15.10,15.40,16.30,16.80,18.00,19.50
126,Peru,46.20,45.20,45.20,40.80,38.30,38.00,39.80,38.80,28.70,...,26.20,20.00,23.80,24.20,24.60,25.60,24.60,24.20,22.10,20.90
127,Philippines,18.10,20.30,20.10,22.00,23.80,23.40,22.20,23.50,22.60,...,19.30,16.60,20.50,20.50,18.20,20.00,20.60,21.20,24.30,25.00
128,Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.70,20.60,21.30,22.40,21.00,19.00,20.40,20.50,19.60,20.00
129,Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.60,20.80,21.10,18.60,15.70,14.60,15.30,15.80,15.50,16.30
130,Qatar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.10,43.00,31.30,29.00,27.10,27.80,31.80,38.20,45.20,NaN
131,Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.20,26.60,27.10,28.00,26.80,25.60,24.70,25.20,24.00,24.40
132,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.50,18.90,22.60,24.40,24.50,23.10,22.20,21.90,22.80,23.90
133,Rwanda,6.05,6.56,8.00,7.81,8.31,9.81,9.66,7.31,8.19,...,24.00,23.40,23.00,23.20,25.70,26.50,25.30,26.40,25.90,23.40
134,Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.60,...,27.30,31.70,30.90,27.00,26.50,26.50,28.80,35.10,30.90,28.20
135,Senegal,3.94,4.45,3.65,4.90,5.11,5.10,6.54,9.84,9.62,...,31.30,22.10,22.10,25.60,29.20,27.40,24.40,25.10,24.90,28.50
136,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.30,19.40,18.50,20.10,21.00,17.60,17.50,18.90,19.10,21.00
137,Seychelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.90,27.30,36.60,35.00,40.00,40.30,39.50,35.30,NaN,NaN
138,Sierra Leone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.11,9.99,31.10,42.00,27.50,13.80,13.70,15.50,20.10,NaN
139,Singapore,11.30,11.50,15.50,17.30,19.80,21.70,21.70,21.90,24.60,...,30.50,27.80,28.20,27.10,29.90,30.70,30.20,27.10,27.00,27.60
140,Slovak Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28.70,21.10,24.00,25.00,20.90,21.00,22.00,24.20,22.60,22.40
141,Slovenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.70,23.40,22.20,21.70,18.70,19.50,19.60,19.40,18.70,19.30
142,Solomon Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Somalia,9.67,9.63,9.68,9.61,9.98,11.20,11.50,12.00,12.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,South Africa,21.90,20.90,19.80,24.00,25.30,27.30,24.80,27.40,25.40,...,23.20,20.70,19.50,19.70,20.00,21.20,20.50,21.00,19.40,18.60
145,South Korea,10.50,12.70,14.10,18.80,15.40,14.80,21.70,22.20,27.10,...,33.00,28.50,32.00,33.00,31.00,29.10,29.30,28.90,29.30,31.10
146,South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.49,10.70,12.80,20.60,14.50,17.30,NaN
147,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.60,24.60,23.50,21.90,20.00,18.70,19.50,20.40,20.50,21.10
148,Sri Lanka,14.20,17.30,15.30,17.00,14.40,12.50,14.30,15.20,15.90,...,27.60,24.40,30.40,33.40,39.10,33.20,32.30,31.20,35.00,36.50
149,Sudan,10.70,14.60,15.00,13.40,13.30,NaN,NaN,NaN,NaN,...,24.60,24.50,23.00,21.60,19.10,19.50,16.40,16.60,19.60,18.90
150,Suriname,36.80,35.60,35.70,36.80,58.40,49.30,29.20,28.00,23.50,...,45.50,47.10,37.50,53.20,57.80,62.90,70.70,67.40,66.00,56.50
151,Swaziland,19.20,23.40,31.70,34.90,37.90,28.70,26.60,23.40,19.60,...,15.70,15.40,14.50,12.90,12.30,12.10,12.30,11.40,12.40,NaN
152,Sweden,NaN,NaN,NaN,NaN,NaN,28.20,26.70,25.70,24.90,...,24.50,20.90,22.90,23.80,22.60,22.50,23.40,24.30,24.70,25.70
153,Switzerland,NaN,NaN,NaN,NaN,NaN,33.80,32.50,32.10,31.00,...,25.30,26.20,23.90,26.70,24.40,22.50,23.20,23.10,23.10,23.30
154,Syria,13.70,14.40,16.30,12.40,11.70,10.30,12.50,12.30,13.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,Tajikistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.50,24.80,23.80,29.20,23.30,24.70,26.20,28.90,31.10,NaN
156,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.10,25.10,27.30,33.20,28.50,30.30,30.10,27.20,24.80,NaN
157,Thailand,14.50,14.00,17.00,19.80,18.50,18.60,21.80,21.90,23.30,...,28.20,20.60,25.40,26.80,28.00,27.50,23.90,22.10,21.70,NaN
158,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.62,11.10,9.42,12.90,10.50,10.30,15.40,18.90,26.10,16.20
159,Togo,10.80,8.06,10.20,12.80,20.10,22.40,16.40,12.60,11.00,...,17.30,18.00,18.90,18.30,24.20,24.60,23.10,20.70,22.90,26.40
160,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.80,24.50,30.10,36.10,33.40,NaN,NaN,NaN,NaN,NaN
161,Tunisia,NaN,NaN,NaN,NaN,NaN,27.90,25.30,25.20,22.90,...,26.00,25.10,26.60,23.50,24.90,23.20,23.50,20.30,19.70,NaN
162,Turkey,9.99,9.97,10.70,11.70,10.90,11.30,12.80,12.60,13.40,...,28.90,23.00,27.00,31.30,28.30,29.80,29.00,28.40,28.20,30.90
163,Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.70,46.60,51.90,51.90,47.20,NaN,NaN,NaN,NaN,NaN
164,Uganda,11.00,10.20,11.10,12.80,12.10,11.20,11.50,13.50,13.10,...,23.00,25.00,25.60,27.50,27.30,28.40,27.30,24.60,25.50,24.00
165,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.90,17.10,20.90,22.40,21.70,18.50,13.40,15.90,21.50,20.70
166,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.10,31.60,27.10,23.20,21.90,19.30,22.20,25.70,26.00,24.80
167,United Kingdom,NaN,NaN,NaN,NaN,NaN,20.30,19.80,20.50,21.20,...,17.00,14.40,15.70,15.60,15.80,16.40,17.10,17.00,17.00,17.00

In [220]:
len(invest.columns)

59

In [224]:
invest_last_10 = invest.iloc[:, np.r_[:1, 47:58]]
invest_last_10

,country,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Afghanistan,23.40,19.90,18.90,17.90,17.90,16.60,16.80,17.20,18.10,19.40,17.70
1,Albania,39.00,38.70,35.80,34.60,30.30,31.40,28.30,28.40,24.60,24.40,24.80
2,Algeria,30.20,34.50,37.30,46.90,41.40,38.10,39.20,43.40,45.60,50.70,50.70
3,Angola,15.40,13.50,16.20,15.20,14.40,12.90,15.10,14.70,15.30,9.55,8.40
4,Argentina,18.70,20.10,19.60,16.10,17.70,18.40,16.50,17.30,17.30,17.10,17.00
5,Armenia,35.90,37.80,40.90,34.70,32.90,27.30,25.30,22.30,20.90,20.70,18.00
6,Australia,27.60,27.50,28.60,27.30,26.80,26.40,27.60,27.80,26.70,26.10,25.30
7,Austria,23.60,24.60,24.50,22.80,22.60,24.10,24.00,23.70,23.50,23.60,24.10
8,Azerbaijan,29.90,21.50,18.70,18.90,18.10,20.30,21.70,24.50,25.70,27.90,24.90
9,Bahamas,33.50,30.50,29.40,28.00,28.00,30.10,31.30,28.70,32.20,24.70,24.70
10,Bahrain,30.40,34.70,35.20,26.10,27.30,22.40,28.10,25.90,26.80,26.50,29.60
11,Bangladesh,26.10,26.20,26.20,26.20,26.20,27.40,28.30,28.40,28.60,28.90,29.70
12,Barbados,21.10,19.60,19.10,17.10,16.00,17.00,15.90,16.70,16.70,17.30,17.10
13,Belarus,32.20,34.10,37.60,37.30,40.70,37.20,35.10,38.80,34.80,29.00,26.50
14,Belgium,23.90,24.40,25.70,21.70,22.70,24.00,23.20,22.20,23.30,23.60,24.00
15,Belize,19.30,19.60,25.60,19.10,13.20,17.00,16.00,18.30,21.30,22.50,22.10
16,Benin,19.00,24.10,20.40,21.90,23.10,24.10,22.60,27.80,28.60,26.00,24.60
17,Bhutan,46.50,29.30,42.90,45.70,61.70,67.70,67.90,46.00,51.70,54.00,55.60
18,Bolivia,13.90,15.20,17.60,17.00,17.00,19.80,17.70,19.00,21.00,20.30,21.10
19,Bosnia and Herzegovina,21.60,25.40,27.10,19.80,16.30,18.70,19.20,18.20,19.10,18.70,19.60
20,Botswana,25.90,30.80,36.20,38.90,41.40,37.80,38.10,29.40,27.90,32.10,24.30
21,Brazil,17.80,19.80,21.60,18.80,21.80,21.80,21.40,21.70,20.50,17.40,15.40
22,Brunei,10.40,13.00,13.70,17.60,23.70,26.00,32.90,39.60,27.40,35.20,34.60
23,Bulgaria,32.30,33.60,37.00,28.60,22.60,21.50,21.90,21.30,21.40,21.20,19.10
24,Burkina Faso,20.70,22.20,25.40,24.90,26.90,28.00,32.50,32.50,25.90,24.30,23.20
25,Burundi,22.00,23.60,26.70,23.20,30.50,27.60,28.40,28.70,27.80,16.60,16.90
26,Cambodia,22.50,21.20,18.60,21.40,17.40,17.10,18.50,20.00,22.10,22.50,22.70
27,Cameroon,20.90,20.80,24.10,23.70,23.20,24.10,22.80,23.10,24.10,22.40,22.20
28,Canada,23.70,24.00,24.10,22.00,23.50,24.20,24.90,25.00,24.90,24.10,23.20
29,Cape Verde,NaN,49.80,48.50,43.80,47.60,47.50,37.20,31.60,37.00,30.20,36.10
30,Central African Republic,10.20,10.70,12.70,13.20,14.30,15.00,14.80,8.69,10.20,13.90,13.60
31,Chad,22.20,22.30,21.90,30.20,34.50,28.50,31.10,29.30,33.80,28.40,26.20
32,Chile,20.80,20.80,26.80,21.10,23.10,24.60,26.40,25.60,23.20,23.80,22.20
33,China,40.90,41.50,43.30,46.40,47.60,47.70,47.20,47.40,47.00,45.40,44.30
34,Colombia,22.40,23.00,23.50,22.40,22.10,23.90,23.90,24.30,26.30,26.70,24.70
35,Comoros,11.30,11.10,19.80,16.80,14.70,15.60,17.70,21.80,27.40,18.40,20.90
36,"Congo, Dem. Rep.",14.60,13.70,10.90,14.60,28.80,24.90,14.30,21.80,23.20,19.60,17.40
37,"Congo, Rep.",21.60,21.80,18.30,22.50,20.50,25.30,26.00,30.90,41.30,40.90,50.40
38,Costa Rica,21.20,23.50,24.90,18.40,19.70,19.90,20.50,19.00,18.80,18.40,17.90
39,Cote d'Ivoire,10.60,12.70,12.10,8.70,13.40,4.70,15.10,20.70,19.80,20.10,20.70
40,Croatia,29.80,29.70,31.40,25.00,21.40,20.60,19.20,19.30,18.80,20.00,20.20
41,Cuba,11.70,10.20,14.80,10.90,10.10,8.47,8.58,9.39,7.61,9.37,NaN
42,Cyprus,24.60,24.40,28.90,22.90,23.80,18.80,16.10,13.20,12.30,14.20,16.80
43,Czech Republic,30.00,32.10,31.10,26.50,27.10,27.00,26.20,24.70,25.90,28.00,26.30
44,Denmark,24.30,25.30,24.00,19.10,18.10,19.10,19.50,19.70,20.10,20.00,21.00
45,Djibouti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.80,33.80,44.70,28.80
46,Dominican Republic,26.90,28.40,30.00,23.60,26.40,25.00,24.30,22.70,23.00,22.60,21.90
47,Ecuador,22.50,22.70,26.40,25.60,28.00,28.10,27.80,28.50,28.30,26.90,25.20
48,Egypt,18.70,20.90,22.40,19.20,19.50,17.10,16.00,14.20,13.60,14.30,15.00
49,El Salvador,20.10,20.80,20.20,14.10,16.70,17.80,17.80,17.20,16.40,15.60,15.10
50,Equatorial Guinea,26.50,29.60,27.50,39.40,38.10,32.00,41.10,30.30,28.70,24.70,16.60
51,Eritrea,13.70,12.70,12.70,9.26,9.30,10.00,NaN,NaN,NaN,NaN,NaN
52,Estonia,39.30,39.30,30.70,20.70,21.30,25.10,29.10,26.90,27.10,24.90,24.20
53,Ethiopia,0.00,0.00,0.00,0.00,0.00,32.10,37.10,34.10,38.00,40.70,38.00
54,Fiji,22.50,21.10,24.90,NaN,NaN,21.00,17.30,27.60,19.00,17.90,20.00
55,Finland,24.00,25.50,25.10,21.20,21.60,23.50,22.50,21.40,20.90,20.90,21.90
56,France,23.20,24.20,24.10,21.30,21.90,23.20,22.60,22.30,22.70,22.70,22.70
57,Gabon,24.00,24.90,25.10,28.00,29.70,26.60,27.00,29.20,35.10,29.20,27.90
58,Gambia,24.30,19.10,15.90,19.60,21.30,18.90,27.80,20.00,20.90,19.70,18.70
59,Georgia,30.90,32.10,26.00,13.00,21.60,26.20,28.90,24.80,29.80,31.50,32.70
60,Germany,19.80,20.70,20.90,18.10,19.60,21.10,19.30,19.50,19.50,19.10,19.20
61,Ghana,23.00,15.40,16.50,16.40,13.10,12.80,17.00,13.30,18.80,16.70,14.50
62,Greece,26.20,27.10,24.50,18.30,17.00,15.10,12.80,11.60,11.90,9.82,10.60
63,Guatemala,20.80,20.80,16.40,13.10,13.90,15.20,15.00,14.00,13.70,13.60,12.90
64,Guinea,24.60,23.40,26.20,21.30,20.30,24.10,26.00,23.50,23.40,23.50,51.80
65,Guinea-Bissau,9.99,12.50,12.80,10.80,10.80,9.93,6.70,7.22,11.40,8.09,7.82
66,Guyana,28.40,24.70,23.90,26.20,25.20,23.90,24.80,18.60,28.70,32.30,29.60
67,Haiti,29.40,30.50,28.80,27.50,25.40,27.90,35.60,36.70,38.20,41.10,38.70
68,Honduras,28.30,33.70,36.10,20.60,21.90,26.00,24.60,21.80,22.20,25.10,23.30
69,Hungary,25.70,24.20,24.70,20.30,20.70,20.50,19.50,21.00,23.30,21.80,19.80
70,Iceland,36.00,29.80,25.80,14.80,13.80,15.40,16.00,15.40,17.30,19.10,21.50
71,India,39.70,42.50,38.20,40.70,40.70,39.60,38.30,34.00,34.30,31.80,30.30
72,Indonesia,25.40,24.90,27.80,31.00,32.90,33.00,35.10,33.80,34.60,34.10,33.80
73,Iran,38.60,39.70,41.80,40.90,40.30,36.90,40.30,38.70,39.90,34.00,33.20
74,Iraq,18.90,9.34,15.20,11.30,15.90,15.50,13.40,26.90,25.70,24.40,20.60
75,Ireland,31.90,29.20,24.60,20.20,17.30,17.20,20.20,18.80,22.40,21.20,32.70
76,Israel,20.50,21.20,20.00,18.30,18.40,20.40,21.20,20.00,20.20,19.80,20.50
77,Italy,21.90,22.20,21.80,19.40,20.50,20.50,17.90,17.00,17.00,17.30,17.10
78,Jamaica,28.40,26.60,24.40,21.10,20.20,21.40,19.90,21.30,22.50,21.30,21.30
79,Japan,24.70,24.50,24.50,21.30,21.30,22.10,22.70,23.20,23.90,24.00,23.60
80,Jordan,28.30,30.30,29.90,26.30,24.00,25.50,26.90,28.10,28.00,24.10,22.20
81,Kazakhstan,33.90,35.50,27.50,29.40,25.40,23.00,25.20,24.60,25.80,27.90,27.80
82,Kenya,18.60,20.50,19.60,19.30,20.80,21.70,21.50,20.10,22.40,21.50,17.30
83,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Kuwait,16.20,20.50,17.60,18.00,17.70,13.50,12.80,14.40,16.30,25.40,27.00
85,Kyrgyz Republic,24.20,26.60,28.90,27.30,27.40,25.50,35.00,33.90,36.80,34.70,33.90
86,Lao,30.10,32.30,31.70,33.90,27.50,28.10,32.50,30.60,29.80,31.60,29.00
87,Latvia,39.20,41.50,35.10,22.00,19.30,25.20,26.20,24.30,22.70,22.20,19.60
88,Lebanon,20.40,24.10,28.20,27.10,25.20,26.80,24.30,27.70,24.20,21.40,24.80
89,Lesotho,NaN,22.40,25.70,27.70,28.40,22.70,32.00,29.70,31.40,28.80,28.30
90,Liberia,19.50,19.50,19.50,19.50,19.50,19.50,19.50,19.50,19.50,20.20,20.10
91,Libya,21.00,26.10,29.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,Lithuania,26.70,32.10,27.90,12.40,18.00,21.70,19.40,19.50,19.00,20.60,17.20
93,Luxembourg,18.30,19.20,20.70,16.20,17.90,19.40,19.40,19.00,18.80,18.10,17.90
94,Madagascar,25.30,29.60,40.30,34.80,20.80,17.60,17.60,15.90,15.60,13.10,14.80
95,Malawi,20.00,23.10,23.20,24.50,22.80,12.40,12.00,12.70,12.00,12.20,10.80
96,Malaysia,22.70,23.40,21.50,17.80,23.40,23.20,25.70,25.90,25.00,25.10,25.90
97,Mali,21.20,23.90,24.20,22.00,24.00,19.70,17.20,17.80,17.60,17.40,17.40
98,Malta,21.30,21.00,21.70,20.80,23.60,19.40,18.00,19.00,17.70,23.90,23.10
99,Marshall Islands,22.70,18.50,14.40,32.10,36.70,21.70,4.35,20.90,17.20,16.00,NaN
100,Mauritania,30.80,31.80,41.70,34.90,39.20,43.40,58.80,56.00,52.20,54.80,47.70
101,Mauritius,25.60,26.00,25.30,23.80,27.10,23.90,24.40,22.00,19.70,18.10,17.90
102,Mexico,22.80,23.10,24.10,22.90,22.80,23.30,23.90,22.50,21.90,23.30,23.70
103,"Micronesia, Fed. Sts.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,Moldova,32.70,38.10,39.20,23.10,23.50,24.20,23.60,24.70,26.10,22.70,22.30
105,Mongolia,35.90,38.70,43.60,34.40,42.10,58.20,55.90,53.30,35.20,26.40,29.40
106,Montenegro,23.90,34.80,41.20,26.90,21.80,19.30,20.60,19.60,20.20,20.10,26.10
107,Morocco,30.90,33.90,39.10,35.00,34.10,35.80,35.00,34.70,32.20,30.20,33.10
108,Mozambique,18.00,15.10,17.30,14.70,18.30,25.70,47.40,54.50,55.40,45.30,38.30
109,Myanmar,NaN,NaN,15.60,18.90,23.20,29.20,30.90,31.80,35.40,34.90,32.90
110,Namibia,22.30,24.40,27.80,26.50,24.10,22.40,26.70,25.10,33.60,33.80,23.70
111,Nepal,26.90,28.70,30.30,31.70,38.30,38.00,34.50,37.30,41.20,39.10,33.70
112,Netherlands,21.50,22.30,22.40,20.90,20.40,20.50,19.20,18.20,18.50,19.90,20.10
113,New Zealand,23.70,24.80,22.70,19.70,20.10,20.40,20.90,22.00,22.90,23.40,24.40
114,Nicaragua,28.30,31.30,33.60,23.20,24.80,31.00,31.00,30.90,28.90,32.70,30.70
115,Niger,23.60,22.90,32.10,34.70,40.00,38.40,36.20,36.20,37.40,40.00,33.90
116,Nigeria,8.27,9.26,8.33,12.10,17.30,16.20,14.90,14.90,15.80,15.50,15.30
117,North Macedonia,21.40,23.70,27.90,25.70,24.50,26.90,28.90,28.80,30.30,30.40,32.60
118,Norway,24.20,27.30,26.10,24.70,25.40,25.90,26.50,27.90,28.10,27.60,29.30
119,Oman,27.20,34.30,36.50,28.20,25.40,23.80,27.80,29.80,24.70,36.40,NaN
120,Pakistan,19.30,18.80,19.20,17.50,15.80,14.10,15.10,15.00,14.60,15.70,15.70
121,Palau,NaN,29.20,26.50,18.80,21.90,24.00,22.10,19.40,28.20,21.10,25.20
122,Palestine,23.50,21.90,20.60,20.70,21.60,17.80,21.10,21.70,19.00,21.10,21.10
123,Panama,29.40,36.00,42.30,31.40,38.20,38.60,43.70,44.00,44.30,42.60,43.80
124,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Paraguay,17.10,15.80,16.40,13.80,16.20,17.10,15.10,15.40,16.30,16.80,18.00
126,Peru,19.70,22.00,26.20,20.00,23.80,24.20,24.60,25.60,24.60,24.20,22.10
127,Philippines,18.00,17.30,19.30,16.60,20.50,20.50,18.20,20.00,20.60,21.20,24.30
128,Poland,21.70,25.20,24.70,20.60,21.30,22.40,21.00,19.00,20.40,20.50,19.60
129,Portugal,23.20,23.10,23.60,20.80,21.10,18.60,15.70,14.60,15.30,15.80,15.50
130,Qatar,41.90,46.00,41.10,43.00,31.30,29.00,27.10,27.80,31.80,38.20,45.20
131,Romania,27.20,31.10,33.20,26.60,27.10,28.00,26.80,25.60,24.70,25.20,24.00
132,Russia,21.20,24.20,25.50,18.90,22.60,24.40,24.50,23.10,22.20,21.90,22.80
133,Rwanda,16.80,18.90,24.00,23.40,23.00,23.20,25.70,26.50,25.30,26.40,25.90
134,Saudi Arabia,22.20,26.50,27.30,31.70,30.90,27.00,26.50,26.50,28.80,35.10,30.90
135,Senegal,24.70,29.30,31.30,22.10,22.10,25.60,29.20,27.40,24.40,25.10,24.90
136,Serbia,25.00,29.10,30.30,19.40,18.50,20.10,21.00,17.60,17.50,18.90,19.10
137,Seychelles,30.40,29.00,26.90,27.30,36.60,35.00,40.00,40.30,39.50,35.30,NaN
138,Sierra Leone,10.40,9.45,9.11,9.99,31.10,42.00,27.50,13.80,13.70,15.50,20.10
139,Singapore,22.30,23.20,30.50,27.80,28.20,27.10,29.90,30.70,30.20,27.10,27.00
140,Slovak Republic,28.80,28.50,28.70,21.10,24.00,25.00,20.90,21.00,22.00,24.20,22.60
141,Slovenia,30.20,32.90,32.70,23.40,22.20,21.70,18.70,19.50,19.60,19.40,18.70
142,Solomon Islands,14.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Somalia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,South Africa,20.20,21.00,23.20,20.70,19.50,19.70,20.00,21.20,20.50,21.00,19.40
145,South Korea,32.70,32.60,33.00,28.50,32.00,33.00,31.00,29.10,29.30,28.90,29.30
146,South Sudan,NaN,NaN,NaN,NaN,NaN,5.49,10.70,12.80,20.60,14.50,17.30
147,Spain,31.30,31.30,29.60,24.60,23.50,21.90,20.00,18.70,19.50,20.40,20.50
148,Sri Lanka,28.00,28.00,27.60,24.40,30.40,33.40,39.10,33.20,32.30,31.20,35.00
149,Sudan,28.90,27.60,24.60,24.50,23.00,21.60,19.10,19.50,16.40,16.60,19.60
150,Suriname,18.40,42.30,45.50,47.10,37.50,53.20,57.80,62.90,70.70,67.40,66.00
151,Swaziland,16.50,16.00,15.70,15.40,14.50,12.90,12.30,12.10,12.30,11.40,12.40
152,Sweden,23.00,24.60,24.50,20.90,22.90,23.80,22.60,22.50,23.40,24.30,24.70
153,Switzerland,25.20,24.30,25.30,26.20,23.90,26.70,24.40,22.50,23.20,23.10,23.10
154,Syria,18.90,27.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,Tajikistan,16.00,24.60,26.50,24.80,23.80,29.20,23.30,24.70,26.20,28.90,31.10
156,Tanzania,26.00,32.80,32.10,25.10,27.30,33.20,28.50,30.30,30.10,27.20,24.80
157,Thailand,27.00,25.50,28.20,20.60,25.40,26.80,28.00,27.50,23.90,22.10,21.70
158,Timor-Leste,2.07,3.52,4.62,11.10,9.42,12.90,10.50,10.30,15.40,18.90,26.10
159,Togo,16.80,14.60,17.30,18.00,18.90,18.30,24.20,24.60,23.10,20.70,22.90
160,Tonga,21.10,21.70,20.80,24.50,30.10,36.10,33.40,NaN,NaN,NaN,NaN
161,Tunisia,23.40,23.80,26.00,25.10,26.60,23.50,24.90,23.20,23.50,20.30,19.70
162,Turkey,29.60,28.70,28.90,23.00,27.00,31.30,28.30,29.80,29.00,28.40,28.20
163,Turkmenistan,19.50,18.60,31.70,46.60,51.90,51.90,47.20,NaN,NaN,NaN,NaN
164,Uganda,21.10,22.10,23.00,25.00,25.60,27.50,27.30,28.40,27.30,24.60,25.50
165,Ukraine,24.80,26.70,27.90,17.10,20.90,22.40,21.70,18.50,13.40,15.90,21.50
166,United Arab Emirates,19.30,25.10,25.10,31.60,27.10,23.20,21.90,19.30,22.20,25.70,26.00
167,United Kingdom,17.60,18.10,17.00,14.40,15.70,15.60,15.80,16.40,17.10,17.00,17.00
168,United States,23.30,22.40,20.80,17.50,18.40,18.50,19.40,19.80,20.10,20.40,19.70
169,Uruguay,19.50,19.50,23.20,19.60,19.40,20.90,22.90,22.50,21.20,19.70,17.80
170,Uzbekistan,19.10,20.90,24.50,25.40,24.60,22.80,23.30,23.70,24.20,23.70,24.90
171,Vanuatu,28.40,32.30,40.60,39.90,34.70,27.50,23.00,25.90,26.40,NaN,NaN
172,Venezuela,26.90,30.30,26.80,25.80,22.00,23.10,26.60,27.30,24.80,NaN,NaN
173,Vietnam,34.50,39.60,36.50,37.20,35.70,29.80,27.20,26.70,26.80,27.70,26.60
174,Yemen,16.40,17.20,15.40,13.50,11.70,5.50,8.70,8.11,7.83,1.85,1.70
175,Zambia,NaN,NaN,NaN,NaN,29.90,33.60,31.80,34.00,34.00,42.80,38.20
176,Zimbabwe,1.57,7.11,5.13,14.30,22.30,20.30,11.80,11.40,11.80,12.30,12.20

In [226]:
invest_last_10 = invest_last_10.melt(id_vars=['country'], var_name='year', value_name='invest_%_gdp')
invest_last_10

          country  year  invest_%_gdp
0     Afghanistan  2006          23.4
1         Albania  2006          39.0
2         Algeria  2006          30.2
3          Angola  2006          15.4
4       Argentina  2006          18.7
...           ...   ...           ...
1942    Venezuela  2016           NaN
1943      Vietnam  2016          26.6
1944        Yemen  2016           1.7
1945       Zambia  2016          38.2
1946     Zimbabwe  2016          12.2

[1947 rows x 3 columns]

In [227]:
invest_last_10.sort_values(['country', 'year'], inplace=True)
invest_last_10

          country  year  invest_%_gdp
0     Afghanistan  2006          23.4
177   Afghanistan  2007          19.9
354   Afghanistan  2008          18.9
531   Afghanistan  2009          17.9
708   Afghanistan  2010          17.9
...           ...   ...           ...
1238     Zimbabwe  2012          11.8
1415     Zimbabwe  2013          11.4
1592     Zimbabwe  2014          11.8
1769     Zimbabwe  2015          12.3
1946     Zimbabwe  2016          12.2

[1947 rows x 3 columns]

In [228]:
invest_last_10.to_csv('invest_last_10.csv', index=False)

In [306]:
combined_last_10 = demo_last_10.copy()
combined_last_10

          country  year  demox_eiu
0     Afghanistan  2006       30.6
164   Afghanistan  2007       30.4
328   Afghanistan  2008       30.2
492   Afghanistan  2009       27.5
656   Afghanistan  2010       24.8
...           ...   ...        ...
1147     Zimbabwe  2012       26.7
1311     Zimbabwe  2013       26.7
1475     Zimbabwe  2014       27.8
1639     Zimbabwe  2015       30.5
1803     Zimbabwe  2016       30.5

[1804 rows x 3 columns]

In [307]:
combined_last_10 = combined_last_10.merge(income_last_10, left_on=['country', 'year'], right_on=['country', 'year'], how='inner')
combined_last_10

          country  year  demox_eiu  income_per_person
0     Afghanistan  2006       30.6               1120
1     Afghanistan  2007       30.4               1250
2     Afghanistan  2008       30.2               1270
3     Afghanistan  2009       27.5               1500
4     Afghanistan  2010       24.8               1670
...           ...   ...        ...                ...
1799     Zimbabwe  2012       26.7               2490
1800     Zimbabwe  2013       26.7               2490
1801     Zimbabwe  2014       27.8               2510
1802     Zimbabwe  2015       30.5               2510
1803     Zimbabwe  2016       30.5               2490

[1804 rows x 4 columns]

In [308]:
combined_last_10 = combined_last_10.merge(invest_last_10, left_on=['country', 'year'], right_on=['country', 'year'], how='inner')
combined_last_10

          country  year  demox_eiu  income_per_person  invest_%_gdp
0     Afghanistan  2006       30.6               1120          23.4
1     Afghanistan  2007       30.4               1250          19.9
2     Afghanistan  2008       30.2               1270          18.9
3     Afghanistan  2009       27.5               1500          17.9
4     Afghanistan  2010       24.8               1670          17.9
...           ...   ...        ...                ...           ...
1777     Zimbabwe  2012       26.7               2490          11.8
1778     Zimbabwe  2013       26.7               2490          11.4
1779     Zimbabwe  2014       27.8               2510          11.8
1780     Zimbabwe  2015       30.5               2510          12.3
1781     Zimbabwe  2016       30.5               2490          12.2

[1782 rows x 5 columns]

In [270]:
combined_last_10.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1782 entries, 0 to 1781
Data columns (total 5 columns):
country              1782 non-null object
year                 1782 non-null object
demox_eiu            1782 non-null float64
income_per_person    1782 non-null int64
invest_%_gdp         1724 non-null float64
dtypes: float64(2), int64(1), object(2)
memory usage: 83.5+ KB

In [271]:
tax_last_10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1771 entries, 0 to 1770
Data columns (total 3 columns):
country      1771 non-null object
year         1771 non-null object
tax_%_gdp    1437 non-null float64
dtypes: float64(1), object(2)
memory usage: 41.6+ KB

In [272]:
tax_last_10.to_csv('tax_last_10.csv', index=False)

In [285]:
tax_last_10 = pd.read_csv('tax_last_10.csv')

In [292]:
tax_last_10.index = list(tax_last_10.index)

In [284]:
tax_last_10.to_csv('tax_last_10.csv')

In [296]:
tax_last_10.drop('Unnamed: 0', axis=1)

          country  year  tax_%_gdp
0     Afghanistan  2006       6.88
1     Afghanistan  2007       5.23
2     Afghanistan  2008       6.04
3     Afghanistan  2009       8.44
4     Afghanistan  2010       9.12
...           ...   ...        ...
1766     Zimbabwe  2012      21.40
1767     Zimbabwe  2013        NaN
1768     Zimbabwe  2014        NaN
1769     Zimbabwe  2015        NaN
1770     Zimbabwe  2016        NaN

[1771 rows x 3 columns]

In [293]:
tax_last_10.info(), income_last_10.info(), invest_last_10.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1771 entries, 0 to 1770
Data columns (total 4 columns):
Unnamed: 0    1771 non-null int64
country       1771 non-null object
year          1771 non-null int64
tax_%_gdp     1437 non-null float64
dtypes: float64(1), int64(2), object(1)
memory usage: 69.2+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2123 entries, 0 to 2122
Data columns (total 3 columns):
country              2123 non-null object
year                 2123 non-null object
income_per_person    2123 non-null int64
dtypes: int64(1), object(2)
memory usage: 66.3+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1947 entries, 0 to 1946
Data columns (total 3 columns):
country         1947 non-null object
year            1947 non-null object
invest_%_gdp    1832 non-null float64
dtypes: float64(1), object(2)
memory usage: 60.8+ KB

(None, None, None)

In [261]:
combined_last_10.merge(tax_last_10, left_on=['country', 'year'], right_on=['country', 'year'], how='inner')
combined_last_10

Empty DataFrame
Columns: [country, year, demox_eiu, income_per_person, invest_%_gdp, tax_%_gdp]
Index: []

In [263]:
combined_last_10

Empty DataFrame
Columns: [country, year, demox_eiu, income_per_person, invest_%_gdp, tax_%_gdp]
Index: []

In [295]:
tax_last_10 = pd.read_csv('tax_last_10.csv')
tax_last_10
tax_last_10.year = tax_last_10.year.astype(object)
tax_last_10.dtypes

Unnamed: 0      int64
country        object
year           object
tax_%_gdp     float64
dtype: object

In [243]:
combined_last_10.dtypes

country               object
year                  object
demox_eiu            float64
income_per_person      int64
invest_%_gdp         float64
dtype: object

In [244]:
income_last_10.dtypes

country              object
year                 object
income_per_person     int64
dtype: object

In [245]:
gini_last_10.dtypes

country        object
year           object
gini_index    float64
dtype: object

In [246]:
invest_last_10.dtypes

country          object
year             object
invest_%_gdp    float64
dtype: object

In [297]:
tax_last_10.year = tax_last_10.year.astype(object)
tax_last_10

      Unnamed: 0      country  year  tax_%_gdp
0              0  Afghanistan  2006       6.88
1              1  Afghanistan  2007       5.23
2              2  Afghanistan  2008       6.04
3              3  Afghanistan  2009       8.44
4              4  Afghanistan  2010       9.12
...          ...          ...   ...        ...
1766        1766     Zimbabwe  2012      21.40
1767        1767     Zimbabwe  2013        NaN
1768        1768     Zimbabwe  2014        NaN
1769        1769     Zimbabwe  2015        NaN
1770        1770     Zimbabwe  2016        NaN

[1771 rows x 4 columns]

In [299]:
tax_last_10.drop('Unnamed: 0', axis=1, inplace=True)
tax_last_10

          country  year  tax_%_gdp
0     Afghanistan  2006       6.88
1     Afghanistan  2007       5.23
2     Afghanistan  2008       6.04
3     Afghanistan  2009       8.44
4     Afghanistan  2010       9.12
...           ...   ...        ...
1766     Zimbabwe  2012      21.40
1767     Zimbabwe  2013        NaN
1768     Zimbabwe  2014        NaN
1769     Zimbabwe  2015        NaN
1770     Zimbabwe  2016        NaN

[1771 rows x 3 columns]

In [309]:
tax_last_10.index = list(tax_last_10.index)
tax_last_10.info(), combined_last_10.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1771 entries, 0 to 1770
Data columns (total 3 columns):
country      1771 non-null object
year         1771 non-null object
tax_%_gdp    1437 non-null float64
dtypes: float64(1), object(2)
memory usage: 55.3+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1782 entries, 0 to 1781
Data columns (total 5 columns):
country              1782 non-null object
year                 1782 non-null object
demox_eiu            1782 non-null float64
income_per_person    1782 non-null int64
invest_%_gdp         1724 non-null float64
dtypes: float64(2), int64(1), object(2)
memory usage: 83.5+ KB

(None, None)

In [318]:
temp = combined_last_10.merge(tax_last_10, left_on=['country', 'year'], right_on=['country', 'year'])
combined_last_10

          country  year  demox_eiu  income_per_person  invest_%_gdp
0     Afghanistan  2006       30.6               1120          23.4
1     Afghanistan  2007       30.4               1250          19.9
2     Afghanistan  2008       30.2               1270          18.9
3     Afghanistan  2009       27.5               1500          17.9
4     Afghanistan  2010       24.8               1670          17.9
...           ...   ...        ...                ...           ...
1777     Zimbabwe  2012       26.7               2490          11.8
1778     Zimbabwe  2013       26.7               2490          11.4
1779     Zimbabwe  2014       27.8               2510          11.8
1780     Zimbabwe  2015       30.5               2510          12.3
1781     Zimbabwe  2016       30.5               2490          12.2

[1782 rows x 5 columns]

In [325]:
income_last_10.merge(invest_last_10, left_on=['country', 'year'], right_on=['country', 'year'])

          country  year  income_per_person  invest_%_gdp
0     Afghanistan  2006               1120          23.4
1     Afghanistan  2007               1250          19.9
2     Afghanistan  2008               1270          18.9
3     Afghanistan  2009               1500          17.9
4     Afghanistan  2010               1670          17.9
...           ...   ...                ...           ...
1942     Zimbabwe  2012               2490          11.8
1943     Zimbabwe  2013               2490          11.4
1944     Zimbabwe  2014               2510          11.8
1945     Zimbabwe  2015               2510          12.3
1946     Zimbabwe  2016               2490          12.2

[1947 rows x 4 columns]

In [323]:
combined_last_10

          country  year  demox_eiu  income_per_person  invest_%_gdp
0     Afghanistan  2006       30.6               1120          23.4
1     Afghanistan  2007       30.4               1250          19.9
2     Afghanistan  2008       30.2               1270          18.9
3     Afghanistan  2009       27.5               1500          17.9
4     Afghanistan  2010       24.8               1670          17.9
...           ...   ...        ...                ...           ...
1777     Zimbabwe  2012       26.7               2490          11.8
1778     Zimbabwe  2013       26.7               2490          11.4
1779     Zimbabwe  2014       27.8               2510          11.8
1780     Zimbabwe  2015       30.5               2510          12.3
1781     Zimbabwe  2016       30.5               2490          12.2

[1782 rows x 5 columns]

In [328]:
tax = pd.read_csv('tax_revenue_percent_of_gdp.csv')
tax

,country,1972,1973,1974,1975,1976,1977,1978,1979,1980,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.040,8.440,9.120,8.850,7.470,7.080,6.840,7.5500,NaN,NaN
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.000,17.500,16.500,18.300,18.5000,17.6000,NaN
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.300,35.100,34.400,37.200,NaN,NaN,NaN,NaN,NaN,NaN
3,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.000,17.100,16.900,17.300,16.700,15.500,15.600,12.5000,10.3000,NaN
4,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.700,17.300,18.500,17.900,18.500,17.200,16.500,NaN,NaN,NaN
5,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.300,12.400,12.900,12.700,13.000,12.500,12.600,12.3000,12.2000,NaN
6,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.300,16.500,17.100,17.200,17.500,NaN,21.600,20.9000,21.3000,NaN
7,Australia,17.90,17.00,18.10,19.90,20.30,20.60,20.40,19.80,20.40,...,24.300,22.100,20.600,20.400,21.200,22.100,22.000,22.0000,22.3000,NaN
8,Austria,17.90,18.20,18.40,18.00,17.90,18.00,18.80,18.60,18.60,...,26.100,25.200,25.300,25.400,25.900,26.400,26.400,26.8000,25.7000,NaN
9,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.400,14.100,12.200,12.200,12.800,13.400,14.200,15.6000,NaN,NaN
10,Bahamas,NaN,14.50,16.70,16.30,17.20,15.90,16.30,15.30,15.00,...,12.100,11.300,10.900,12.900,11.900,11.400,11.400,12.7000,14.2000,NaN
11,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.240,1.360,1.180,1.110,NaN,1.070,NaN,NaN,NaN,NaN
12,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.660,7.500,7.830,8.690,9.020,8.960,8.640,8.5000,8.7700,NaN
13,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.400,24.900,25.100,25.900,24.200,23.400,24.000,26.1000,NaN,NaN
14,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.400,19.300,16.300,14.500,14.700,13.400,12.700,14.2000,13.8000,NaN
15,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.100,23.600,24.300,24.700,25.700,26.200,26.300,24.7000,23.1000,NaN
16,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.700,22.500,23.600,22.600,22.500,23.300,23.400,NaN,NaN,NaN
17,Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.100,15.000,15.500,14.800,14.400,15.400,NaN,NaN,NaN,NaN
18,Bhutan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.420,9.240,13.100,13.500,14.700,14.400,13.300,13.8000,13.2000,NaN
19,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.300,18.900,19.700,20.300,20.500,19.800,19.800,19.9000,20.0000,NaN
21,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.400,27.300,23.600,23.200,26.600,25.600,25.800,24.7000,20.8000,NaN
22,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.10,...,15.500,14.400,13.600,14.200,13.700,13.400,12.800,12.8000,12.9000,NaN
23,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.200,19.000,18.500,17.700,19.000,19.800,19.600,20.2000,20.0000,NaN
24,Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.900,12.500,12.700,13.700,15.600,16.800,15.400,15.1000,15.8000,NaN
25,Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13.900,14.700,13.700,12.200,NaN,NaN,NaN,NaN
26,Cambodia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.600,9.650,10.000,10.200,11.100,12.100,14.600,14.2000,15.3000,NaN
27,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.400,12.300,11.800,11.800,11.700,11.700,11.800,12.3000,12.2000,12.20
28,Cape Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.300,18.400,NaN,NaN,17.900,NaN,NaN,NaN,NaN,NaN
29,Central African Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.060,9.170,10.100,9.290,NaN,NaN,NaN,NaN,NaN,NaN
30,Chile,16.20,17.40,16.30,20.60,18.40,18.80,18.70,17.90,19.00,...,18.700,14.500,17.400,18.900,19.000,17.400,17.000,17.4000,17.4000,NaN
31,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.100,10.300,10.200,10.300,10.200,9.870,9.670,9.3700,NaN,NaN
32,Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.900,12.600,12.100,14.600,13.300,14.100,15.000,15.1000,13.3000,NaN
33,"Congo, Dem. Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.970,7.890,8.350,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"Congo, Rep.",16.80,15.50,25.00,20.40,NaN,NaN,NaN,NaN,25.40,...,5.950,8.400,7.600,8.860,9.430,NaN,NaN,NaN,NaN,NaN
35,Costa Rica,11.40,12.50,13.60,12.40,12.20,12.30,12.70,11.90,11.60,...,15.300,13.300,13.100,13.400,13.300,13.700,13.400,13.7000,14.0000,NaN
36,Cote d'Ivoire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.100,14.600,14.300,10.900,14.300,14.500,14.000,15.4000,15.2000,NaN
37,Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000,19.200,19.100,18.400,19.500,19.000,19.100,NaN,NaN,NaN
38,Cyprus,NaN,NaN,NaN,13.40,12.10,13.20,13.60,14.20,14.80,...,46.100,23.300,23.200,23.300,23.300,23.400,24.500,24.1000,24.3000,NaN
39,Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.400,13.400,13.400,14.300,14.700,14.900,14.200,14.6000,14.7000,NaN
40,Denmark,29.00,28.90,29.10,26.70,26.50,27.10,28.10,28.60,28.50,...,33.400,33.200,32.700,32.800,33.400,33.800,36.500,33.9000,33.7000,NaN
41,Dominica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.800,24.300,24.600,23.100,23.000,22.400,22.100,NaN,NaN,NaN
42,Dominican Republic,13.90,13.40,14.40,16.10,13.30,12.50,11.30,11.00,10.50,...,14.200,12.600,12.200,12.300,13.000,13.500,13.600,13.3000,13.5000,NaN
43,Egypt,NaN,NaN,NaN,20.90,17.30,25.10,23.00,21.10,NaN,...,15.300,15.700,14.100,14.000,12.400,13.500,12.200,12.5000,NaN,NaN
44,El Salvador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.100,15.000,15.800,15.300,16.200,17.100,16.700,16.9000,17.6000,NaN
45,Equatorial Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.790,12.800,7.590,7.020,8.740,8.520,8.300,11.5000,NaN,NaN
46,Estonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.240,1.370,1.270,1.230,1.270,1.290,1.340,1.4000,1.4300,NaN
47,Ethiopia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.810,6.580,8.160,9.210,9.380,8.760,NaN,NaN,NaN,NaN
48,Fiji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,21.800,23.000,23.200,23.600,24.600,25.5000,NaN,NaN
49,Finland,21.70,22.00,21.30,22.10,24.70,24.20,22.40,21.20,21.40,...,20.500,19.000,18.700,20.100,20.300,20.700,20.800,20.7000,21.0000,NaN
50,France,18.70,17.80,18.90,17.70,18.80,18.20,18.30,18.80,19.30,...,22.000,20.700,22.000,21.800,22.600,23.200,23.200,23.2000,23.1000,NaN
51,Gambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.700,15.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.800,23.100,22.100,23.800,24.100,23.400,23.500,23.8000,23.5000,NaN
53,Germany,10.80,11.00,10.50,10.10,10.20,10.50,10.50,10.40,10.30,...,11.400,11.600,11.100,11.400,11.600,11.600,11.500,11.4000,11.2000,NaN
54,Ghana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Greece,12.90,12.50,12.60,12.70,14.10,14.00,14.30,13.90,13.80,...,20.200,19.800,20.200,22.100,23.600,23.700,24.400,24.9000,26.7000,NaN
56,Grenada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.500,18.200,18.700,19.200,18.700,18.400,19.400,NaN,NaN,NaN
57,Guatemala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.300,10.300,10.400,10.800,10.800,10.900,10.800,10.2000,10.4000,NaN
58,Honduras,10.70,10.80,11.10,11.10,11.70,13.10,12.70,12.80,13.60,...,16.100,14.200,14.400,14.800,14.700,15.100,16.500,17.3000,NaN,NaN
59,Hungary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.300,23.300,22.800,21.100,22.900,22.700,23.000,23.4000,23.4000,NaN
60,Iceland,23.20,23.20,24.10,23.20,22.10,21.10,21.50,22.20,21.50,...,23.200,20.100,20.700,21.200,22.100,22.700,25.300,23.5000,38.5000,NaN
61,India,NaN,NaN,8.29,9.15,9.31,8.71,9.43,9.82,9.15,...,11.100,9.940,10.500,10.200,10.800,11.000,NaN,NaN,NaN,NaN
62,Indonesia,12.40,13.80,16.00,16.60,17.90,17.70,17.90,20.30,21.80,...,13.300,11.100,10.500,11.200,11.400,11.300,10.800,10.8000,10.3000,NaN
63,Iran,8.27,7.55,5.42,8.19,7.56,8.22,8.87,5.99,5.17,...,6.200,7.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.890,1.2300,2.0200,NaN
65,Ireland,21.80,22.10,22.00,21.30,23.60,22.50,22.10,21.90,24.20,...,23.700,22.000,21.800,21.800,22.500,22.800,23.200,18.9000,18.8000,NaN
66,Israel,25.70,24.30,30.60,30.40,33.80,35.10,33.20,37.80,35.90,...,23.800,21.900,22.500,22.700,22.100,23.000,23.300,23.4000,23.4000,NaN
67,Italy,NaN,12.60,13.50,12.80,14.10,15.00,15.70,15.80,17.40,...,21.900,22.400,22.300,22.300,23.600,23.700,23.500,23.4000,23.7000,NaN
68,Jamaica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.700,25.000,24.300,23.400,24.300,24.000,24.100,24.8000,26.1000,NaN
69,Japan,10.50,11.70,11.30,9.35,9.13,9.16,9.25,9.95,10.50,...,8.930,8.370,8.810,9.360,9.680,10.400,11.500,11.4000,11.1000,NaN
70,Jordan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.800,17.000,16.000,15.000,15.300,15.300,NaN,NaN,NaN,NaN
71,Kazakhstan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,15.700,18.300,13.300,16.000,14.200,9.8400,9.9200,NaN
72,Kenya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,16.900,16.3000,15.8000,NaN
73,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16.000,18.100,18.500,17.800,17.800,22.3000,24.5000,NaN
74,Kuwait,37.40,37.20,32.70,NaN,NaN,4.62,7.60,2.18,2.70,...,0.876,0.971,0.979,0.800,0.716,0.777,0.890,1.3800,NaN,NaN
75,Kyrgyz Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,17.600,17.500,16.8000,16.9000,NaN
76,Lao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.100,12.800,13.000,13.100,13.600,13.700,13.800,13.5000,12.9000,NaN
77,Latvia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.800,18.800,19.800,20.000,21.100,22.000,22.400,22.8000,23.9000,NaN
78,Lebanon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.400,16.800,16.900,16.300,15.200,14.300,14.200,13.6000,13.9000,NaN
79,Lesotho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.200,58.400,37.300,34.800,48.000,45.900,45.200,40.6000,34.2000,36.40
80,Liberia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000,NaN,17.300,17.300,20.900,20.300,NaN,NaN,NaN,NaN
81,Lithuania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.930,4.930,4.620,4.490,4.510,4.530,4.590,4.8200,4.9300,NaN
82,Luxembourg,16.10,16.60,17.10,20.00,19.60,22.00,22.90,21.10,21.60,...,24.700,25.100,25.000,24.600,25.700,25.900,25.600,25.0000,25.7000,NaN
83,Madagascar,59.00,56.30,NaN,NaN,NaN,NaN,65.40,62.00,57.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Malawi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,14.500,15.400,15.500,13.600,14.100,15.900,15.2000,15.5000,17.30
85,Malaysia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.700,14.900,13.300,14.800,15.600,15.300,14.800,14.3000,13.8000,NaN
86,Maldives,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.12,...,11.600,9.100,8.850,12.100,NaN,NaN,19.500,NaN,NaN,NaN
87,Mali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.900,13.000,12.900,12.500,13.000,13.000,12.600,14.1000,15.4000,NaN
88,Malta,21.20,22.00,20.70,18.90,17.70,18.40,19.20,NaN,19.70,...,26.100,26.500,26.100,26.100,26.400,26.800,26.900,25.6000,26.2000,NaN
89,Marshall Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.400,18.100,17.100,16.700,15.800,15.900,15.900,17.5000,17.8000,NaN
90,Mauritius,NaN,NaN,NaN,NaN,20.00,19.60,17.70,16.40,18.30,...,17.000,18.100,18.000,18.000,18.600,18.400,18.500,8.9900,18.1000,NaN
91,Mexico,7.61,7.09,8.00,9.18,9.04,9.95,10.70,11.30,12.10,...,10.000,9.680,10.100,10.000,9.770,10.300,10.600,12.8000,13.6000,NaN
92,"Micronesia, Fed. Sts.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.290,4.400,4.670,4.980,4.910,5.490,12.600,5.4400,6.0500,NaN
93,Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.400,17.700,18.200,18.300,18.600,18.400,19.800,19.5000,19.3000,NaN
94,Mongolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.700,16.500,19.600,18.500,15.300,15.700,12.900,11.8000,11.3000,NaN
95,Morocco,14.90,15.60,15.50,19.80,16.60,20.00,19.50,20.00,16.60,...,26.500,23.500,22.800,23.300,NaN,NaN,NaN,NaN,NaN,NaN
96,Mozambique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16.100,18.700,20.400,23.100,25.400,21.9000,20.1000,NaN
97,Myanmar,NaN,9.42,7.61,7.92,8.81,10.50,10.00,10.20,9.61,...,NaN,NaN,NaN,NaN,4.520,5.530,5.840,6.0100,6.4100,5.82
98,Namibia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.100,29.400,25.900,30.000,32.900,31.500,33.600,32.5000,28.5000,NaN
99,Nepal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.400,11.800,13.400,13.300,13.900,15.300,15.900,16.7000,18.7000,21.30
100,Netherlands,NaN,22.80,21.50,22.60,22.60,23.70,23.50,23.40,23.40,...,21.400,21.000,21.300,20.400,19.600,19.900,20.900,21.5000,22.2000,NaN
101,New Zealand,23.80,25.60,28.10,27.70,27.50,29.60,28.10,29.40,29.40,...,31.500,29.600,26.100,25.600,26.800,26.600,26.800,27.4000,27.2000,NaN
102,Nicaragua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.200,13.100,13.700,14.500,15.000,15.000,15.300,15.8000,16.3000,NaN
103,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.460,5.110,2.270,1.800,1.560,1.480,NaN,NaN,NaN,NaN
104,North Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.500,17.100,16.900,17.000,16.400,15.700,16.200,16.8000,16.8000,NaN
105,Norway,23.00,20.70,20.50,20.40,21.50,22.10,21.80,22.20,25.10,...,27.900,25.900,26.800,27.700,27.000,25.100,23.500,22.1000,22.0000,NaN
106,Oman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.420,3.390,2.540,2.270,2.600,2.520,NaN,NaN,NaN,NaN
107,Pakistan,NaN,10.40,11.90,10.80,10.90,11.00,11.50,12.30,13.30,...,9.490,8.940,9.980,9.190,NaN,NaN,NaN,NaN,NaN,NaN
108,Palau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.700,16.000,17.000,18.300,18.000,18.400,19.200,19.3000,19.7000,NaN
109,Palestine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.060,5.220,5.450,5.250,4.560,4.810,5.710,5.6000,NaN,NaN
110,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18.000,16.0000,13.5000,NaN
111,Paraguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.800,11.700,12.100,12.600,12.800,12.000,12.700,12.9000,12.6000,13.20
112,Peru,12.70,10.80,11.00,11.60,11.20,11.70,12.50,13.80,18.00,...,16.500,14.500,15.500,16.000,16.500,16.400,16.700,14.9000,13.8000,NaN
113,Philippines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.600,12.200,12.100,12.400,12.900,13.300,13.600,13.6000,13.7000,NaN
114,Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.200,15.900,16.500,16.700,16.000,15.600,15.500,15.6000,16.2000,NaN
115,Portugal,NaN,11.50,11.80,12.30,13.80,14.10,13.50,13.80,15.20,...,21.000,19.200,19.700,21.200,20.900,22.800,22.700,22.9000,22.5000,NaN
116,Qatar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.900,19.900,14.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.800,15.400,16.600,18.000,17.900,17.600,17.900,18.9000,16.8000,NaN
118,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.800,13.000,13.000,13.900,13.700,12.900,13.200,10.6000,9.1300,NaN
119,Rwanda,NaN,8.63,10.20,7.52,9.91,10.90,9.72,11.70,10.50,...,NaN,NaN,NaN,NaN,NaN,NaN,13.300,13.7000,14.8000,NaN
120,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,21.700,19.400,19.600,22.100,23.100,22.7000,24.2000,24.30
121,San Marino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.400,14.700,13.700,14.200,16.100,15.400,NaN,16.2000,15.4000,NaN
122,Sao Tome and Principe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.900,15.200,17.700,17.700,14.600,NaN,NaN,NaN,NaN,NaN
123,Senegal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,18.000,18.700,19.000,19.000,NaN,19.600,20.6000,20.5000,NaN
124,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.400,21.200,21.400,20.200,19.700,NaN,NaN,NaN,NaN,NaN
125,Seychelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.400,25.200,27.900,31.500,30.400,28.100,30.100,29.6000,31.7000,NaN
126,Sierra Leone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.210,8.410,9.080,9.310,9.510,9.120,8.600,NaN,NaN,NaN
127,Singapore,14.60,14.80,15.10,16.60,16.00,16.70,15.90,16.00,17.00,...,13.900,13.100,13.000,13.300,13.800,13.400,13.700,13.3000,13.7000,NaN
128,Slovak Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.400,15.500,15.000,15.500,15.000,15.900,16.700,17.6000,17.4000,NaN
129,Slovenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.400,18.000,18.100,17.900,18.000,18.000,18.200,18.5000,18.6000,NaN
130,Solomon Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,28.700,29.200,30.300,29.200,29.2000,26.7000,NaN
131,South Africa,17.20,17.80,17.40,18.30,18.20,19.10,19.10,19.30,19.20,...,26.800,24.400,25.000,25.200,25.600,26.000,26.500,27.3000,27.1000,NaN
132,South Korea,11.20,10.50,11.60,13.30,14.50,14.20,14.60,14.80,14.80,...,15.100,14.300,14.000,14.400,14.700,14.300,13.900,13.9000,14.8000,NaN
133,Spain,8.98,9.35,8.60,8.79,9.05,8.92,9.53,9.70,9.70,...,13.300,11.000,13.000,12.400,12.200,14.000,14.300,14.4000,13.8000,NaN
134,Sri Lanka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.300,12.800,11.300,11.300,10.400,10.500,10.100,12.4000,12.3000,NaN
135,St. Kitts and Nevis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.500,22.200,22.100,20.300,21.700,19.800,20.400,NaN,NaN,NaN
136,St. Lucia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.000,21.200,19.500,19.700,19.100,20.200,20.400,NaN,NaN,NaN
137,St. Vincent and the Grenadines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.900,23.700,22.900,22.600,23.000,21.600,23.900,NaN,NaN,NaN
138,Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.300,17.200,15.700,18.500,19.500,NaN,NaN,NaN,NaN,NaN
139,Swaziland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.800,25.300,16.000,16.300,28.600,NaN,NaN,NaN,NaN,NaN
140,Sweden,19.30,17.80,17.30,16.70,19.60,20.30,18.60,17.00,16.50,...,27.000,26.900,27.100,26.500,26.100,26.200,26.300,27.0000,27.7000,NaN
141,Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.51,...,9.910,9.680,9.720,9.650,9.520,9.600,9.400,9.8500,9.7700,NaN
142,Syria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.900,NaN,NaN,NaN
144,Thailand,11.00,10.20,12.60,11.20,10.80,11.60,11.70,12.40,13.10,...,15.400,14.200,14.900,16.400,15.400,16.900,15.600,16.0000,15.5000,NaN
145,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,24.300,24.900,25.700,23.200,22.500,18.5000,9.8200,NaN
146,Togo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.900,15.300,15.700,16.400,16.600,20.000,NaN,21.8000,21.9000,NaN
147,Trinidad and Tobago,NaN,NaN,NaN,NaN,29.60,32.60,28.70,29.20,35.70,...,29.500,26.800,26.200,25.600,26.400,NaN,27.100,NaN,NaN,NaN
148,Tunisia,17.80,19.00,17.90,20.20,19.90,21.30,22.60,21.80,21.00,...,20.500,20.000,20.100,21.200,21.100,NaN,NaN,NaN,NaN,NaN
149,Turkey,13.40,14.30,13.20,14.70,16.30,16.70,16.50,14.60,14.30,...,17.700,18.300,19.400,18.700,18.400,18.500,18.100,18.2000,18.3000,NaN
150,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9000,13.5000,NaN
151,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.900,16.400,15.600,18.500,18.300,17.600,17.300,20.5000,19.6000,NaN
152,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.321,0.364,0.370,0.356,0.0577,0.0435,NaN
153,United Kingdom,23.00,21.10,23.70,24.30,23.80,23.30,22.20,21.90,23.90,...,26.500,24.200,25.400,26.100,25.200,25.200,24.900,25.2000,25.6000,NaN
154,United States,11.80,11.50,11.80,11.20,10.70,11.60,11.50,12.00,12.10,...,10.300,7.940,8.610,9.590,9.820,10.600,11.000,11.2000,10.9000,NaN
155,Uruguay,13.70,10.40,12.70,12.20,15.50,15.80,16.00,14.40,15.80,...,18.200,18.700,18.900,19.100,18.800,19.000,18.600,18.5000,23.7000,NaN
156,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16.200,17.200,17.500,17.300,17.5000,17.3000,NaN
157,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,16.000,15.500,16.000,16.600,17.200,17.400,16.7000,16.6000,NaN
158,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.400,20.600,22.300,22.200,19.000,19.100,NaN,NaN,NaN,NaN
159,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.200,12.500,13.200,17.100,16.200,15.700,17.000,16.8000,14.9000,NaN
160,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.300,20.700,20.900,21.400,NaN,NaN,NaN,NaN,NaN

In [329]:
tax.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 47 columns):
country    161 non-null object
1972       38 non-null float64
1973       45 non-null float64
1974       45 non-null float64
1975       46 non-null float64
1976       47 non-null float64
1977       48 non-null float64
1978       49 non-null float64
1979       48 non-null float64
1980       52 non-null float64
1981       51 non-null float64
1982       49 non-null float64
1983       50 non-null float64
1984       50 non-null float64
1985       52 non-null float64
1986       52 non-null float64
1987       49 non-null float64
1988       54 non-null float64
1989       54 non-null float64
1990       77 non-null float64
1991       77 non-null float64
1992       80 non-null float64
1993       82 non-null float64
1994       85 non-null float64
1995       94 non-null float64
1996       94 non-null float64
1997       98 non-null float64
1998       99 non-null float64
1999       101 non-null float64
2000       98 non-null float64
2001       106 non-null float64
2002       112 non-null float64
2003       116 non-null float64
2004       118 non-null float64
2005       123 non-null float64
2006       126 non-null float64
2007       126 non-null float64
2008       134 non-null float64
2009       137 non-null float64
2010       143 non-null float64
2011       144 non-null float64
2012       140 non-null float64
2013       131 non-null float64
2014       128 non-null float64
2015       119 non-null float64
2016       109 non-null float64
2017       7 non-null float64
dtypes: float64(46), object(1)
memory usage: 59.2+ KB

In [330]:
income = pd.read_csv('income_per_person_gdppercapita_ppp_inflation_adjusted.csv')
income

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040
0,Afghanistan,603,603,603,603,603,603,603,603,603,...,2550,2600,2660,2710,2770,2820,2880,2940,3000,3060
1,Albania,667,667,667,667,667,668,668,668,668,...,19400,19800,20200,20600,21000,21500,21900,22300,22800,23300
2,Algeria,715,716,717,718,719,720,721,722,723,...,14300,14600,14900,15200,15500,15800,16100,16500,16800,17100
3,Andorra,1200,1200,1200,1200,1210,1210,1210,1210,1220,...,73600,75100,76700,78300,79900,81500,83100,84800,86500,88300
4,Angola,618,620,623,626,628,631,634,637,640,...,6110,6230,6350,6480,6610,6750,6880,7020,7170,7310
5,Antigua and Barbuda,757,757,757,757,757,757,757,758,758,...,28800,29400,30000,30600,31200,31800,32500,33100,33800,34500
6,Argentina,1640,1640,1650,1650,1660,1660,1670,1680,1680,...,20800,21300,21700,22100,22600,23100,23500,24000,24500,25000
7,Armenia,514,514,514,514,514,514,514,514,514,...,15300,15600,15900,16300,16600,16900,17300,17600,18000,18400
8,Australia,817,822,826,831,836,841,845,850,855,...,53000,54000,55100,56200,57400,58600,59700,61000,62200,63500
9,Austria,1850,1850,1860,1870,1880,1880,1890,1900,1910,...,54700,55800,56900,58000,59200,60400,61700,62900,64200,65500
10,Azerbaijan,775,775,775,775,775,776,776,776,776,...,19100,19500,19900,20300,20700,21100,21500,22000,22400,22900
11,Bahamas,1450,1450,1450,1450,1450,1450,1450,1450,1450,...,31600,32200,32800,33500,34100,34800,35500,36300,37000,37800
12,Bahrain,1240,1240,1250,1250,1260,1260,1270,1270,1280,...,47700,48600,49600,50600,51600,52700,53700,54800,55900,57100
13,Bangladesh,876,876,876,876,876,876,876,876,876,...,7480,7650,7820,7980,8140,8310,8480,8650,8830,9010
14,Barbados,913,914,914,914,914,914,914,914,915,...,20100,20500,20900,21300,21700,22200,22600,23100,23600,24000
15,Belarus,608,608,608,609,609,609,610,610,610,...,19900,20300,20700,21100,21500,22000,22400,22900,23300,23800
16,Belgium,2390,2390,2390,2400,2400,2400,2410,2410,2410,...,49900,50900,51900,53000,54100,55200,56300,57400,58600,59800
17,Belize,579,579,579,579,579,579,579,579,579,...,7760,7910,8060,8220,8390,8560,8730,8910,9090,9270
18,Benin,597,597,597,597,597,597,597,597,597,...,3310,3380,3450,3520,3590,3660,3740,3810,3890,3970
19,Bhutan,629,629,630,630,630,630,630,630,630,...,15700,16100,16400,16800,17100,17400,17800,18200,18500,18900
20,Bolivia,854,854,854,854,854,854,854,854,855,...,9230,9420,9620,9810,10000,10200,10400,10600,10900,11100
21,Bosnia and Herzegovina,669,669,669,669,669,669,669,669,669,...,18300,18700,19100,19500,19900,20300,20700,21100,21500,22000
22,Botswana,397,397,397,397,397,398,398,398,398,...,21800,22300,22700,23200,23700,24100,24600,25100,25700,26200
23,Brazil,1120,1120,1120,1120,1120,1120,1120,1120,1120,...,17700,18000,18400,18800,19100,19500,19900,20300,20800,21200
24,Brunei,1510,1510,1510,1510,1510,1510,1510,1510,1510,...,89600,91300,93200,95000,97000,98900,101000,103000,105000,107000
25,Bulgaria,1090,1090,1090,1090,1090,1090,1090,1090,1090,...,29000,29600,30200,30900,31500,32100,32800,33500,34100,34800
26,Burkina Faso,480,480,480,480,480,480,480,480,480,...,2500,2550,2600,2660,2710,2770,2820,2880,2940,3000
27,Burundi,418,418,419,419,420,420,420,421,421,...,557,566,577,588,600,612,625,637,650,664
28,Cambodia,384,385,385,385,385,385,385,385,385,...,6670,6820,6970,7110,7250,7400,7550,7710,7860,8020
29,Cameroon,626,626,626,626,626,627,627,627,627,...,4510,4610,4700,4800,4900,5000,5100,5200,5310,5420
30,Canada,1310,1320,1330,1340,1350,1360,1360,1370,1380,...,50600,51600,52600,53700,54800,55900,57000,58200,59300,60500
31,Cape Verde,529,529,529,529,530,530,530,530,530,...,10200,10400,10600,10800,11000,11300,11500,11700,12000,12200
32,Central African Republic,424,424,424,424,424,424,424,425,425,...,1090,1120,1140,1160,1190,1210,1240,1260,1290,1310
33,Chad,418,418,418,418,418,418,418,419,419,...,2170,2210,2250,2300,2340,2390,2440,2490,2540,2590
34,Chile,744,744,744,744,744,744,744,744,744,...,30000,30700,31300,31900,32600,33200,33900,34600,35300,36000
35,China,736,735,733,732,730,729,727,726,724,...,28900,29600,30200,30900,31500,32100,32800,33400,34100,34800
36,Colombia,937,932,927,923,918,913,908,904,899,...,18500,18900,19300,19700,20100,20500,20900,21300,21800,22200
37,Comoros,696,697,697,698,699,700,700,701,702,...,2880,2930,2990,3050,3110,3180,3240,3310,3380,3440
38,"Congo, Dem. Rep.",485,487,489,491,493,495,497,499,501,...,1000,1020,1040,1060,1090,1110,1130,1150,1180,1200
39,"Congo, Rep.",575,576,578,580,581,583,585,586,588,...,5180,5280,5380,5490,5600,5710,5830,5950,6070,6190
40,Costa Rica,775,775,775,775,775,776,776,776,776,...,20200,20600,21000,21500,21900,22300,22800,23300,23700,24200
41,Cote d'Ivoire,812,816,819,822,825,829,832,835,839,...,5840,5970,6090,6220,6350,6470,6610,6740,6880,7020
42,Croatia,1080,1090,1100,1110,1120,1130,1140,1150,1160,...,33700,34400,35100,35800,36600,37300,38100,38800,39600,40400
43,Cuba,902,909,917,925,932,940,948,956,964,...,11000,11200,11500,11700,11900,12200,12400,12700,12900,13200
44,Cyprus,853,854,854,854,854,854,854,854,854,...,41700,42600,43400,44300,45200,46100,47100,48000,49000,50000
45,Czech Republic,1920,1920,1920,1920,1920,1920,1920,1920,1920,...,45100,46100,47000,48000,48900,49900,50900,52000,53000,54100
46,Denmark,2010,2020,2020,2020,2030,2030,2030,2040,2040,...,56300,57400,58600,59800,61000,62200,63500,64800,66100,67400
47,Djibouti,752,754,757,759,762,764,766,769,771,...,5020,5130,5230,5340,5450,5560,5670,5790,5910,6030
48,Dominica,663,663,663,663,663,664,664,664,664,...,13700,14000,14300,14600,14800,15100,15500,15800,16100,16400
49,Dominican Republic,667,667,667,667,667,667,668,668,668,...,24700,25200,25800,26300,26800,27400,27900,28500,29100,29700
50,Ecuador,529,529,529,529,529,529,529,530,530,...,11700,11900,12200,12400,12700,12900,13200,13400,13700,14000
51,Egypt,1590,1600,1600,1600,1600,1600,1600,1600,1600,...,15800,16100,16400,16800,17100,17400,17800,18200,18500,18900
52,El Salvador,974,975,975,975,975,975,975,975,976,...,8960,9140,9320,9510,9700,9900,10100,10300,10500,10700
53,Equatorial Guinea,356,356,357,357,357,358,358,359,359,...,11400,11600,11800,12000,12200,12500,12700,13000,13300,13500
54,Eritrea,532,532,532,532,532,532,532,533,533,...,1960,2000,2040,2080,2130,2170,2210,2260,2300,2350
55,Estonia,938,939,940,941,942,943,944,945,947,...,43600,44500,45400,46300,47300,48200,49200,50200,51200,52300
56,Ethiopia,523,523,523,523,523,523,523,523,523,...,3110,3180,3250,3320,3390,3460,3530,3600,3670,3740
57,Fiji,785,785,785,785,785,785,786,786,786,...,13400,13600,13900,14200,14500,14800,15100,15400,15700,16000
58,Finland,1230,1240,1240,1250,1250,1260,1260,1270,1270,...,50400,51400,52400,53500,54500,55700,56800,57900,59100,60300
59,France,1850,1850,1850,1850,1850,1850,1850,1850,1860,...,47100,48000,48900,49900,51000,52000,53000,54100,55200,56300
60,Gabon,390,390,390,390,390,391,391,391,391,...,22500,22900,23400,23900,24400,24900,25400,25900,26400,27000
61,Gambia,813,813,814,814,815,815,816,816,817,...,2010,2050,2090,2140,2180,2220,2270,2310,2360,2410
62,Georgia,543,543,543,543,543,543,543,543,544,...,16700,17100,17400,17800,18200,18500,18900,19300,19700,20100
63,Germany,1990,2010,2020,2040,2050,2070,2080,2100,2110,...,55300,56400,57500,58700,59900,61100,62300,63600,64900,66200
64,Ghana,696,696,697,697,698,698,699,699,700,...,5890,6020,6140,6260,6390,6520,6650,6790,6930,7070
65,Greece,1370,1370,1380,1380,1390,1400,1410,1420,1430,...,31300,31900,32500,33200,33900,34500,35300,36000,36700,37400
66,Grenada,959,959,959,959,959,959,959,960,960,...,18900,19300,19700,20100,20500,21000,21400,21800,22300,22700
67,Guatemala,857,857,857,857,858,858,858,858,858,...,9230,9410,9600,9790,9990,10200,10400,10600,10800,11100
68,Guinea,450,450,450,450,450,451,451,451,451,...,3240,3310,3380,3450,3520,3590,3660,3740,3810,3890
69,Guinea-Bissau,567,567,567,567,567,567,567,567,567,...,2250,2300,2350,2390,2440,2490,2540,2600,2650,2700
70,Guyana,1210,1210,1210,1220,1220,1220,1220,1220,1220,...,11300,11600,11800,12000,12300,12500,12800,13000,13300,13600
71,Haiti,633,633,634,634,634,634,634,634,634,...,1810,1850,1880,1920,1960,2000,2040,2080,2120,2170
72,Honduras,675,675,675,675,675,675,675,675,675,...,5920,6040,6160,6290,6410,6540,6680,6810,6950,7090
73,Hungary,1250,1250,1250,1250,1250,1250,1250,1250,1250,...,39800,40700,41500,42300,43200,44100,45000,45900,46800,47800
74,Iceland,926,926,927,927,927,927,927,927,927,...,52200,53200,54200,55300,56500,57600,58800,60000,61200,62400
75,India,863,862,858,854,849,845,841,837,833,...,12800,13100,13300,13600,13900,14200,14500,14800,15100,15400
76,Indonesia,990,986,983,979,975,971,967,963,959,...,18300,18700,19100,19500,19900,20300,20700,21200,21600,22000
77,Iran,1530,1530,1530,1530,1530,1530,1530,1530,1530,...,17100,17400,17800,18100,18500,18900,19300,19600,20000,20500
78,Iraq,3840,3840,3840,3840,3840,3840,3840,3840,3840,...,16800,17100,17400,17800,18100,18500,18900,19200,19600,20000
79,Ireland,1460,1470,1480,1490,1500,1510,1520,1530,1550,...,90900,92700,94600,96500,98400,100000,102000,105000,107000,109000
80,Israel,879,880,880,880,880,880,880,880,881,...,39900,40700,41500,42400,43200,44100,45000,45900,46900,47800
81,Italy,2780,2740,2830,2910,3040,2940,3010,3020,3190,...,41300,42100,42900,43800,44700,45600,46500,47500,48400,49400
82,Jamaica,1360,1360,1360,1360,1360,1360,1360,1360,1360,...,10000,10200,10400,10600,10900,11100,11300,11500,11800,12000
83,Japan,1010,1010,1010,1010,1010,1020,1020,1020,1020,...,46100,47000,47900,48900,49900,50900,51900,53000,54100,55200
84,Jordan,1130,1130,1130,1130,1130,1130,1130,1130,1130,...,10700,10900,11100,11300,11600,11800,12000,12300,12500,12800
85,Kazakhstan,1140,1140,1140,1140,1150,1150,1150,1150,1150,...,33400,34100,34800,35500,36200,36900,37700,38500,39200,40000
86,Kenya,854,856,859,862,864,867,870,872,875,...,4400,4500,4590,4680,4780,4880,4970,5080,5180,5280
87,Kiribati,551,551,552,552,553,553,554,554,555,...,2230,2280,2320,2370,2420,2470,2520,2570,2620,2670
88,Kuwait,1100,1100,1110,1110,1110,1120,1120,1130,1130,...,68500,69800,71100,72600,74000,75500,77100,78600,80200,81900
89,Kyrgyz Republic,508,508,508,508,508,508,509,509,509,...,4240,4320,4410,4500,4590,4680,4780,4870,4970,5070
90,Lao,864,865,865,865,865,865,865,865,866,...,11600,11800,12100,12300,12600,12800,13100,13300,13600,13900
91,Latvia,751,752,753,754,754,755,756,757,758,...,38300,39100,39900,40700,41500,42400,43200,44100,45000,45900
92,Lebanon,2150,2150,2150,2150,2160,2160,2160,2160,2160,...,17500,17900,18300,18700,19000,19400,19800,20200,20600,21100
93,Lesotho,351,351,352,352,352,352,352,353,353,...,3310,3370,3430,3500,3570,3650,3720,3800,3870,3950
94,Liberia,797,797,797,797,797,797,798,798,798,...,1180,1200,1230,1250,1280,1300,1330,1360,1380,1410
95,Libya,1050,1050,1050,1050,1050,1050,1050,1050,1050,...,14500,14700,15000,15300,15600,15900,16300,16600,16900,17300
96,Lithuania,1270,1270,1270,1270,1280,1280,1280,1280,1280,...,45400,46400,47300,48300,49300,50300,51300,52400,53400,54500
97,Luxembourg,1450,1450,1450,1450,1450,1450,1450,1450,1450,...,107000,109000,111000,114000,116000,118000,121000,123000,126000,128000
98,Madagascar,573,573,573,573,573,573,573,573,573,...,1920,1960,2000,2040,2080,2120,2160,2210,2250,2300
99,Malawi,350,350,350,350,350,350,350,350,350,...,1660,1700,1730,1770,1800,1840,1880,1910,1950,1990
100,Malaysia,1120,1120,1120,1120,1120,1120,1120,1120,1120,...,42100,43000,43900,44800,45700,46600,47600,48500,49500,50500
101,Maldives,842,843,843,843,843,843,843,843,843,...,21100,21500,22000,22400,22900,23300,23800,24300,24800,25300
102,Mali,603,603,603,603,603,603,603,603,603,...,2620,2670,2720,2780,2830,2890,2950,3010,3070,3130
103,Malta,781,782,782,782,782,782,782,782,782,...,52500,53600,54700,55800,56900,58100,59300,60500,61700,63000
104,Marshall Islands,539,539,540,540,540,541,541,541,542,...,3870,3940,4020,4100,4180,4270,4350,4440,4530,4620
105,Mauritania,527,528,528,528,528,528,528,528,528,...,5830,5950,6070,6200,6330,6450,6590,6720,6860,7000
106,Mauritius,940,940,940,940,941,941,941,941,941,...,32800,33500,34200,34900,35600,36300,37100,37800,38600,39400
107,Mexico,1560,1550,1520,1510,1480,1460,1430,1400,1360,...,21500,22000,22400,22900,23300,23800,24300,24800,25300,25800
108,"Micronesia, Fed. Sts.",518,518,518,519,519,519,520,520,520,...,3620,3690,3770,3840,3920,4000,4080,4170,4250,4340
109,Moldova,621,621,621,621,621,621,622,622,622,...,10000,10200,10400,10600,10900,11100,11300,11500,11800,12000
110,Monaco,1950,1950,1950,1960,1960,1960,1960,1970,1970,...,74100,75600,77100,78600,80200,81900,83500,85200,87000,88700
111,Mongolia,592,592,592,592,592,593,593,593,593,...,18100,18400,18800,19200,19600,20000,20400,20800,21200,21700
112,Montenegro,1060,1060,1060,1060,1060,1060,1060,1060,1060,...,24300,24800,25300,25800,26400,26900,27500,28000,28600,29200
113,Morocco,714,714,715,715,715,715,715,715,715,...,11100,11300,11500,11800,12000,12300,12500,12800,13000,13300
114,Mozambique,390,391,391,391,391,392,392,392,392,...,2080,2130,2180,2230,2270,2320,2370,2420,2470,2520
115,Myanmar,594,594,594,594,594,594,594,594,594,...,10900,11100,11400,11600,11800,12100,12300,12600,12800,13100
116,Namibia,540,540,540,540,540,541,541,541,541,...,11300,11500,11700,12000,12200,12400,12700,13000,13200,13500
117,Nauru,554,554,554,554,554,554,554,554,555,...,14300,14600,14900,15200,15500,15800,16100,16400,16800,17100
118,Nepal,621,621,621,621,621,621,621,621,621,...,4290,4380,4470,4560,4660,4750,4850,4950,5050,5150
119,Netherlands,3330,3330,3330,3330,3330,3330,3330,3330,2970,...,60100,61300,62500,63800,65100,66400,67800,69100,70500,72000
120,New Zealand,658,658,658,658,659,659,659,659,659,...,41900,42700,43500,44400,45300,46200,47200,48100,49100,50100
121,Nicaragua,973,973,973,974,974,974,974,974,974,...,4850,4940,5040,5140,5250,5350,5460,5570,5690,5800
122,Niger,446,446,446,446,446,446,446,447,447,...,1340,1360,1390,1420,1450,1480,1510,1540,1570,1600
123,Nigeria,851,853,854,856,857,859,860,862,864,...,5720,5830,5940,6060,6180,6310,6440,6570,6700,6840
124,North Korea,250,250,249,249,249,249,248,248,248,...,1950,1990,2030,2070,2110,2150,2190,2240,2280,2330
125,North Macedonia,690,690,690,690,690,691,691,691,691,...,19900,20400,20800,21200,21600,22100,22500,23000,23500,23900
126,Norway,2530,2540,2540,2550,2550,2550,2560,2560,2560,...,78300,79800,81400,83000,84700,86400,88200,90000,91800,93700
127,Oman,915,916,916,916,916,916,916,916,917,...,34100,34800,35400,36100,36900,37600,38400,39100,39900,40800
128,Pakistan,1020,1020,1020,1020,1020,1020,1020,1020,1020,...,6620,6760,6900,7040,7180,7330,7480,7630,7780,7940
129,Palau,839,839,839,839,839,839,840,840,840,...,20500,20900,21300,21800,22200,22600,23100,23600,24100,24500
130,Palestine,675,675,675,675,675,675,675,675,675,...,5390,5500,5610,5720,5840,5960,6080,6200,6330,6450
131,Panama,847,847,847,847,848,848,848,848,848,...,33600,34300,35000,35800,36500,37200,38000,38800,39500,40300
132,Papua New Guinea,546,546,546,546,547,547,547,547,547,...,4630,4730,4820,4920,5020,5120,5230,5330,5440,5550
133,Paraguay,835,835,835,835,836,836,836,836,836,...,16000,16400,16700,17000,17400,17700,18100,18500,18800,19200
134,Peru,1120,1060,1060,1040,1040,1070,1100,1110,1090,...,17700,18100,18400,18800,19200,19600,20000,20400,20800,21200
135,Philippines,1090,1090,1090,1090,1090,1090,1090,1090,1090,...,13300,13500,13800,14100,14400,14700,15000,15300,15600,15900
136,Poland,1100,1080,1050,1020,1000,976,952,929,907,...,40300,41200,42000,42900,43700,44600,45500,46500,47400,48400
137,Portugal,1730,1780,1830,1870,1960,1870,1740,1780,1720,...,36300,37000,37800,38600,39300,40100,41000,41800,42600,43500
138,Qatar,1100,1100,1110,1110,1110,1120,1120,1130,1130,...,149000,153000,156000,159000,162000,165000,169000,172000,176000,179000
139,Romania,377,377,377,377,377,377,377,377,377,...,35500,36200,37000,37700,38500,39300,40100,40900,41700,42600
140,Russia,1430,1430,1430,1440,1440,1440,1440,1440,1440,...,32800,33400,34100,34800,35500,36200,37000,37700,38500,39300
141,Rwanda,431,432,432,433,433,434,434,435,435,...,3540,3620,3700,3770,3850,3930,4010,4090,4170,4260
142,Samoa,1400,1400,1400,1400,1400,1400,1400,1400,1400,...,7640,7790,7950,8110,8280,8440,8620,8790,8970,9150
143,San Marino,1400,1400,1410,1410,1410,1410,1420,1420,1420,...,62900,64100,65400,66700,68000,69400,70800,72300,73700,75200
144,Sao Tome and Principe,850,852,853,855,857,858,860,861,863,...,3930,4010,4100,4180,4260,4350,4440,4530,4620,4720
145,Saudi Arabia,2370,2370,2370,2370,2370,2370,2370,2380,2380,...,53200,54200,55300,56400,57600,58800,59900,61200,62400,63700
146,Senegal,497,497,497,497,497,497,498,498,498,...,5740,5870,5990,6120,6240,6370,6500,6630,6760,6900
147,Serbia,1360,1360,1360,1360,1360,1360,1360,1360,1360,...,24700,25300,25800,26300,26900,27400,28000,28500,29100,29700
148,Seychelles,792,795,798,801,804,807,811,814,817,...,37700,38500,39300,40100,40900,41700,42600,43500,44300,45200
149,Sierra Leone,734,734,734,734,734,734,735,735,735,...,1930,1970,2010,2050,2090,2140,2180,2220,2270,2310
150,Singapore,1020,1020,1020,1020,1020,1020,1020,1020,1020,...,111000,113000,115000,117000,120000,122000,125000,127000,130000,133000
151,Slovak Republic,1430,1430,1430,1430,1430,1430,1430,1430,1430,...,42400,43300,44100,45000,46000,46900,47800,48800,49800,50800
152,Slovenia,1410,1410,1410,1410,1410,1410,1410,1410,1410,...,43600,44500,45400,46300,47300,48200,49200,50200,51200,52300
153,Solomon Islands,363,363,363,363,363,363,363,363,363,...,2430,2470,2520,2570,2620,2680,2730,2790,2840,2900
154,Somalia,694,694,695,696,696,697,698,698,699,...,732,746,761,776,792,808,825,842,859,876
155,South Africa,2280,2250,2230,2200,2180,2060,2060,2240,1960,...,13000,13300,13500,13800,14100,14400,14700,15000,15300,15600
156,South Korea,462,462,462,462,462,462,462,462,462,...,49000,50000,51100,52100,53200,54200,55300,56500,57600,58800
157,South Sudan,507,507,507,507,508,508,508,508,508,...,2190,2230,2270,2320,2360,2410,2460,2510,2560,2610
158,Spain,1600,1610,1620,1620,1630,1640,1650,1650,1660,...,42400,43300,44100,45000,45900,46900,47800,48800,49800,50800
159,Sri Lanka,799,799,799,799,799,799,799,799,799,...,17300,17700,18100,18400,18800,19200,19600,20000,20400,20800
160,St. Kitts and Nevis,1160,1170,1170,1170,1170,1170,1170,1170,1170,...,36100,36800,37500,38300,39100,39900,40700,41500,42400,43200
161,St. Lucia,874,875,875,875,875,875,875,875,875,...,14900,15200,15500,15800,16200,16500,16800,17200,17500,17900
162,St. Vincent and the Grenadines,838,838,838,838,838,839,839,839,839,...,14500,14800,15100,15400,15700,16000,16300,16700,17000,17300
163,Sudan,518,518,518,518,519,519,519,519,519,...,5360,5460,5570,5680,5800,5920,6040,6160,6290,6410
164,Suriname,1640,1640,1640,1640,1640,1640,1640,1640,1640,...,16600,16900,17200,17600,18000,18300,18700,19100,19500,19900
165,Swaziland,490,490,490,490,490,490,490,490,490,...,9740,9920,10100,10300,10500,10700,11000,11200,11400,11600
166,Sweden,1450,1440,1500,1490,1390,1480,1500,1430,1360,...,55500,56600,57700,58900,60100,61300,62500,63800,65100,66400
167,Switzerland,2700,2700,2700,2700,2700,2700,2700,2700,2700,...,65100,66400,67700,69000,70400,71900,73300,74800,76400,77900
168,Syria,502,503,503,503,503,503,503,503,503,...,3290,3350,3420,3490,3560,3630,3710,3780,3860,3940
169,Tajikistan,556,557,557,557,557,557,558,558,558,...,4110,4190,4280,4370,4460,4550,4640,4730,4830,4930
170,Tanzania,562,562,562,562,562,562,563,563,563,...,4200,4290,4380,4470,4560,4650,4750,4840,4940,5040
171,Thailand,795,795,795,795,795,795,795,795,795,...,25000,25500,26000,26600,27100,27700,28200,28800,29400,30000
172,Timor-Leste,521,522,523,524,525,526,527,528,529,...,5720,5830,5950,6070,6200,6320,6450,6580,6720,6850
173,Togo,682,683,683,683,683,683,683,683,683,...,2180,2230,2270,2320,2370,2420,2470,2520,2570,2620
174,Tonga,663,663,663,663,663,663,663,663,663,...,7810,7960,8130,8290,8460,8630,8810,8990,9170,9360
175,Trinidad and Tobago,1230,1230,1230,1230,1230,1230,1230,1230,1230,...,34200,34800,35500,36200,37000,37700,38500,39300,40100,40900

In [331]:
income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Columns: 242 entries, country to 2040
dtypes: int64(241), object(1)
memory usage: 365.0+ KB

In [335]:
tax_last_10 = tax.iloc[:, np.r_[:1, 35:46]]
tax_last_10

,country,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Afghanistan,6.88,5.23,6.040,8.440,9.120,8.850,7.470,7.080,6.840,7.5500,NaN
1,Albania,NaN,NaN,NaN,NaN,NaN,18.000,17.500,16.500,18.300,18.5000,17.6000
2,Algeria,40.80,37.40,45.300,35.100,34.400,37.200,NaN,NaN,NaN,NaN,NaN
3,Angola,29.30,23.20,27.000,17.100,16.900,17.300,16.700,15.500,15.600,12.5000,10.3000
4,Antigua and Barbuda,18.20,19.50,18.700,17.300,18.500,17.900,18.500,17.200,16.500,NaN,NaN
5,Argentina,12.90,12.40,13.300,12.400,12.900,12.700,13.000,12.500,12.600,12.3000,12.2000
6,Armenia,14.40,16.00,17.300,16.500,17.100,17.200,17.500,NaN,21.600,20.9000,21.3000
7,Australia,24.60,24.10,24.300,22.100,20.600,20.400,21.200,22.100,22.000,22.0000,22.3000
8,Austria,25.10,25.40,26.100,25.200,25.300,25.400,25.900,26.400,26.400,26.8000,25.7000
9,Azerbaijan,NaN,NaN,16.400,14.100,12.200,12.200,12.800,13.400,14.200,15.6000,NaN
10,Bahamas,11.20,11.40,12.100,11.300,10.900,12.900,11.900,11.400,11.400,12.7000,14.2000
11,Bahrain,1.17,1.15,1.240,1.360,1.180,1.110,NaN,1.070,NaN,NaN,NaN
12,Bangladesh,7.04,6.92,7.660,7.500,7.830,8.690,9.020,8.960,8.640,8.5000,8.7700
13,Barbados,25.10,26.80,26.400,24.900,25.100,25.900,24.200,23.400,24.000,26.1000,NaN
14,Belarus,22.20,23.70,25.400,19.300,16.300,14.500,14.700,13.400,12.700,14.2000,13.8000
15,Belgium,25.20,24.70,25.100,23.600,24.300,24.700,25.700,26.200,26.300,24.7000,23.1000
16,Belize,21.80,22.90,21.700,22.500,23.600,22.600,22.500,23.300,23.400,NaN,NaN
17,Benin,14.20,15.70,16.100,15.000,15.500,14.800,14.400,15.400,NaN,NaN,NaN
18,Bhutan,9.03,7.52,8.420,9.240,13.100,13.500,14.700,14.400,13.300,13.8000,13.2000
19,Bolivia,16.80,17.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Bosnia and Herzegovina,21.70,21.40,20.300,18.900,19.700,20.300,20.500,19.800,19.800,19.9000,20.0000
21,Botswana,26.90,25.70,27.400,27.300,23.600,23.200,26.600,25.600,25.800,24.7000,20.8000
22,Brazil,15.40,15.80,15.500,14.400,13.600,14.200,13.700,13.400,12.800,12.8000,12.9000
23,Bulgaria,21.10,22.90,22.200,19.000,18.500,17.700,19.000,19.800,19.600,20.2000,20.0000
24,Burkina Faso,12.10,12.70,11.900,12.500,12.700,13.700,15.600,16.800,15.400,15.1000,15.8000
25,Burundi,NaN,NaN,NaN,NaN,13.900,14.700,13.700,12.200,NaN,NaN,NaN
26,Cambodia,8.18,9.70,10.600,9.650,10.000,10.200,11.100,12.100,14.600,14.2000,15.3000
27,Canada,13.40,13.40,12.400,12.300,11.800,11.800,11.700,11.700,11.800,12.3000,12.2000
28,Cape Verde,22.70,20.90,21.300,18.400,NaN,NaN,17.900,NaN,NaN,NaN,NaN
29,Central African Republic,NaN,NaN,9.060,9.170,10.100,9.290,NaN,NaN,NaN,NaN,NaN
30,Chile,19.50,20.30,18.700,14.500,17.400,18.900,19.000,17.400,17.000,17.4000,17.4000
31,China,9.06,9.77,10.100,10.300,10.200,10.300,10.200,9.870,9.670,9.3700,NaN
32,Colombia,NaN,NaN,12.900,12.600,12.100,14.600,13.300,14.100,15.000,15.1000,13.3000
33,"Congo, Dem. Rep.",6.83,6.99,8.970,7.890,8.350,NaN,NaN,NaN,NaN,NaN,NaN
34,"Congo, Rep.",5.79,6.60,5.950,8.400,7.600,8.860,9.430,NaN,NaN,NaN,NaN
35,Costa Rica,13.90,14.90,15.300,13.300,13.100,13.400,13.300,13.700,13.400,13.7000,14.0000
36,Cote d'Ivoire,14.70,15.10,15.100,14.600,14.300,10.900,14.300,14.500,14.000,15.4000,15.2000
37,Croatia,19.90,19.90,20.000,19.200,19.100,18.400,19.500,19.000,19.100,NaN,NaN
38,Cyprus,40.90,48.30,46.100,23.300,23.200,23.300,23.300,23.400,24.500,24.1000,24.3000
39,Czech Republic,14.10,14.50,13.400,13.400,13.400,14.300,14.700,14.900,14.200,14.6000,14.7000
40,Denmark,31.90,35.10,33.400,33.200,32.700,32.800,33.400,33.800,36.500,33.9000,33.7000
41,Dominica,23.50,25.10,24.800,24.300,24.600,23.100,23.000,22.400,22.100,NaN,NaN
42,Dominican Republic,14.00,14.90,14.200,12.600,12.200,12.300,13.000,13.500,13.600,13.3000,13.5000
43,Egypt,15.80,15.30,15.300,15.700,14.100,14.000,12.400,13.500,12.200,12.5000,NaN
44,El Salvador,15.70,16.70,17.100,15.000,15.800,15.300,16.200,17.100,16.700,16.9000,17.6000
45,Equatorial Guinea,9.67,7.55,7.790,12.800,7.590,7.020,8.740,8.520,8.300,11.5000,NaN
46,Estonia,1.28,1.30,1.240,1.370,1.270,1.230,1.270,1.290,1.340,1.4000,1.4300
47,Ethiopia,8.26,7.81,7.810,6.580,8.160,9.210,9.380,8.760,NaN,NaN,NaN
48,Fiji,23.20,NaN,NaN,NaN,21.800,23.000,23.200,23.600,24.600,25.5000,NaN
49,Finland,21.50,21.10,20.500,19.000,18.700,20.100,20.300,20.700,20.800,20.7000,21.0000
50,France,22.60,22.10,22.000,20.700,22.000,21.800,22.600,23.200,23.200,23.2000,23.1000
51,Gambia,7.98,13.00,14.700,15.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Georgia,15.40,17.70,23.800,23.100,22.100,23.800,24.100,23.400,23.500,23.8000,23.5000
53,Germany,10.80,11.30,11.400,11.600,11.100,11.400,11.600,11.600,11.500,11.4000,11.2000
54,Ghana,NaN,NaN,NaN,NaN,13.700,NaN,NaN,NaN,NaN,NaN,NaN
55,Greece,20.00,20.20,20.200,19.800,20.200,22.100,23.600,23.700,24.400,24.9000,26.7000
56,Grenada,19.10,19.70,19.500,18.200,18.700,19.200,18.700,18.400,19.400,NaN,NaN
57,Guatemala,11.90,12.10,11.300,10.300,10.400,10.800,10.800,10.900,10.800,10.2000,10.4000
58,Honduras,15.20,16.40,16.100,14.200,14.400,14.800,14.700,15.100,16.500,17.3000,NaN
59,Hungary,19.80,21.40,23.300,23.300,22.800,21.100,22.900,22.700,23.000,23.4000,23.4000
60,Iceland,27.40,26.20,23.200,20.100,20.700,21.200,22.100,22.700,25.300,23.5000,38.5000
61,India,11.40,12.30,11.100,9.940,10.500,10.200,10.800,11.000,NaN,NaN,NaN
62,Indonesia,NaN,NaN,13.300,11.100,10.500,11.200,11.400,11.300,10.800,10.8000,10.3000
63,Iran,6.22,5.94,6.200,7.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.890,1.2300,2.0200
65,Ireland,26.80,25.90,23.700,22.000,21.800,21.800,22.500,22.800,23.200,18.9000,18.8000
66,Israel,26.10,26.10,23.800,21.900,22.500,22.700,22.100,23.000,23.300,23.4000,23.4000
67,Italy,22.10,22.40,21.900,22.400,22.300,22.300,23.600,23.700,23.500,23.4000,23.7000
68,Jamaica,24.00,24.80,24.700,25.000,24.300,23.400,24.300,24.000,24.100,24.8000,26.1000
69,Japan,10.50,10.10,8.930,8.370,8.810,9.360,9.680,10.400,11.500,11.4000,11.1000
70,Jordan,NaN,NaN,17.800,17.000,16.000,15.000,15.300,15.300,NaN,NaN,NaN
71,Kazakhstan,NaN,NaN,NaN,NaN,15.700,18.300,13.300,16.000,14.200,9.8400,9.9200
72,Kenya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.900,16.3000,15.8000
73,Kiribati,NaN,NaN,NaN,NaN,16.000,18.100,18.500,17.800,17.800,22.3000,24.5000
74,Kuwait,0.97,1.09,0.876,0.971,0.979,0.800,0.716,0.777,0.890,1.3800,NaN
75,Kyrgyz Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.600,17.500,16.8000,16.9000
76,Lao,NaN,NaN,12.100,12.800,13.000,13.100,13.600,13.700,13.800,13.5000,12.9000
77,Latvia,22.20,21.70,20.800,18.800,19.800,20.000,21.100,22.000,22.400,22.8000,23.9000
78,Lebanon,15.20,15.10,16.400,16.800,16.900,16.300,15.200,14.300,14.200,13.6000,13.9000
79,Lesotho,48.00,49.30,51.200,58.400,37.300,34.800,48.000,45.900,45.200,40.6000,34.2000
80,Liberia,13.40,19.00,20.000,NaN,17.300,17.300,20.900,20.300,NaN,NaN,NaN
81,Lithuania,5.93,5.89,5.930,4.930,4.620,4.490,4.510,4.530,4.590,4.8200,4.9300
82,Luxembourg,24.20,24.70,24.700,25.100,25.000,24.600,25.700,25.900,25.600,25.0000,25.7000
83,Madagascar,10.70,11.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Malawi,NaN,NaN,NaN,14.500,15.400,15.500,13.600,14.100,15.900,15.2000,15.5000
85,Malaysia,14.50,14.30,14.700,14.900,13.300,14.800,15.600,15.300,14.800,14.3000,13.8000
86,Maldives,11.80,12.10,11.600,9.100,8.850,12.100,NaN,NaN,19.500,NaN,NaN
87,Mali,13.30,13.10,11.900,13.000,12.900,12.500,13.000,13.000,12.600,14.1000,15.4000
88,Malta,60.20,62.90,26.100,26.500,26.100,26.100,26.400,26.800,26.900,25.6000,26.2000
89,Marshall Islands,NaN,NaN,18.400,18.100,17.100,16.700,15.800,15.900,15.900,17.5000,17.8000
90,Mauritius,16.00,15.10,17.000,18.100,18.000,18.000,18.600,18.400,18.500,8.9900,18.1000
91,Mexico,NaN,NaN,10.000,9.680,10.100,10.000,9.770,10.300,10.600,12.8000,13.6000
92,"Micronesia, Fed. Sts.",NaN,NaN,4.290,4.400,4.670,4.980,4.910,5.490,12.600,5.4400,6.0500
93,Moldova,19.60,20.60,20.400,17.700,18.200,18.300,18.600,18.400,19.800,19.5000,19.3000
94,Mongolia,28.70,23.50,21.700,16.500,19.600,18.500,15.300,15.700,12.900,11.8000,11.3000
95,Morocco,21.50,23.90,26.500,23.500,22.800,23.300,NaN,NaN,NaN,NaN,NaN
96,Mozambique,NaN,NaN,NaN,NaN,16.100,18.700,20.400,23.100,25.400,21.9000,20.1000
97,Myanmar,NaN,NaN,NaN,NaN,NaN,NaN,4.520,5.530,5.840,6.0100,6.4100
98,Namibia,29.10,30.90,30.100,29.400,25.900,30.000,32.900,31.500,33.600,32.5000,28.5000
99,Nepal,8.78,9.77,10.400,11.800,13.400,13.300,13.900,15.300,15.900,16.7000,18.7000
100,Netherlands,21.80,21.90,21.400,21.000,21.300,20.400,19.600,19.900,20.900,21.5000,22.2000
101,New Zealand,32.00,30.10,31.500,29.600,26.100,25.600,26.800,26.600,26.800,27.4000,27.2000
102,Nicaragua,13.70,13.90,13.200,13.100,13.700,14.500,15.000,15.000,15.300,15.8000,16.3000
103,Nigeria,2.41,3.98,5.460,5.110,2.270,1.800,1.560,1.480,NaN,NaN,NaN
104,North Macedonia,18.10,19.10,18.500,17.100,16.900,17.000,16.400,15.700,16.200,16.8000,16.8000
105,Norway,28.90,28.10,27.900,25.900,26.800,27.700,27.000,25.100,23.500,22.1000,22.0000
106,Oman,1.94,2.70,2.420,3.390,2.540,2.270,2.600,2.520,NaN,NaN,NaN
107,Pakistan,10.40,9.23,9.490,8.940,9.980,9.190,NaN,NaN,NaN,NaN,NaN
108,Palau,NaN,NaN,16.700,16.000,17.000,18.300,18.000,18.400,19.200,19.3000,19.7000
109,Palestine,4.60,4.63,5.060,5.220,5.450,5.250,4.560,4.810,5.710,5.6000,NaN
110,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000,16.0000,13.5000
111,Paraguay,10.50,10.10,10.800,11.700,12.100,12.600,12.800,12.000,12.700,12.9000,12.6000
112,Peru,15.70,16.40,16.500,14.500,15.500,16.000,16.500,16.400,16.700,14.9000,13.8000
113,Philippines,13.70,13.50,13.600,12.200,12.100,12.400,12.900,13.300,13.600,13.6000,13.7000
114,Poland,17.20,18.10,18.200,15.900,16.500,16.700,16.000,15.600,15.500,15.6000,16.2000
115,Portugal,21.10,21.30,21.000,19.200,19.700,21.200,20.900,22.800,22.700,22.9000,22.5000
116,Qatar,20.10,20.60,15.900,19.900,14.700,NaN,NaN,NaN,NaN,NaN,NaN
117,Romania,17.70,17.40,16.800,15.400,16.600,18.000,17.900,17.600,17.900,18.9000,16.8000
118,Russia,16.60,16.60,15.800,13.000,13.000,13.900,13.700,12.900,13.200,10.6000,9.1300
119,Rwanda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.300,13.7000,14.8000
120,Samoa,NaN,NaN,NaN,NaN,21.700,19.400,19.600,22.100,23.100,22.7000,24.2000
121,San Marino,15.70,15.50,15.400,14.700,13.700,14.200,16.100,15.400,NaN,16.2000,15.4000
122,Sao Tome and Principe,16.10,16.30,14.900,15.200,17.700,17.700,14.600,NaN,NaN,NaN,NaN
123,Senegal,NaN,NaN,NaN,18.000,18.700,19.000,19.000,NaN,19.600,20.6000,20.5000
124,Serbia,NaN,22.80,22.400,21.200,21.400,20.200,19.700,NaN,NaN,NaN,NaN
125,Seychelles,24.70,23.30,22.400,25.200,27.900,31.500,30.400,28.100,30.100,29.6000,31.7000
126,Sierra Leone,8.43,7.88,8.210,8.410,9.080,9.310,9.510,9.120,8.600,NaN,NaN
127,Singapore,11.90,12.90,13.900,13.100,13.000,13.300,13.800,13.400,13.700,13.3000,13.7000
128,Slovak Republic,16.80,16.70,16.400,15.500,15.000,15.500,15.000,15.900,16.700,17.6000,17.4000
129,Slovenia,20.80,20.00,19.400,18.000,18.100,17.900,18.000,18.000,18.200,18.5000,18.6000
130,Solomon Islands,NaN,NaN,NaN,NaN,NaN,28.700,29.200,30.300,29.200,29.2000,26.7000
131,South Africa,27.30,27.60,26.800,24.400,25.000,25.200,25.600,26.000,26.500,27.3000,27.1000
132,South Korea,14.30,15.50,15.100,14.300,14.000,14.400,14.700,14.300,13.900,13.9000,14.8000
133,Spain,16.10,16.70,13.300,11.000,13.000,12.400,12.200,14.000,14.300,14.4000,13.8000
134,Sri Lanka,14.60,14.20,13.300,12.800,11.300,11.300,10.400,10.500,10.100,12.4000,12.3000
135,St. Kitts and Nevis,21.10,22.10,22.500,22.200,22.100,20.300,21.700,19.800,20.400,NaN,NaN
136,St. Lucia,19.70,19.10,21.000,21.200,19.500,19.700,19.100,20.200,20.400,NaN,NaN
137,St. Vincent and the Grenadines,21.90,22.90,23.900,23.700,22.900,22.600,23.000,21.600,23.900,NaN,NaN
138,Suriname,16.70,18.90,17.300,17.200,15.700,18.500,19.500,NaN,NaN,NaN,NaN
139,Swaziland,31.00,27.30,29.800,25.300,16.000,16.300,28.600,NaN,NaN,NaN,NaN
140,Sweden,28.50,28.40,27.000,26.900,27.100,26.500,26.100,26.200,26.300,27.0000,27.7000
141,Switzerland,9.52,9.36,9.910,9.680,9.720,9.650,9.520,9.600,9.400,9.8500,9.7700
142,Syria,14.60,14.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.900,NaN,NaN
144,Thailand,15.60,15.10,15.400,14.200,14.900,16.400,15.400,16.900,15.600,16.0000,15.5000
145,Timor-Leste,NaN,NaN,NaN,NaN,24.300,24.900,25.700,23.200,22.500,18.5000,9.8200
146,Togo,14.80,16.20,14.900,15.300,15.700,16.400,16.600,20.000,NaN,21.8000,21.9000
147,Trinidad and Tobago,30.30,26.00,29.500,26.800,26.200,25.600,26.400,NaN,27.100,NaN,NaN
148,Tunisia,18.50,19.10,20.500,20.000,20.100,21.200,21.100,NaN,NaN,NaN,NaN
149,Turkey,NaN,NaN,17.700,18.300,19.400,18.700,18.400,18.500,18.100,18.2000,18.3000
150,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9000,13.5000
151,Ukraine,17.70,16.50,17.900,16.400,15.600,18.500,18.300,17.600,17.300,20.5000,19.6000
152,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,0.321,0.364,0.370,0.356,0.0577,0.0435
153,United Kingdom,25.70,25.90,26.500,24.200,25.400,26.100,25.200,25.200,24.900,25.2000,25.6000
154,United States,11.30,11.30,10.300,7.940,8.610,9.590,9.820,10.600,11.000,11.2000,10.9000
155,Uruguay,19.00,18.40,18.200,18.700,18.900,19.100,18.800,19.000,18.600,18.5000,23.7000
156,Uzbekistan,NaN,NaN,NaN,NaN,NaN,16.200,17.200,17.500,17.300,17.5000,17.3000
157,Vanuatu,NaN,NaN,NaN,16.000,15.500,16.000,16.600,17.200,17.400,16.7000,16.6000
158,Vietnam,22.20,21.50,22.400,20.600,22.300,22.200,19.000,19.100,NaN,NaN,NaN
159,Zambia,13.70,13.90,14.200,12.500,13.200,17.100,16.200,15.700,17.000,16.8000,14.9000
160,Zimbabwe,NaN,NaN,NaN,10.300,20.700,20.900,21.400,NaN,NaN,NaN,NaN

In [337]:
tax_last_10 = tax_last_10.melt(id_vars=['country'], var_name='year', value_name='tax_%_gdp')
tax_last_10

                  country  year  tax_%_gdp
0             Afghanistan  2006       6.88
1                 Albania  2006        NaN
2                 Algeria  2006      40.80
3                  Angola  2006      29.30
4     Antigua and Barbuda  2006      18.20
...                   ...   ...        ...
1766           Uzbekistan  2016      17.30
1767              Vanuatu  2016      16.60
1768              Vietnam  2016        NaN
1769               Zambia  2016      14.90
1770             Zimbabwe  2016        NaN

[1771 rows x 3 columns]

In [340]:
tax_last_10.sort_values(['country', 'year'], inplace=True)
tax_last_10

          country  year  tax_%_gdp
0     Afghanistan  2006       6.88
161   Afghanistan  2007       5.23
322   Afghanistan  2008       6.04
483   Afghanistan  2009       8.44
644   Afghanistan  2010       9.12
...           ...   ...        ...
1126     Zimbabwe  2012      21.40
1287     Zimbabwe  2013        NaN
1448     Zimbabwe  2014        NaN
1609     Zimbabwe  2015        NaN
1770     Zimbabwe  2016        NaN

[1771 rows x 3 columns]

In [341]:
tax_last_10.to_csv('tax_last_10.csv', index=False)

In [338]:
tax_last_10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1771 entries, 0 to 1770
Data columns (total 3 columns):
country      1771 non-null object
year         1771 non-null object
tax_%_gdp    1437 non-null float64
dtypes: float64(1), object(2)
memory usage: 41.6+ KB

In [342]:
combined_last_10 = combined_last_10.merge(tax_last_10, left_on=['country', 'year'], right_on=['country', 'year'])
combined_last_10

          country  year  demox_eiu  income_per_person  invest_%_gdp  tax_%_gdp
0     Afghanistan  2006       30.6               1120          23.4       6.88
1     Afghanistan  2007       30.4               1250          19.9       5.23
2     Afghanistan  2008       30.2               1270          18.9       6.04
3     Afghanistan  2009       27.5               1500          17.9       8.44
4     Afghanistan  2010       24.8               1670          17.9       9.12
...           ...   ...        ...                ...           ...        ...
1524     Zimbabwe  2012       26.7               2490          11.8      21.40
1525     Zimbabwe  2013       26.7               2490          11.4        NaN
1526     Zimbabwe  2014       27.8               2510          11.8        NaN
1527     Zimbabwe  2015       30.5               2510          12.3        NaN
1528     Zimbabwe  2016       30.5               2490          12.2        NaN

[1529 rows x 6 columns]

In [344]:
combined_last_10 = combined_last_10.merge(gini_last_10, left_on=['country', 'year'], right_on=['country', 'year'])
combined_last_10

,country,year,demox_eiu,income_per_person,invest_%_gdp,tax_%_gdp,gini_index
0,Afghanistan,2006,30.6,1120,23.4,6.88,36.8
1,Afghanistan,2007,30.4,1250,19.9,5.23,36.8
2,Afghanistan,2008,30.2,1270,18.9,6.04,36.8
3,Afghanistan,2009,27.5,1500,17.9,8.44,36.8
4,Afghanistan,2010,24.8,1670,17.9,9.12,36.8
...,...,...,...,...,...,...,...
1524,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2
1525,Zimbabwe,2013,26.7,2490,11.4,NaN,43.2
1526,Zimbabwe,2014,27.8,2510,11.8,NaN,43.2
1527,Zimbabwe,2015,30.5,2510,12.3,NaN,43.2
1528,Zimbabwe,2016,30.5,2490,12.2,NaN,43.2

In [345]:
combined_last_10.to_csv('combined_last_10.csv', index=False)

In [427]:
full = pd.read_csv('gapminder_full.csv')
full

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [442]:
cont = full.loc[:, ['continent', 'country', 'year']]
cont.query('year >= 2006 & year <= 2016')

     continent                   country  year
11        Asia               Afghanistan  2007
23      Europe                   Albania  2007
35      Africa                   Algeria  2007
47      Africa                    Angola  2007
59    Americas                 Argentina  2007
71     Oceania                 Australia  2007
83      Europe                   Austria  2007
95        Asia                   Bahrain  2007
107       Asia                Bangladesh  2007
119     Europe                   Belgium  2007
131     Africa                     Benin  2007
143   Americas                   Bolivia  2007
155     Europe    Bosnia and Herzegovina  2007
167     Africa                  Botswana  2007
179   Americas                    Brazil  2007
191     Europe                  Bulgaria  2007
203     Africa              Burkina Faso  2007
215     Africa                   Burundi  2007
227       Asia                  Cambodia  2007
239     Africa                  Cameroon  2007
251   Americas                    Canada  2007
263     Africa  Central African Republic  2007
275     Africa                      Chad  2007
287   Americas                     Chile  2007
299       Asia                     China  2007
311   Americas                  Colombia  2007
323     Africa                   Comoros  2007
335     Africa          Congo, Dem. Rep.  2007
347     Africa               Congo, Rep.  2007
359   Americas                Costa Rica  2007
371     Africa             Cote d'Ivoire  2007
383     Europe                   Croatia  2007
395   Americas                      Cuba  2007
407     Europe            Czech Republic  2007
419     Europe                   Denmark  2007
431     Africa                  Djibouti  2007
443   Americas        Dominican Republic  2007
455   Americas                   Ecuador  2007
467     Africa                     Egypt  2007
479   Americas               El Salvador  2007
491     Africa         Equatorial Guinea  2007
503     Africa                   Eritrea  2007
515     Africa                  Ethiopia  2007
527     Europe                   Finland  2007
539     Europe                    France  2007
551     Africa                     Gabon  2007
563     Africa                    Gambia  2007
575     Europe                   Germany  2007
587     Africa                     Ghana  2007
599     Europe                    Greece  2007
611   Americas                 Guatemala  2007
623     Africa                    Guinea  2007
635     Africa             Guinea-Bissau  2007
647   Americas                     Haiti  2007
659   Americas                  Honduras  2007
671       Asia          Hong Kong, China  2007
683     Europe                   Hungary  2007
695     Europe                   Iceland  2007
707       Asia                     India  2007
719       Asia                 Indonesia  2007
731       Asia                      Iran  2007
743       Asia                      Iraq  2007
755     Europe                   Ireland  2007
767       Asia                    Israel  2007
779     Europe                     Italy  2007
791   Americas                   Jamaica  2007
803       Asia                     Japan  2007
815       Asia                    Jordan  2007
827     Africa                     Kenya  2007
839       Asia          Korea, Dem. Rep.  2007
851       Asia               Korea, Rep.  2007
863       Asia                    Kuwait  2007
875       Asia                   Lebanon  2007
887     Africa                   Lesotho  2007
899     Africa                   Liberia  2007
911     Africa                     Libya  2007
923     Africa                Madagascar  2007
935     Africa                    Malawi  2007
947       Asia                  Malaysia  2007
959     Africa                      Mali  2007
971     Africa                Mauritania  2007
983     Africa                 Mauritius  2007
995   Americas                    Mexico  2007
1007      Asia                  Mongolia  2007
1019    Europe                Montenegro  2007
1031    Africa                   Morocco  2007
1043    Africa                Mozambique  2007
1055      Asia                   Myanmar  2007
1067    Africa                   Namibia  2007
1079      Asia                     Nepal  2007
1091    Europe               Netherlands  2007
1103   Oceania               New Zealand  2007
1115  Americas                 Nicaragua  2007
1127    Africa                     Niger  2007
1139    Africa                   Nigeria  2007
1151    Europe                    Norway  2007
1163      Asia                      Oman  2007
1175      Asia                  Pakistan  2007
1187  Americas                    Panama  2007
1199  Americas                  Paraguay  2007
1211  Americas                      Peru  2007
1223      Asia               Philippines  2007
1235    Europe                    Poland  2007
1247    Europe                  Portugal  2007
1259  Americas               Puerto Rico  2007
1271    Africa                   Reunion  2007
1283    Europe                   Romania  2007
1295    Africa                    Rwanda  2007
1307    Africa     Sao Tome and Principe  2007
1319      Asia              Saudi Arabia  2007
1331    Africa                   Senegal  2007
1343    Europe                    Serbia  2007
1355    Africa              Sierra Leone  2007
1367      Asia                 Singapore  2007
1379    Europe           Slovak Republic  2007
1391    Europe                  Slovenia  2007
1403    Africa                   Somalia  2007
1415    Africa              South Africa  2007
1427    Europe                     Spain  2007
1439      Asia                 Sri Lanka  2007
1451    Africa                     Sudan  2007
1463    Africa                 Swaziland  2007
1475    Europe                    Sweden  2007
1487    Europe               Switzerland  2007
1499      Asia                     Syria  2007
1511      Asia                    Taiwan  2007
1523    Africa                  Tanzania  2007
1535      Asia                  Thailand  2007
1547    Africa                      Togo  2007
1559  Americas       Trinidad and Tobago  2007
1571    Africa                   Tunisia  2007
1583    Europe                    Turkey  2007
1595    Africa                    Uganda  2007
1607    Europe            United Kingdom  2007
1619  Americas             United States  2007
1631  Americas                   Uruguay  2007
1643  Americas                 Venezuela  2007
1655      Asia                   Vietnam  2007
1667      Asia        West Bank and Gaza  2007
1679      Asia               Yemen, Rep.  2007
1691    Africa                    Zambia  2007
1703    Africa                  Zimbabwe  2007

In [429]:
cont.to_csv('continent_country.csv', index=False)

In [355]:
cont = cont.merge(combined_last_10, left_on='country', right_on='country')
cont

,continent,country,year,demox_eiu,income_per_person,invest_%_gdp,tax_%_gdp,gini_index
0,Asia,Afghanistan,2006,30.6,1120,23.4,6.88,36.8
1,Asia,Afghanistan,2007,30.4,1250,19.9,5.23,36.8
2,Asia,Afghanistan,2008,30.2,1270,18.9,6.04,36.8
3,Asia,Afghanistan,2009,27.5,1500,17.9,8.44,36.8
4,Asia,Afghanistan,2010,24.8,1670,17.9,9.12,36.8
...,...,...,...,...,...,...,...,...
14779,Africa,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2
14780,Africa,Zimbabwe,2013,26.7,2490,11.4,NaN,43.2
14781,Africa,Zimbabwe,2014,27.8,2510,11.8,NaN,43.2
14782,Africa,Zimbabwe,2015,30.5,2510,12.3,NaN,43.2
14783,Africa,Zimbabwe,2016,30.5,2490,12.2,NaN,43.2

In [356]:
cont.to_csv('full_combined_last_10.csv', index=False)

In [380]:
gini_last_10.country.nunique()
gini_last_10.year = gini_last_10.year.astype(int)
gini_last_10.dtypes

country        object
year            int64
gini_index    float64
dtype: object

In [381]:
gini_last_10.to_csv('gini_last_10.csv', index=False)

In [479]:
gini_last_10 = pd.read_csv('gini_last_10.csv')
print("number of rows: ", gini_last_10.shape[0])
print("number of columns: ", gini_last_10.shape[1])
print(gini_last_10.dtypes)
print("number of duplicates", gini_last_10.duplicated().sum())
gini_last_10.head(10)

number of rows:  2145
number of columns:  3
country        object
year            int64
gini_index    float64
dtype: object
number of duplicates 0

       country  year  gini_index
0  Afghanistan  2006        36.8
1  Afghanistan  2007        36.8
2  Afghanistan  2008        36.8
3  Afghanistan  2009        36.8
4  Afghanistan  2010        36.8
5  Afghanistan  2011        36.8
6  Afghanistan  2012        36.8
7  Afghanistan  2013        36.8
8  Afghanistan  2014        36.8
9  Afghanistan  2015        36.8

In [369]:
demox_eiu_last_10 = pd.read_csv('demox_eiu_last_10.csv')

164

In [385]:
demox_eiu_last_10.head(50)
demox_eiu_last_10.year.nunique()
demox_eiu_last_10.shape

(1804, 3)

In [373]:
income_last_10 = pd.read_csv('income_last_10.csv')
income_last_10.shape

(2123, 3)

In [390]:
income_last_10.country.nunique()
income_last_10.dtypes
income_last_10.shape

(2123, 3)

In [389]:
tmp = gini_last_10.merge(demox_eiu_last_10, left_on=['country', 'year'], right_on=['country', 'year'])
tmp.shape, tmp.country.nunique()

((1804, 4), 164)

In [391]:
combined = tmp

In [392]:
tmp = combined.merge(income_last_10, left_on=['country', 'year'], right_on=['country', 'year'])
tmp

          country  year  gini_index  demox_eiu  income_per_person
0     Afghanistan  2006        36.8       30.6               1120
1     Afghanistan  2007        36.8       30.4               1250
2     Afghanistan  2008        36.8       30.2               1270
3     Afghanistan  2009        36.8       27.5               1500
4     Afghanistan  2010        36.8       24.8               1670
...           ...   ...         ...        ...                ...
1799     Zimbabwe  2012        43.2       26.7               2490
1800     Zimbabwe  2013        43.2       26.7               2490
1801     Zimbabwe  2014        43.2       27.8               2510
1802     Zimbabwe  2015        43.2       30.5               2510
1803     Zimbabwe  2016        43.2       30.5               2490

[1804 rows x 5 columns]

In [393]:
combined = tmp

In [396]:
invest_last_10 = pd.read_csv('invest_last_10.csv')
invest_last_10.shape

(1947, 3)

In [397]:
tmp = combined.merge(invest_last_10, left_on=['country', 'year'], right_on=['country', 'year'])

In [399]:
tmp.shape

(1782, 6)

In [400]:
tmp.country.nunique()

162

In [401]:
tax_last_10 = pd.read_csv('tax_last_10.csv')

In [402]:
tax_last_10.shape, tax_last_10.dtypes

((1771, 3), country       object
 year           int64
 tax_%_gdp    float64
 dtype: object)

In [404]:
tax_last_10.isnull().sum()

country        0
year           0
tax_%_gdp    334
dtype: int64

In [405]:
tax_last_10.dropna(inplace=True)

In [406]:
tax_last_10.isnull().sum(), tax_last_10.shape

(country      0
 year         0
 tax_%_gdp    0
 dtype: int64, (1437, 3))

In [416]:
tax_last_10.country.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Canada',
       'Cape Verde', 'Central African Republic', 'Chile', 'China',
       'Colombia', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark',
       'Dominica', 'Dominican Republic', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland',
       'France', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyz Republic', 'Lao', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Moldova',
       'Mongolia', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau',
       'Palestine', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovak Republic', 'Slovenia', 'Solomon Islands', 'South Africa',
       'South Korea', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis',
       'St. Lucia', 'St. Vincent and the Grenadines', 'Suriname',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Tanzania',
       'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Vietnam', 'Zambia', 'Zimbabwe'], dtype=object)

In [410]:
combined = tmp

In [417]:
tmp = combined.merge(tax_last_10, left_on=['country', 'year'], right_on=['country', 'year'])

In [425]:
#tmp = tmp.drop('gini_index', axis=1)
tmp = tmp.merge(gini_last_10, left_on=['country', 'year'], right_on=['country', 'year'])
tmp

,country,year,demox_eiu,income_per_person,invest_%_gdp,tax_%_gdp,gini_index
0,Afghanistan,2006,30.6,1120,23.4,6.88,36.8
1,Afghanistan,2007,30.4,1250,19.9,5.23,36.8
2,Afghanistan,2008,30.2,1270,18.9,6.04,36.8
3,Afghanistan,2009,27.5,1500,17.9,8.44,36.8
4,Afghanistan,2010,24.8,1670,17.9,9.12,36.8
...,...,...,...,...,...,...,...
1239,Zambia,2016,59.9,3700,38.2,14.90,57.1
1240,Zimbabwe,2009,25.9,1630,14.3,10.30,43.2
1241,Zimbabwe,2010,26.4,1930,22.3,20.70,43.2
1242,Zimbabwe,2011,26.8,2170,20.3,20.90,43.2
1243,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2

In [430]:
combined = tmp

In [431]:
combined.shape

(1244, 7)

In [450]:
cont = pd.read_csv('continent_country.csv')
cont

     continent      country
0         Asia  Afghanistan
1         Asia  Afghanistan
2         Asia  Afghanistan
3         Asia  Afghanistan
4         Asia  Afghanistan
...        ...          ...
1699    Africa     Zimbabwe
1700    Africa     Zimbabwe
1701    Africa     Zimbabwe
1702    Africa     Zimbabwe
1703    Africa     Zimbabwe

[1704 rows x 2 columns]

In [454]:
tmp = combined.merge(cont, left_on=['country'], right_on=['country'])
tmp

,country,year,demox_eiu,income_per_person,invest_%_gdp,tax_%_gdp,gini_index,continent
0,Afghanistan,2006,30.6,1120,23.4,6.88,36.8,Asia
1,Afghanistan,2006,30.6,1120,23.4,6.88,36.8,Asia
2,Afghanistan,2006,30.6,1120,23.4,6.88,36.8,Asia
3,Afghanistan,2006,30.6,1120,23.4,6.88,36.8,Asia
4,Afghanistan,2006,30.6,1120,23.4,6.88,36.8,Asia
...,...,...,...,...,...,...,...,...
12079,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2,Africa
12080,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2,Africa
12081,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2,Africa
12082,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2,Africa
12083,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2,Africa

In [455]:
tmp.shape

(12084, 8)

In [449]:
cont

0       1952
1       1957
2       1962
3       1967
4       1972
        ...
1699    1987
1700    1992
1701    1997
1702    2002
1703    2007
Name: year, Length: 1704, dtype: int64

In [457]:
tmp = cont.merge(combined, left_on=['country'], right_on=['country'])
tmp

,continent,country,year,demox_eiu,income_per_person,invest_%_gdp,tax_%_gdp,gini_index
0,Asia,Afghanistan,2006,30.6,1120,23.4,6.88,36.8
1,Asia,Afghanistan,2007,30.4,1250,19.9,5.23,36.8
2,Asia,Afghanistan,2008,30.2,1270,18.9,6.04,36.8
3,Asia,Afghanistan,2009,27.5,1500,17.9,8.44,36.8
4,Asia,Afghanistan,2010,24.8,1670,17.9,9.12,36.8
...,...,...,...,...,...,...,...,...
12079,Africa,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2
12080,Africa,Zimbabwe,2009,25.9,1630,14.3,10.30,43.2
12081,Africa,Zimbabwe,2010,26.4,1930,22.3,20.70,43.2
12082,Africa,Zimbabwe,2011,26.8,2170,20.3,20.90,43.2
12083,Africa,Zimbabwe,2012,26.7,2490,11.8,21.40,43.2

In [458]:
tmp.shape

(12084, 8)

In [460]:
tmp = tmp.drop_duplicates()

In [462]:
combined = tmp

In [463]:
combined.to_csv('combined_cleaned.csv', index=False)

In [501]:
combined.country.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Canada',
       'Central African Republic', 'Chile', 'China', 'Colombia',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Czech Republic', 'Denmark', 'Dominican Republic',
       'Egypt', 'El Salvador', 'Equatorial Guinea', 'Ethiopia', 'Finland',
       'France', 'Gambia', 'Germany', 'Ghana', 'Greece', 'Guatemala',
       'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kenya', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Madagascar',
       'Malawi', 'Malaysia', 'Mali', 'Mauritius', 'Mexico', 'Mongolia',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria', 'Norway',
       'Oman', 'Pakistan', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Romania', 'Rwanda', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'South Africa', 'Spain', 'Sri Lanka', 'Swaziland', 'Sweden',
       'Switzerland', 'Syria', 'Tanzania', 'Thailand', 'Togo', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Vietnam', 'Zambia', 'Zimbabwe'], dtype=object)

In [466]:
combined.head(50)

,continent,country,year,demox_eiu,income_per_person,invest_%_gdp,tax_%_gdp,gini_index
0,Asia,Afghanistan,2006,30.6,1120,23.40,6.88,36.8
1,Asia,Afghanistan,2007,30.4,1250,19.90,5.23,36.8
2,Asia,Afghanistan,2008,30.2,1270,18.90,6.04,36.8
3,Asia,Afghanistan,2009,27.5,1500,17.90,8.44,36.8
4,Asia,Afghanistan,2010,24.8,1670,17.90,9.12,36.8
5,Asia,Afghanistan,2011,24.8,1630,16.60,8.85,36.8
6,Asia,Afghanistan,2012,24.8,1770,16.80,7.47,36.8
7,Asia,Afghanistan,2013,24.8,1810,17.20,7.08,36.8
8,Asia,Afghanistan,2014,27.7,1800,18.10,6.84,36.8
9,Asia,Afghanistan,2015,27.7,1770,19.40,7.55,36.8
120,Europe,Albania,2011,58.1,10200,31.40,18.00,29.3
121,Europe,Albania,2012,56.7,10400,28.30,17.50,29.1
122,Europe,Albania,2013,56.7,10500,28.40,16.50,29.0
123,Europe,Albania,2014,56.7,10700,24.60,18.30,29.0
124,Europe,Albania,2015,59.1,11000,24.40,18.50,29.0
125,Europe,Albania,2016,59.1,11400,24.80,17.60,29.0
192,Africa,Algeria,2006,31.7,12400,30.20,40.80,30.3
193,Africa,Algeria,2007,32.5,12600,34.50,37.40,29.9
194,Africa,Algeria,2008,33.2,12700,37.30,45.30,29.4
195,Africa,Algeria,2009,33.8,12700,46.90,35.10,29.0
196,Africa,Algeria,2010,34.4,12900,41.40,34.40,28.5
197,Africa,Algeria,2011,34.4,13000,38.10,37.20,28.2
264,Africa,Angola,2006,24.1,5500,15.40,29.30,46.2
265,Africa,Angola,2007,28.8,6040,13.50,23.20,45.0
266,Africa,Angola,2008,33.5,6470,16.20,27.00,44.1
267,Africa,Angola,2009,33.4,6290,15.20,17.10,43.4
268,Africa,Angola,2010,33.2,6360,14.40,16.90,42.9
269,Africa,Angola,2011,33.2,6350,12.90,17.30,42.7
270,Africa,Angola,2012,33.5,6650,15.10,16.70,42.6
271,Africa,Angola,2013,33.5,6730,14.70,15.50,42.6
272,Africa,Angola,2014,33.5,6810,15.30,15.60,42.6
273,Africa,Angola,2015,33.5,6650,9.55,12.50,42.6
274,Africa,Angola,2016,34.0,6260,8.40,10.30,42.6
396,Americas,Argentina,2006,66.3,16700,18.70,12.90,46.7
397,Americas,Argentina,2007,66.3,18000,20.10,12.40,45.8
398,Americas,Argentina,2008,66.3,18600,19.60,13.30,44.9
399,Americas,Argentina,2009,67.3,17300,16.10,12.40,44.0
400,Americas,Argentina,2010,68.4,18900,17.70,12.90,43.0
401,Americas,Argentina,2011,68.4,19800,18.40,12.70,42.3
402,Americas,Argentina,2012,68.4,19400,16.50,13.00,41.8
403,Americas,Argentina,2013,68.4,19600,17.30,12.50,41.6
404,Americas,Argentina,2014,68.4,18900,17.30,12.60,41.6
405,Americas,Argentina,2015,70.2,19200,17.10,12.30,41.8
406,Americas,Argentina,2016,69.6,18600,17.00,12.20,42.1
528,Oceania,Australia,2006,90.9,39500,27.60,24.60,34.7
529,Oceania,Australia,2007,90.9,40700,27.50,24.10,34.9
530,Oceania,Australia,2008,90.9,41400,28.60,24.30,35.0
531,Oceania,Australia,2009,91.5,41300,27.30,22.10,34.2
532,Oceania,Australia,2010,92.2,41500,26.80,20.60,33.6
533,Oceania,Australia,2011,92.2,42000,26.40,20.40,32.9

In [468]:
combined.country.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Canada',
       'Central African Republic', 'Chile', 'China', 'Colombia',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Czech Republic', 'Denmark', 'Dominican Republic',
       'Egypt', 'El Salvador', 'Equatorial Guinea', 'Ethiopia', 'Finland',
       'France', 'Gambia', 'Germany', 'Ghana', 'Greece', 'Guatemala',
       'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kenya', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Madagascar',
       'Malawi', 'Malaysia', 'Mali', 'Mauritius', 'Mexico', 'Mongolia',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria', 'Norway',
       'Oman', 'Pakistan', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Romania', 'Rwanda', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'South Africa', 'Spain', 'Sri Lanka', 'Swaziland', 'Sweden',
       'Switzerland', 'Syria', 'Tanzania', 'Thailand', 'Togo', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Vietnam', 'Zambia', 'Zimbabwe'], dtype=object)

In [480]:
tax = pd.read_csv('tax_revenue_percent_of_gdp.csv')
tax

,country,1972,1973,1974,1975,1976,1977,1978,1979,1980,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.040,8.440,9.120,8.850,7.470,7.080,6.840,7.5500,NaN,NaN
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.000,17.500,16.500,18.300,18.5000,17.6000,NaN
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.300,35.100,34.400,37.200,NaN,NaN,NaN,NaN,NaN,NaN
3,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.000,17.100,16.900,17.300,16.700,15.500,15.600,12.5000,10.3000,NaN
4,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.700,17.300,18.500,17.900,18.500,17.200,16.500,NaN,NaN,NaN
5,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.300,12.400,12.900,12.700,13.000,12.500,12.600,12.3000,12.2000,NaN
6,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.300,16.500,17.100,17.200,17.500,NaN,21.600,20.9000,21.3000,NaN
7,Australia,17.90,17.00,18.10,19.90,20.30,20.60,20.40,19.80,20.40,...,24.300,22.100,20.600,20.400,21.200,22.100,22.000,22.0000,22.3000,NaN
8,Austria,17.90,18.20,18.40,18.00,17.90,18.00,18.80,18.60,18.60,...,26.100,25.200,25.300,25.400,25.900,26.400,26.400,26.8000,25.7000,NaN
9,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.400,14.100,12.200,12.200,12.800,13.400,14.200,15.6000,NaN,NaN
10,Bahamas,NaN,14.50,16.70,16.30,17.20,15.90,16.30,15.30,15.00,...,12.100,11.300,10.900,12.900,11.900,11.400,11.400,12.7000,14.2000,NaN
11,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.240,1.360,1.180,1.110,NaN,1.070,NaN,NaN,NaN,NaN
12,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.660,7.500,7.830,8.690,9.020,8.960,8.640,8.5000,8.7700,NaN
13,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.400,24.900,25.100,25.900,24.200,23.400,24.000,26.1000,NaN,NaN
14,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.400,19.300,16.300,14.500,14.700,13.400,12.700,14.2000,13.8000,NaN
15,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.100,23.600,24.300,24.700,25.700,26.200,26.300,24.7000,23.1000,NaN
16,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.700,22.500,23.600,22.600,22.500,23.300,23.400,NaN,NaN,NaN
17,Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.100,15.000,15.500,14.800,14.400,15.400,NaN,NaN,NaN,NaN
18,Bhutan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.420,9.240,13.100,13.500,14.700,14.400,13.300,13.8000,13.2000,NaN
19,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.300,18.900,19.700,20.300,20.500,19.800,19.800,19.9000,20.0000,NaN
21,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.400,27.300,23.600,23.200,26.600,25.600,25.800,24.7000,20.8000,NaN
22,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.10,...,15.500,14.400,13.600,14.200,13.700,13.400,12.800,12.8000,12.9000,NaN
23,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.200,19.000,18.500,17.700,19.000,19.800,19.600,20.2000,20.0000,NaN
24,Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.900,12.500,12.700,13.700,15.600,16.800,15.400,15.1000,15.8000,NaN
25,Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13.900,14.700,13.700,12.200,NaN,NaN,NaN,NaN
26,Cambodia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.600,9.650,10.000,10.200,11.100,12.100,14.600,14.2000,15.3000,NaN
27,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.400,12.300,11.800,11.800,11.700,11.700,11.800,12.3000,12.2000,12.20
28,Cape Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.300,18.400,NaN,NaN,17.900,NaN,NaN,NaN,NaN,NaN
29,Central African Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.060,9.170,10.100,9.290,NaN,NaN,NaN,NaN,NaN,NaN
30,Chile,16.20,17.40,16.30,20.60,18.40,18.80,18.70,17.90,19.00,...,18.700,14.500,17.400,18.900,19.000,17.400,17.000,17.4000,17.4000,NaN
31,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.100,10.300,10.200,10.300,10.200,9.870,9.670,9.3700,NaN,NaN
32,Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.900,12.600,12.100,14.600,13.300,14.100,15.000,15.1000,13.3000,NaN
33,"Congo, Dem. Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.970,7.890,8.350,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"Congo, Rep.",16.80,15.50,25.00,20.40,NaN,NaN,NaN,NaN,25.40,...,5.950,8.400,7.600,8.860,9.430,NaN,NaN,NaN,NaN,NaN
35,Costa Rica,11.40,12.50,13.60,12.40,12.20,12.30,12.70,11.90,11.60,...,15.300,13.300,13.100,13.400,13.300,13.700,13.400,13.7000,14.0000,NaN
36,Cote d'Ivoire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.100,14.600,14.300,10.900,14.300,14.500,14.000,15.4000,15.2000,NaN
37,Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000,19.200,19.100,18.400,19.500,19.000,19.100,NaN,NaN,NaN
38,Cyprus,NaN,NaN,NaN,13.40,12.10,13.20,13.60,14.20,14.80,...,46.100,23.300,23.200,23.300,23.300,23.400,24.500,24.1000,24.3000,NaN
39,Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.400,13.400,13.400,14.300,14.700,14.900,14.200,14.6000,14.7000,NaN
40,Denmark,29.00,28.90,29.10,26.70,26.50,27.10,28.10,28.60,28.50,...,33.400,33.200,32.700,32.800,33.400,33.800,36.500,33.9000,33.7000,NaN
41,Dominica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.800,24.300,24.600,23.100,23.000,22.400,22.100,NaN,NaN,NaN
42,Dominican Republic,13.90,13.40,14.40,16.10,13.30,12.50,11.30,11.00,10.50,...,14.200,12.600,12.200,12.300,13.000,13.500,13.600,13.3000,13.5000,NaN
43,Egypt,NaN,NaN,NaN,20.90,17.30,25.10,23.00,21.10,NaN,...,15.300,15.700,14.100,14.000,12.400,13.500,12.200,12.5000,NaN,NaN
44,El Salvador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.100,15.000,15.800,15.300,16.200,17.100,16.700,16.9000,17.6000,NaN
45,Equatorial Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.790,12.800,7.590,7.020,8.740,8.520,8.300,11.5000,NaN,NaN
46,Estonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.240,1.370,1.270,1.230,1.270,1.290,1.340,1.4000,1.4300,NaN
47,Ethiopia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.810,6.580,8.160,9.210,9.380,8.760,NaN,NaN,NaN,NaN
48,Fiji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,21.800,23.000,23.200,23.600,24.600,25.5000,NaN,NaN
49,Finland,21.70,22.00,21.30,22.10,24.70,24.20,22.40,21.20,21.40,...,20.500,19.000,18.700,20.100,20.300,20.700,20.800,20.7000,21.0000,NaN
50,France,18.70,17.80,18.90,17.70,18.80,18.20,18.30,18.80,19.30,...,22.000,20.700,22.000,21.800,22.600,23.200,23.200,23.2000,23.1000,NaN
51,Gambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.700,15.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.800,23.100,22.100,23.800,24.100,23.400,23.500,23.8000,23.5000,NaN
53,Germany,10.80,11.00,10.50,10.10,10.20,10.50,10.50,10.40,10.30,...,11.400,11.600,11.100,11.400,11.600,11.600,11.500,11.4000,11.2000,NaN
54,Ghana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Greece,12.90,12.50,12.60,12.70,14.10,14.00,14.30,13.90,13.80,...,20.200,19.800,20.200,22.100,23.600,23.700,24.400,24.9000,26.7000,NaN
56,Grenada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.500,18.200,18.700,19.200,18.700,18.400,19.400,NaN,NaN,NaN
57,Guatemala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.300,10.300,10.400,10.800,10.800,10.900,10.800,10.2000,10.4000,NaN
58,Honduras,10.70,10.80,11.10,11.10,11.70,13.10,12.70,12.80,13.60,...,16.100,14.200,14.400,14.800,14.700,15.100,16.500,17.3000,NaN,NaN
59,Hungary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.300,23.300,22.800,21.100,22.900,22.700,23.000,23.4000,23.4000,NaN
60,Iceland,23.20,23.20,24.10,23.20,22.10,21.10,21.50,22.20,21.50,...,23.200,20.100,20.700,21.200,22.100,22.700,25.300,23.5000,38.5000,NaN
61,India,NaN,NaN,8.29,9.15,9.31,8.71,9.43,9.82,9.15,...,11.100,9.940,10.500,10.200,10.800,11.000,NaN,NaN,NaN,NaN
62,Indonesia,12.40,13.80,16.00,16.60,17.90,17.70,17.90,20.30,21.80,...,13.300,11.100,10.500,11.200,11.400,11.300,10.800,10.8000,10.3000,NaN
63,Iran,8.27,7.55,5.42,8.19,7.56,8.22,8.87,5.99,5.17,...,6.200,7.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.890,1.2300,2.0200,NaN
65,Ireland,21.80,22.10,22.00,21.30,23.60,22.50,22.10,21.90,24.20,...,23.700,22.000,21.800,21.800,22.500,22.800,23.200,18.9000,18.8000,NaN
66,Israel,25.70,24.30,30.60,30.40,33.80,35.10,33.20,37.80,35.90,...,23.800,21.900,22.500,22.700,22.100,23.000,23.300,23.4000,23.4000,NaN
67,Italy,NaN,12.60,13.50,12.80,14.10,15.00,15.70,15.80,17.40,...,21.900,22.400,22.300,22.300,23.600,23.700,23.500,23.4000,23.7000,NaN
68,Jamaica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.700,25.000,24.300,23.400,24.300,24.000,24.100,24.8000,26.1000,NaN
69,Japan,10.50,11.70,11.30,9.35,9.13,9.16,9.25,9.95,10.50,...,8.930,8.370,8.810,9.360,9.680,10.400,11.500,11.4000,11.1000,NaN
70,Jordan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.800,17.000,16.000,15.000,15.300,15.300,NaN,NaN,NaN,NaN
71,Kazakhstan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,15.700,18.300,13.300,16.000,14.200,9.8400,9.9200,NaN
72,Kenya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,16.900,16.3000,15.8000,NaN
73,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16.000,18.100,18.500,17.800,17.800,22.3000,24.5000,NaN
74,Kuwait,37.40,37.20,32.70,NaN,NaN,4.62,7.60,2.18,2.70,...,0.876,0.971,0.979,0.800,0.716,0.777,0.890,1.3800,NaN,NaN
75,Kyrgyz Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,17.600,17.500,16.8000,16.9000,NaN
76,Lao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.100,12.800,13.000,13.100,13.600,13.700,13.800,13.5000,12.9000,NaN
77,Latvia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.800,18.800,19.800,20.000,21.100,22.000,22.400,22.8000,23.9000,NaN
78,Lebanon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.400,16.800,16.900,16.300,15.200,14.300,14.200,13.6000,13.9000,NaN
79,Lesotho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.200,58.400,37.300,34.800,48.000,45.900,45.200,40.6000,34.2000,36.40
80,Liberia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000,NaN,17.300,17.300,20.900,20.300,NaN,NaN,NaN,NaN
81,Lithuania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.930,4.930,4.620,4.490,4.510,4.530,4.590,4.8200,4.9300,NaN
82,Luxembourg,16.10,16.60,17.10,20.00,19.60,22.00,22.90,21.10,21.60,...,24.700,25.100,25.000,24.600,25.700,25.900,25.600,25.0000,25.7000,NaN
83,Madagascar,59.00,56.30,NaN,NaN,NaN,NaN,65.40,62.00,57.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Malawi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,14.500,15.400,15.500,13.600,14.100,15.900,15.2000,15.5000,17.30
85,Malaysia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.700,14.900,13.300,14.800,15.600,15.300,14.800,14.3000,13.8000,NaN
86,Maldives,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.12,...,11.600,9.100,8.850,12.100,NaN,NaN,19.500,NaN,NaN,NaN
87,Mali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.900,13.000,12.900,12.500,13.000,13.000,12.600,14.1000,15.4000,NaN
88,Malta,21.20,22.00,20.70,18.90,17.70,18.40,19.20,NaN,19.70,...,26.100,26.500,26.100,26.100,26.400,26.800,26.900,25.6000,26.2000,NaN
89,Marshall Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.400,18.100,17.100,16.700,15.800,15.900,15.900,17.5000,17.8000,NaN
90,Mauritius,NaN,NaN,NaN,NaN,20.00,19.60,17.70,16.40,18.30,...,17.000,18.100,18.000,18.000,18.600,18.400,18.500,8.9900,18.1000,NaN
91,Mexico,7.61,7.09,8.00,9.18,9.04,9.95,10.70,11.30,12.10,...,10.000,9.680,10.100,10.000,9.770,10.300,10.600,12.8000,13.6000,NaN
92,"Micronesia, Fed. Sts.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.290,4.400,4.670,4.980,4.910,5.490,12.600,5.4400,6.0500,NaN
93,Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.400,17.700,18.200,18.300,18.600,18.400,19.800,19.5000,19.3000,NaN
94,Mongolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.700,16.500,19.600,18.500,15.300,15.700,12.900,11.8000,11.3000,NaN
95,Morocco,14.90,15.60,15.50,19.80,16.60,20.00,19.50,20.00,16.60,...,26.500,23.500,22.800,23.300,NaN,NaN,NaN,NaN,NaN,NaN
96,Mozambique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16.100,18.700,20.400,23.100,25.400,21.9000,20.1000,NaN
97,Myanmar,NaN,9.42,7.61,7.92,8.81,10.50,10.00,10.20,9.61,...,NaN,NaN,NaN,NaN,4.520,5.530,5.840,6.0100,6.4100,5.82
98,Namibia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.100,29.400,25.900,30.000,32.900,31.500,33.600,32.5000,28.5000,NaN
99,Nepal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.400,11.800,13.400,13.300,13.900,15.300,15.900,16.7000,18.7000,21.30
100,Netherlands,NaN,22.80,21.50,22.60,22.60,23.70,23.50,23.40,23.40,...,21.400,21.000,21.300,20.400,19.600,19.900,20.900,21.5000,22.2000,NaN
101,New Zealand,23.80,25.60,28.10,27.70,27.50,29.60,28.10,29.40,29.40,...,31.500,29.600,26.100,25.600,26.800,26.600,26.800,27.4000,27.2000,NaN
102,Nicaragua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.200,13.100,13.700,14.500,15.000,15.000,15.300,15.8000,16.3000,NaN
103,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.460,5.110,2.270,1.800,1.560,1.480,NaN,NaN,NaN,NaN
104,North Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.500,17.100,16.900,17.000,16.400,15.700,16.200,16.8000,16.8000,NaN
105,Norway,23.00,20.70,20.50,20.40,21.50,22.10,21.80,22.20,25.10,...,27.900,25.900,26.800,27.700,27.000,25.100,23.500,22.1000,22.0000,NaN
106,Oman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.420,3.390,2.540,2.270,2.600,2.520,NaN,NaN,NaN,NaN
107,Pakistan,NaN,10.40,11.90,10.80,10.90,11.00,11.50,12.30,13.30,...,9.490,8.940,9.980,9.190,NaN,NaN,NaN,NaN,NaN,NaN
108,Palau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.700,16.000,17.000,18.300,18.000,18.400,19.200,19.3000,19.7000,NaN
109,Palestine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.060,5.220,5.450,5.250,4.560,4.810,5.710,5.6000,NaN,NaN
110,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18.000,16.0000,13.5000,NaN
111,Paraguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.800,11.700,12.100,12.600,12.800,12.000,12.700,12.9000,12.6000,13.20
112,Peru,12.70,10.80,11.00,11.60,11.20,11.70,12.50,13.80,18.00,...,16.500,14.500,15.500,16.000,16.500,16.400,16.700,14.9000,13.8000,NaN
113,Philippines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.600,12.200,12.100,12.400,12.900,13.300,13.600,13.6000,13.7000,NaN
114,Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.200,15.900,16.500,16.700,16.000,15.600,15.500,15.6000,16.2000,NaN
115,Portugal,NaN,11.50,11.80,12.30,13.80,14.10,13.50,13.80,15.20,...,21.000,19.200,19.700,21.200,20.900,22.800,22.700,22.9000,22.5000,NaN
116,Qatar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.900,19.900,14.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.800,15.400,16.600,18.000,17.900,17.600,17.900,18.9000,16.8000,NaN
118,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.800,13.000,13.000,13.900,13.700,12.900,13.200,10.6000,9.1300,NaN
119,Rwanda,NaN,8.63,10.20,7.52,9.91,10.90,9.72,11.70,10.50,...,NaN,NaN,NaN,NaN,NaN,NaN,13.300,13.7000,14.8000,NaN
120,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,21.700,19.400,19.600,22.100,23.100,22.7000,24.2000,24.30
121,San Marino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.400,14.700,13.700,14.200,16.100,15.400,NaN,16.2000,15.4000,NaN
122,Sao Tome and Principe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.900,15.200,17.700,17.700,14.600,NaN,NaN,NaN,NaN,NaN
123,Senegal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,18.000,18.700,19.000,19.000,NaN,19.600,20.6000,20.5000,NaN
124,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.400,21.200,21.400,20.200,19.700,NaN,NaN,NaN,NaN,NaN
125,Seychelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.400,25.200,27.900,31.500,30.400,28.100,30.100,29.6000,31.7000,NaN
126,Sierra Leone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.210,8.410,9.080,9.310,9.510,9.120,8.600,NaN,NaN,NaN
127,Singapore,14.60,14.80,15.10,16.60,16.00,16.70,15.90,16.00,17.00,...,13.900,13.100,13.000,13.300,13.800,13.400,13.700,13.3000,13.7000,NaN
128,Slovak Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.400,15.500,15.000,15.500,15.000,15.900,16.700,17.6000,17.4000,NaN
129,Slovenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.400,18.000,18.100,17.900,18.000,18.000,18.200,18.5000,18.6000,NaN
130,Solomon Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,28.700,29.200,30.300,29.200,29.2000,26.7000,NaN
131,South Africa,17.20,17.80,17.40,18.30,18.20,19.10,19.10,19.30,19.20,...,26.800,24.400,25.000,25.200,25.600,26.000,26.500,27.3000,27.1000,NaN
132,South Korea,11.20,10.50,11.60,13.30,14.50,14.20,14.60,14.80,14.80,...,15.100,14.300,14.000,14.400,14.700,14.300,13.900,13.9000,14.8000,NaN
133,Spain,8.98,9.35,8.60,8.79,9.05,8.92,9.53,9.70,9.70,...,13.300,11.000,13.000,12.400,12.200,14.000,14.300,14.4000,13.8000,NaN
134,Sri Lanka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.300,12.800,11.300,11.300,10.400,10.500,10.100,12.4000,12.3000,NaN
135,St. Kitts and Nevis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.500,22.200,22.100,20.300,21.700,19.800,20.400,NaN,NaN,NaN
136,St. Lucia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.000,21.200,19.500,19.700,19.100,20.200,20.400,NaN,NaN,NaN
137,St. Vincent and the Grenadines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.900,23.700,22.900,22.600,23.000,21.600,23.900,NaN,NaN,NaN
138,Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.300,17.200,15.700,18.500,19.500,NaN,NaN,NaN,NaN,NaN
139,Swaziland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.800,25.300,16.000,16.300,28.600,NaN,NaN,NaN,NaN,NaN
140,Sweden,19.30,17.80,17.30,16.70,19.60,20.30,18.60,17.00,16.50,...,27.000,26.900,27.100,26.500,26.100,26.200,26.300,27.0000,27.7000,NaN
141,Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.51,...,9.910,9.680,9.720,9.650,9.520,9.600,9.400,9.8500,9.7700,NaN
142,Syria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.900,NaN,NaN,NaN
144,Thailand,11.00,10.20,12.60,11.20,10.80,11.60,11.70,12.40,13.10,...,15.400,14.200,14.900,16.400,15.400,16.900,15.600,16.0000,15.5000,NaN
145,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,24.300,24.900,25.700,23.200,22.500,18.5000,9.8200,NaN
146,Togo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.900,15.300,15.700,16.400,16.600,20.000,NaN,21.8000,21.9000,NaN
147,Trinidad and Tobago,NaN,NaN,NaN,NaN,29.60,32.60,28.70,29.20,35.70,...,29.500,26.800,26.200,25.600,26.400,NaN,27.100,NaN,NaN,NaN
148,Tunisia,17.80,19.00,17.90,20.20,19.90,21.30,22.60,21.80,21.00,...,20.500,20.000,20.100,21.200,21.100,NaN,NaN,NaN,NaN,NaN
149,Turkey,13.40,14.30,13.20,14.70,16.30,16.70,16.50,14.60,14.30,...,17.700,18.300,19.400,18.700,18.400,18.500,18.100,18.2000,18.3000,NaN
150,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9000,13.5000,NaN
151,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.900,16.400,15.600,18.500,18.300,17.600,17.300,20.5000,19.6000,NaN
152,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.321,0.364,0.370,0.356,0.0577,0.0435,NaN
153,United Kingdom,23.00,21.10,23.70,24.30,23.80,23.30,22.20,21.90,23.90,...,26.500,24.200,25.400,26.100,25.200,25.200,24.900,25.2000,25.6000,NaN
154,United States,11.80,11.50,11.80,11.20,10.70,11.60,11.50,12.00,12.10,...,10.300,7.940,8.610,9.590,9.820,10.600,11.000,11.2000,10.9000,NaN
155,Uruguay,13.70,10.40,12.70,12.20,15.50,15.80,16.00,14.40,15.80,...,18.200,18.700,18.900,19.100,18.800,19.000,18.600,18.5000,23.7000,NaN
156,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16.200,17.200,17.500,17.300,17.5000,17.3000,NaN
157,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,16.000,15.500,16.000,16.600,17.200,17.400,16.7000,16.6000,NaN
158,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.400,20.600,22.300,22.200,19.000,19.100,NaN,NaN,NaN,NaN
159,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.200,12.500,13.200,17.100,16.200,15.700,17.000,16.8000,14.9000,NaN
160,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.300,20.700,20.900,21.400,NaN,NaN,NaN,NaN,NaN

In [483]:
tax.shape

(161, 47)

In [485]:
tax['1972'].isnull().sum()/tax.shape[0]
tax['1973'].isnull().sum()/tax.shape[0]

0.7204968944099379

In [498]:
tax.isnull().sum()/tax.shape[0]*100

country     0.000000
1972       76.397516
1973       72.049689
1974       72.049689
1975       71.428571
1976       70.807453
1977       70.186335
1978       69.565217
1979       70.186335
1980       67.701863
1981       68.322981
1982       69.565217
1983       68.944099
1984       68.944099
1985       67.701863
1986       67.701863
1987       69.565217
1988       66.459627
1989       66.459627
1990       52.173913
1991       52.173913
1992       50.310559
1993       49.068323
1994       47.204969
1995       41.614907
1996       41.614907
1997       39.130435
1998       38.509317
1999       37.267081
2000       39.130435
2001       34.161491
2002       30.434783
2003       27.950311
2004       26.708075
2005       23.602484
2006       21.739130
2007       21.739130
2008       16.770186
2009       14.906832
2010       11.180124
2011       10.559006
2012       13.043478
2013       18.633540
2014       20.496894
2015       26.086957
2016       32.298137
2017       95.652174
dtype: float64

In [496]:
tax_melt = tax.melt(id_vars=['country'], var_name='year', value_name="tax_%_gdp")
tax_melt.isnull().sum()

country         0
year            0
tax_%_gdp    3523
dtype: int64

In [494]:
#tax_melt.groupby('year').isnull().sum()
tax_melt['tax_%_gdp'].isnull().groupby([tax_melt['year']]).sum().astype(int).reset_index(name='count').sort_values(by=['count'])

    year  count
39  2011     17
38  2010     18
40  2012     21
37  2009     24
36  2008     27
41  2013     30
42  2014     33
35  2007     35
34  2006     35
33  2005     38
43  2015     42
32  2004     43
31  2003     45
30  2002     49
44  2016     52
29  2001     55
27  1999     60
26  1998     62
28  2000     63
25  1997     63
24  1996     67
23  1995     67
22  1994     76
21  1993     79
20  1992     81
19  1991     84
18  1990     84
16  1988    107
17  1989    107
8   1980    109
14  1986    109
13  1985    109
9   1981    110
12  1984    111
11  1983    111
10  1982    112
15  1987    112
6   1978    112
7   1979    113
5   1977    113
4   1976    114
3   1975    115
2   1974    116
1   1973    116
0   1972    123
45  2017    154